### ISSUE TITLE
snipping.pileup question

### ISSUE THREAD

**Issue by sabrsyed** [open2c/cooltools#110]
Hi, I'm encountering the following error when trying to use snipping.pileup and any help would be much appreciated. 

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-30-6a5d9746523c> in <module>
      5     print(expected.head())
      6     snipper = snipping.ObsExpSnipper(clrs20kb[cond], expected)
----> 7     stack = snipping.pileup(windows, snipper.select, snipper.snip)
      8     #stacks[cond] = stack
      9     #piles[cond] = np.nanmean(stack, axis=2)

~/miniconda3/envs/insulation-model-NEW/lib/python3.6/site-packages/cooltools/snipping.py in pileup(features, data_select, data_snip, map)
    196     cumul_stack, orig_rank = zip(*map(
    197         partial(_pileup, data_select, data_snip),
--> 198         features.groupby('region', sort=False)
    199     ))
    200 

~/miniconda3/envs/insulation-model-NEW/lib/python3.6/site-packages/cooltools/snipping.py in _pileup(data_select, data_snip, arg)
    160                      zip(s1, e1, s2, e2)))
    161 
--> 162     return np.dstack(stack), feature_group['_rank'].values
    163 
    164 

~/miniconda3/envs/insulation-model-NEW/lib/python3.6/site-packages/numpy/lib/shape_base.py in dstack(tup)
    697     """
    698     _warn_for_nonsequence(tup)
--> 699     return _nx.concatenate([atleast_3d(_m) for _m in tup], 2)
    700 
    701 

ValueError: all the input array dimensions except for the concatenation axis must match exactly

I've also seen a variation on the value error: along dimension 0, the array at index 0 has size 27 and the array at index 1 has size 26

**Comment by sabrsyed** [comment]
Here's what I've run so far and outputs

snippet_flank = 200000

windows1 = snipping.make_bin_aligned_windows(
    binsize, 
    sites['chrom1'], 
    sites['mid1'],
    flank_bp=snippet_flank)
windows1['strand'] = '.'

windows2 = snipping.make_bin_aligned_windows(
    binsize, 
    sites['chrom2'], 
    sites['mid2'],
    flank_bp=snippet_flank)
windows2['strand'] = '.'

windows = pd.merge(windows1, windows2, left_index=True, right_index=True, suffixes=('1', '2'))
windows = snipping.assign_regions(windows, supports)
windows = windows.dropna()
windows.head()



chrom1 | start1 | end1 | lo1 | hi1 | strand1 | chrom2 | start2 | end2 | lo2 | hi2 | strand2 | region
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
chr1 | 156700000 | 157120000 | 7835 | 7856 | . | chr1 | 156860000 | 157280000 | 7843 | 7864 | . | chr1:0-195471971
chr1 | 178320000 | 178740000 | 8916 | 8937 | . | chr1 | 178760000 | 179180000 | 8938 | 8959 | . | chr1:0-195471971
chr1 | 178320000 | 178740000 | 8916 | 8937 | . | chr1 | 179260000 | 179680000 | 8963 | 8984 | . | chr1:0-195471971
chr1 | 178320000 | 178740000 | 8916 | 8937 | . | chr1 | 178940000 | 179360000 | 8947 | 8968 | . | chr1:0-195471971
chr1 | 149640000 | 150060000 | 7482 | 7503 | . | chr1 | 150040000 | 150460000 | 7502 | 7523 | . | chr1:0-195471971

stacks = {}
piles = {}
for cond in conditions:
    expected = cis_exp[cond]
    print(expected.head())
    snipper = snipping.ObsExpSnipper(clrs20kb[cond], expected)
    stack = snipping.pileup(windows, snipper.select, snipper.snip)
    #stacks[cond] = stack
    #piles[cond] = np.nanmean(stack, axis=2)

chrom  diag  n_valid  balanced.sum  balanced.avg
0  chr1     0    11799           NaN           NaN
1  chr1     1    11605           NaN           NaN
2  chr1     2    11592    360.418559      0.031092
3  chr1     3    11588    236.874955      0.020441
4  chr1     4    11582    178.353606      0.015399

**Comment by golobor** [comment]
@sabrsyed , sorry for not answering this in time! The code for pileups has changed a lot and is much easier to use (also, we have a good tutorial now!). I am closing this issue for now, but please feel to reopen or to reach out in the future!
