### ISSUE TITLE
question regarding the interpretation of call-compartments

### ISSUE THREAD

**Issue by oriolfornes** [open2c/cooltools#116]
Hi,

I have a question regarding the interpretation of `call-compartments`.

Let's say I want to call compartments for `A.cool`, `B.cool`, `C.cool`, ..., and `N.cool`, where each `A`, `B`, `C`, ..., `N` refer to different experimental conditions such as cell type, restriction enzyme, etc.

I call `call-compartments` as follows: `cooltools call-compartments -o compartments.$LABEL $LABEL.cool`. This creates the following two files: `compartments.$LABEL.cis.lam.txt` and `compartments.$LABEL.cis.vecs.tsv`.

The content of a given `compartments.$LABEL.cis.vecs.tsv` file looks as follows:
```
chrom	start	end	E1	E2	E3
chr1	0	100000	-0.3604436930426914	0.7554852994754232	-0.507474373780304
chr1	100000	200000			
chr1	200000	300000			
chr1	300000	400000			
chr1	400000	500000			
chr1	500000	600000	-0.4313521315219643	0.22247503970129562	-0.649543984014918
chr1	600000	700000			
chr1	700000	800000	-0.3485413537229596	-0.418055366976313	-0.636332590218608
chr1	800000	900000	-0.5188014009934732	-0.03347418490264274	-0.7522066209353574
chr1	900000	1000000	-0.7537143867541539	-0.3477349621268979	-0.42414879971967046
chr1	1000000	1100000	-0.6258982435799673	-0.14005266670178548	-0.18278219831572107
...
```

From the [literature](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-015-0741-y), I understand that "boundary changes between the two compartments occur where the entries of the first eigenvector change sign", and that "the sign of the eigenvector is arbitrary". Therefore, I was wondering if there is a "simple" way to identify which compartment is active (A) or inactive (B) from the eigenvector signs? For instance, in the previous paper, they "correlate the resulting eigenvector with the eigenvector from [Lieberman-Aiden et al.](https://science.sciencemag.org/content/326/5950/289), changing sign if necessary to ensure a positive correlation" (in the Lieberman-Aiden paper, they ensured that negative values are associated with the closed compartment).

Thank you in advance!

**Comment by oriolfornes** [comment]
Nevermind, I should have RTFM more carefully: `--reference-track`.

**Comment by oriolfornes** [comment]
Nevermind, I should have RTFM more carefully: `--reference-track`.

**Comment by nvictus** [comment]
This is exactly what the [phasing/reference track](https://github.com/mirnylab/cooltools/blob/master/cooltools/cli/call_compartments.py#L19) is for. If a phasing track is provided, cooltools will "flip" (i.e. change sign of) the eigenvectors to achieve a positive correlation with the phasing track. The simplest phasing track to use is GC content, which works for most vertebrate genomes. You can also use gene density or anything other signal that preferentially marks the "active" part of the genome. 

The `cooltools genome` command group can generate GC or gene coverage tracks.
