### ISSUE TITLE
extending CLI expected and expected.py module

### ISSUE THREAD

**Issue by sergpolly** [open2c/cooltools#120]
There are several things to be addressed:

1. `blocksum_pairwise` - would require new parameters , e.g. `weight_name` to allow different balacning names https://github.com/mirnylab/cooltools/blob/cb77cf219aa38286f418b0a15eb44128de295d4e/cooltools/expected.py#L771
2. allow `blocksum_pairwise` to divide sums by the `n_total` - without subtracting `n_bad` - maybe usefull for non-balanced data (low resolution, SV analysis stuff)
3. `diagsum` effectively divides by `n_total` , in case when `transforms={}` provided - i.e. when trying to calculated expected on the raw data
4. is it a good idea to be able to apply `blocksum_pairwise` to inter-arm regions? they are almost "flat"... ?
5. of course we'd need to introduce `--range` (and potentially `--range2`) to calculate intra-armal expected (which might be useful for dot calling btw)
6. turn `expected` into scaling plots/distance decay calculated from `cooler` (i.e. binned data)
7. what am I missing ?

**Comment by sergpolly** [comment]
basically a subset of https://github.com/mirnylab/cooltools/issues/37

**Comment by Phlya** [comment]
@sergpolly can you check if this can be closed? You addressed some things in the PR, and I _think_ the rest is covered in #37?

**Comment by sergpolly** [comment]
sure ! yeah ! mostly addressed now
