### ISSUE TITLE
assign_supports doesn't support UCSC strings and deviates from "matrix.fetch" in some edge-cases

### ISSUE THREAD

**Issue by sergpolly** [open2c/cooltools#128]
Some ignoranuses like myself were trying to stick a simple list of chromosomes `["chr1","chr2","chr3",...]` into `assign
_supports` instead of proper support regions (a 3-tuple as I understand now)

I was actually sticking `["chr1","chr2","chr3",...]` into `expected.blocksum()` but it was `assign_supports` that was failing: https://github.com/mirnylab/cooltools/blob/9c8028f756865f8315096419b3d32bc7d6560bed/cooltools/lib/common.py#L5

https://github.com/mirnylab/cooltools/blob/9c8028f756865f8315096419b3d32bc7d6560bed/cooltools/lib/common.py#L32
there are checks for `len(region)==3` - aka proper support region, and `len(region)==2` - implies a pair of proper support regions - there should be `else`-branch `raising` some `ValueError` or something like that - also inside of `len(region)==2` - there should be a check to prevent `("chr1","chr2")` from failing mysteriously

this is related to #120  and I could try to fix this in https://github.com/mirnylab/cooltools/pull/127

**Comment by Phlya** [comment]
Why not support string regions, actually? Anything parse-able by `cooler.util.parse_region_string` could be made to work...

Checking by length for that is a bad idea, by the way, since chromosome names in some organisms might be 3 characters (or easily 2 characters for naming without "chr").

**Comment by sergpolly** [comment]
yeah, there has to be a check `isinstance(region,str)`  at least - otherwise not sure why it couldn't be made `str`-based

**Comment by sergpolly** [comment]
apparently - there are more issues with `assign_supports` - all the details are here https://github.com/mirnylab/cooltools/pull/127

**Comment by sergpolly** [comment]
related to https://github.com/mirnylab/cooltools/issues/37

**Comment by sergpolly** [comment]
according to @nvictus the following should fix `assign_support` in a general case ...
![Screenshot from 2019-12-28 23-45-36](https://user-images.githubusercontent.com/6790270/71552496-4b343000-29cc-11ea-912f-15169ec31c92.png)

idea is to make `assign_support` select pixels following the same rules/logic (half-open intervals) as `clr.matrix().fetch()`

**Comment by golobor** [comment]
assuming that it is resolved with the next snipping code - @sergpolly , please, feel free to reopen!
