### ISSUE TITLE
for future references: this might lead to unexpected behavior in trans expected calculations

### ISSUE THREAD

**Issue by sergpolly** [open2c/cooltools#142]
https://github.com/mirnylab/cooltools/blob/98332348e7dd89d9cd5f9723c5a216a341092655/cooltools/expected.py#L727

seems like a minor non-issue for now , but eventually might lead to additional frustration - if we have several `weight` columns in the `bins` table, then, once you annotate the `pixels` and do `.dropna()` then we are dropping *ALL* rows with any `NaNs` - which might be not what we want ...

**Comment by sergpolly** [comment]
or ... perhaps `fields` argument should take care of that ... - i.e. if you are trying you're expected based on `weight_1`  - do not pass `weight_2` there .

But right now `fileds` does nothing in the `_block_asymm_sum`  - so this issue still holds and should stay here

it is an edge case and should not affect typical use of trans-expected ...

**Comment by sergpolly** [comment]
sorry , no `fields` is basically a list of columns to be summed - never intended to solve an issue of multiple `weight` columns

**Comment by sergpolly** [comment]
sorry , no `fields` is basically a list of columns to be summed - never intended to solve an issue of multiple `weight` columns

**Comment by golobor** [comment]
@sergpolly , we need your input here too - still an issue?

**Comment by sergpolly** [comment]
will check it myself
latest version might be fool-proof actually

**Comment by sergpolly** [comment]
checked - latest version should be fool-proof, because we do:
```python
pixels.dropna(subset=["r1","r2"])
```
so other columns in the `pixels` table should not affect our `dropna`
