### ISSUE TITLE
eigendecomp bedslice error

### ISSUE THREAD

**Issue by dlafont15** [open2c/cooltools#151]
Hi. I'm getting an error when running the cooltools eigendecomp (see screenshot).  Others in the lab have this working without specifying additional arguments... I was initially using version 0.0.9 of bioframe but i get the same error after I had updated to version 0.0.10. Any ideas?
![Untitled-1-01 (1)](https://user-images.githubusercontent.com/50594175/80010470-77eae680-8498-11ea-8227-476333f42909.jpg)

**Comment by mimakaev** [comment]
Hi. We're in a process of refactoring some functions in cooltools/bioframe, and cooltools/bioframe are somewhat out of sync right now. I believe the master branch of bioframe on github would have this error fixed.

**Comment by dlafont15** [comment]
Thanks for the suggestion but that didn't work. I was running cooltools v0.4.0.dev0. Running either v0.3.1 or v0.3.0 instead fixed the error
