### ISSUE TITLE
calculate_insulation_score throws KeyError

### ISSUE THREAD

**Issue by dmalzl** [open2c/cooltools#158]
Hi,

I am trying to compute the insulation score around my compartment boundaries using `cooltools` v0.3.2 and found two issues in your code.

1. Example code is not up to date
In order to do so I was looking at the code for the examples in the documentation and found that importing the function `find_insulation_boundaries` throws an import error due to the function simply not being defined in the `cooltools.insulation` module.

2. `calculate_insulation_score` tries to get a column from the cooler frame which is not defined
When searching for a replacement I found the `calculate_insulation_score` function to be a decent workaround. However, when trying to use it, it throws
```
KeyError: 'ignore_diags'
```

This is due to a line of code where the function tries to get an `'ignore_diags'` column from the cooler frame which is not defined in my coolers (or any other coolers I have examined until now). 
```
156     ignore_diags = (ignore_diags
157                     if ignore_diags is not None
158                     else clr._load_attrs(clr.root.rstrip('/')+'/bins/weight')['ignore_diags'])
```

Is this the way it was intended or is this simply a typo or something?

**Comment by dmalzl** [comment]
Okay, I see this column is only valid when balancing with IC. However, the `find_insulation_boundaries` is actually named `_find_insulation_boundaries_dense`.

**Comment by gfudenberg** [comment]
yes, these function names appear to be out of sync with the ipynbs... 

I'm finding a different error for calculate_insulation_score in cooltools 0.3.2-- if window_bp is int64, the step to convert window_bp to a list doesn't happen, & the function throws an error in the enumerate step.

**Comment by golobor** [comment]
@dmalzl , see the new ipynb examples here : https://github.com/open2c/open2c_examples
Feel free to reopen this issue or open new ones!
