### ISSUE TITLE
What does "DB" argument mean in cooltools genome genecov?

### ISSUE THREAD

**Issue by pkubgmlixs** [open2c/cooltools#164]
Hello everyone,

I want to use _cooltools genome genecov_ to generate gene density track, however, I don't understand the required format of  gene annotation file. To my understanding, the "DB" argument described in CLI reference is something like gene annotation in gff or gpe format. Could anyone have any idea about this command? 
Thank you in advance.

Kevin

**Comment by golobor** [comment]
Hi Kevin,
thank you for this bugreport!
Indeed, this looks very confusing. Confusingly, DB is the name of the UCSC genome assembly; gene locations are automatically downloaded from UCSC goldenPath. I updated the docstrings to reflect this.
Thanks again!
Anton.
