### ISSUE TITLE
Error in ObsExpSnipper?

### ISSUE THREAD

**Issue by Mittmich** [open2c/cooltools#168]
We started migrating our [labinternal wrappers](https://github.com/gerlichlab/ngs) for cooltools to a new version of cooltools (0.2.0 to 0.3.2) and noticed that our pileups are not working anymore. I get a `ValueError` in `ObsExpSnipper` when the individual groups are accessed:https://github.com/mirnylab/cooltools/blob/d9f43d3120d72e242c00f029c655887cc9f30681/cooltools/snipping.py#L359

A notebook to reproduce the error with our testdata is available [here](https://github.com/gerlichlab/ngs/blob/new_cooltools/Cooltools_error.ipynb). The same code with an older version that worked can be found [here](https://github.com/gerlichlab/ngs/blob/new_cooltools/Cooltools_old_error.ipynb).

The commit that changed the behavior is this one: https://github.com/mirnylab/cooltools/commit/86f2636c25f0351d7056d3f19bbe629d6c913017#diff-2c39b1e7b7e8511cda2d9ee8ddcc0335

Is this expected behavior and I need to change the way I feed the data, or is this a bug?

**Comment by mimakaev** [comment]
I remember seeing this code, and I even remember fixing this bug, but I probably forgot to commit it because I can't find my fix. It was something easy. So this is definitely a bug. I'll see if I can recall the solution.

**Comment by mimakaev** [comment]
Submitted a PR that I believe corrects this issue. Not sure how and why this happened in the first place... but I should wait from users of this code to report perhaps. Maybe someone is using regions as a tuple as a first column of expected dataframe? https://github.com/mirnylab/cooltools/pull/171

**Comment by Mittmich** [comment]
Thanks a lot! I was also thinking that this might be a possibility, but the `region` and `region2` arguments that are passed to `.snipping` come from `bioframe.parse_region_string`, which is always a tuple of `(chrom, start, end)`, so the above code will always select `chrom` because `len(self.regions_columns)` is always `> 0`. This might work if `self.regions_columns` are a single chromosome name, but I think it will fail in all other cases.

**Comment by valtona** [comment]
Hello,
When using snipping for dot pileups I am now having this error:

```
KeyError                                  Traceback (most recent call last)
<ipython-input-33-b559c633342e> in <module>
      4     expected = pd.read_table(f'/data/.../expected/{long_names[cond]}.{binsize//1000}kb.expected.cis.tsv')
      5     snipper = snipping.ObsExpSnipper(clrs[cond], expected)
----> 6     stack = snipping.pileup(windows, snipper.select, snipper.snip)
      7     stacks[cond] = stack
      8     piles[cond] = np.nanmean(stack, axis=2)
~/miniconda3/envs/cooler-env/lib/python3.7/site-packages/cooltools/snipping.py in pileup(features, data_select, data_snip, map)
    197         *map(
    198             partial(_pileup, data_select, data_snip),
--> 199             features.groupby("region", sort=False),
    200         )
    201     )
~/miniconda3/envs/cooler-env/lib/python3.7/site-packages/cooltools/snipping.py in _pileup(data_select, data_snip, arg)
    156         e2 = feature_group["end2"].values
    157 
--> 158     data = data_select(region1, region2)
    159     stack = list(map(partial(data_snip, data, region1, region2), zip(s1, e1, s2, e2)))
    160 
~/miniconda3/envs/cooler-env/lib/python3.7/site-packages/cooltools/snipping.py in select(self, region1, region2)
    357         gr = self.expected.groupby(self.regions_columns)
    358         self._expected = LazyToeplitz(            
--> 359             gr.get_group(region1)[
    360                 "balanced.avg"
    361             ]
~/miniconda3/envs/cooler-env/lib/python3.7/site-packages/pandas/core/groupby/groupby.py in get_group(self, name, obj)
    646         inds = self._get_index(name)
    647         if not len(inds):
--> 648             raise KeyError(name)
    649 
    650         return obj._take(inds, axis=self.axis)
KeyError: ('chr10', 0, 135534747)
```


I was using the pileup jupyter notebook from the cooltools documentation and running this:
```
stacks = {}
piles = {}
for cond in conditions:
    expected = pd.read_table(f'/data/.../expected/{long_names[cond]}.{binsize//1000}kb.expected.cis.tsv')
    snipper = snipping.ObsExpSnipper(clrs[cond], expected)
    stack = snipping.pileup(windows, snipper.select, snipper.snip)
    stacks[cond] = stack
    piles[cond] = np.nanmean(stack, axis=2)
```

With
```
snippet_flank = 250000

from cooltools.expected import diagsum, blocksum_pairwise
supports = [(chrom, 0, chromsizes[chrom]) for chrom in chromosomes]

windows1 = snipping.make_bin_aligned_windows(
    binsize, 
    sites['chrom1'], 
    sites['mid1'],
    flank_bp=snippet_flank)

windows2 = snipping.make_bin_aligned_windows(
    binsize, 
    sites['chrom2'], 
    sites['mid2'],
    flank_bp=snippet_flank)

windows = pd.merge(windows1, windows2, left_index=True, right_index=True, suffixes=('1', '2'))
windows = snipping.assign_regions(windows, supports)
windows = windows.dropna()
windows.head()
```

It was working before the update, so I am wondering if  I am doing something wrong or is there something that should be modified?
Thanks

**Comment by Phlya** [comment]
Yeah reported here, same problem I think https://github.com/mirnylab/cooltools/issues/177

**Comment by Phlya** [comment]
This should all be finally fixed in the current pre-release (which will be released imminently), yay!

**Comment by Mittmich** [comment]
Already saw it, thanks! 👍
