### ISSUE TITLE
KeyError in ObsExpSnipper for input expected tsv

### ISSUE THREAD

**Issue by zhaoweiyu-github** [open2c/cooltools#177]
Hi, although you fixed bugs reported for calculated expected dataframe (have chrom,start,end columns) [Error in ObsExpSnipper](https://github.com/mirnylab/cooltools/issues/168) but the new version would report KeyError for input expected tsv generated by cooltools compute-expected (only have chrom column but not start,end column).

**Comment by Phlya** [comment]
Yeah, it's the same in ExpectedSnipper. Example:

https://gist.github.com/Phlya/0cd17b6d4f9a1245bef8d5991fce7b77

**Comment by Phlya** [comment]
So I'm not sure what format of region would even work at all for expected files with just "chrom" (old style) or just "region" (future style) column.

**Comment by Phlya** [comment]
This should all be finally fixed in the current pre-release (which will be released imminently), yay!
