### ISSUE TITLE
import error in compute_expected.py

### ISSUE THREAD

**Issue by KaSaBe** [open2c/cooltools#183]
Just installed the newest version of cooltools from git repo, and upon running the cooltools CLI it throws an import error:

```
compute_expected.py", line 5, in <module>
from bioframe import parse_regions
ImportError: cannot import name 'parse_regions' from 'bioframe' 
```

The import should be:

`from bioframe import parse_region`

With that fixed the CLI works fine.

**Comment by sergpolly** [comment]
Hi @KaSaBe this is totally my fault ... We are trying to introduce some major changes in the `cooltools/bioframe` ecosystem and I updated `cooltools` a bit prematurely (it should ave been a pull request instead) .

The `biofrmae.parse_regions` with `s` at the end does exist and it is an intended use of that function - problem is,  it is not in a `master` branch of `bioframe`, instead it is in `develop` - you can install `develop` branch of bioframe like this:
`pip install git+https://github.com/open2c/bioframe.git@develop` or `pip install git+https://github.com/open2c/bioframe.git@develop#egg=bioframe` if the previous fails .

We apologize for the inconvenience! and just as a heads up - there might be some of that in recent weeks - please report issues that you're experiencing - this would be super helpful for our transition. Thank you !

**Comment by sergpolly** [comment]
We are in sync now with the latest `bioframe` and this shouldn't be an issue anymore - please reopen otherwise

**Comment by shappiron** [comment]
The problem remained for me. I installed cooltools with conda install. The error was the following when I tried to call `cooler_cis_eig`
```
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_22832/2649296964.py in <module>
     10         bad_bins=mask_indices,
     11         ignore_diags=2,
---> 12         sort_metric='var_explained')
     13 
     14     # Save text files

~/miniconda3/envs/mice/lib/python3.7/site-packages/cooltools/eigdecomp.py in cooler_cis_eig(clr, bins, regions, n_eigs, phasing_track_col, balance, ignore_diags, bad_bins, clip_percentile, sort_metric, map)
    370 
    371     # regions to dataframe
--> 372     regions = bioframe.parse_regions(regions, clr.chromsizes)
    373 
    374     # ignore diags as in cooler inless specified

AttributeError: module 'bioframe' has no attribute 'parse_regions'
```

**Comment by Phlya** [comment]
@shappiron it doesn't look like you have the latest version of cooltools, could you try updating? There is no `cooler_cis_eig` function anymore, it's called `eigs_cis`.

**Comment by shappiron** [comment]
Indeed, I installed an old version from conda, sorry for a disturbance.
