### ISSUE TITLE
BED nad BEDGraph formats adherence ?

### ISSUE THREAD

**Issue by sergpolly** [open2c/cooltools#187]
should we adhere to BED/BEDgraph "formats" throughout CLI API ? - i.e. tab separated, header-less, chrom, start,end, (name and more for BED) and signal or signalS for BEDGraph ...

right now `call-compartments` yields a tsv file with a header, and that's how we interpret it in `compute-saddle` - i.e. `chrom start end` are hardcoded in `compute-saddle` ....

eventually we should probably have a unified BED/BedGrpah interface in bioframe for that i guess (with validations and other stuff) ... Don't we have it something like that already?

**Comment by nvictus** [comment]
Maybe a convention that .bed and .bedGraph are headerless (columns are standard), while with an arbitrary .tsv one should expect a header?

**Comment by golobor** [comment]
(1) do bed/bedgraph absolutely have to be headerless? it'd be a pity,
because headers are extremely useful for knowing what's inside the file.
(2) bedgraph is a shitty format to follow :(

**Comment by nvictus** [comment]
(1) yeah, I think they are.. except that they can optionally have UCSC browser and track definition lines instead of a header: https://genome.ucsc.edu/FAQ/FAQformat.html#format1

**Comment by golobor** [comment]
can I expand on point (2) then?.. 
To me, these formats, as defined by the ucsc, just look very bad. 
- they do not offer any place to store metadata;
- the standard header lines make bed/bedgraph not compatible with the .csv standard. One can argue that #-comments are not a part of the official csv standard, but, de facto, many (most?) csv parsers expect them.
- the header lines as defined by the ucsc standards are too inflexible and application-specific to be useful. 

So, my question is - what's the point of following these standards? (i very well may be missing something here)

**Comment by sergpolly** [comment]
I don't have a strong opinion on whether to follow strict definitions of BED/BEDGraph  - but it would be goo to agree on some more or less unified interface and approach throughout cooltools/bioframe

we've got this in bioframe https://github.com/open2c/bioframe/blob/22675199efd1ee80304ed31a108505d84341d5ab/bioframe/io/formats.py#L42

should we start using that throughout our CLI ?
there are also these helper functions - e.g. `sniff_for_header` https://github.com/open2c/cooltools/blob/5d641c449a5192282e9fadf8d848e7b0a6c869f9/cooltools/cli/util.py

Could we allow `bioframe.read_table` to do some header sniffing activity - in order not to punish people unnecessarily for leaving headers in slightly unconventional BED/BEDGraph ?

**Comment by sergpolly** [comment]
header/comments sniffing activity is important imho, - sorry could not resist an illustration
![sniffing](https://user-images.githubusercontent.com/6790270/94960438-e492f400-04c0-11eb-9535-8ac0f838e449.jpeg)

**Comment by sergpolly** [comment]
there are some schemas in bioframe and we started adding cooltools-specific schemas, so closing this for now
