### ISSUE TITLE
Question about compute-expected function for trans-interactions

### ISSUE THREAD

**Issue by QianzhaoJ** [open2c/cooltools#195]
Hi
   I found that  `compute-expected`  function can calculate the expected Hi-C signal for trans-interactions, but I am confused about the `trans-expected`. How is `trans-expected` calculated? Maybe, for the trans-interactions in chr4-chr6, the expected means the average of observed interactions in chr4-chr6?  Could you explain a little more?
   Thanks in advance!

Best,
Qianzhao

**Comment by sergpolly** [comment]
@QianzhaoJ you are exactly right ! Trans- (i.e. inter-chromosomal) interactions are interactions between different chromosomes, which are not connected into a single "polymer" chain. Thus - trans-interactions lack the most prominent feature of cis-interactions - "distance decay" (higher frequency of interactions of loci that are close along the chromosome).

So, for trans-interactions `compute-expected` aggregates and averages interactions over inter-chromosomal "blocks" - e.g. average level of interactions in a "rectangle" representing interactions between chr1 and chr2 .

In humans, different pairs of chromosomes have different level of average interactions - e.g. small chromosomes chr15-chr22 tend to interact stronger which each other that with others . So, when you are trying to study compartmentalization in trans - it is important to normalize trans-interactions by such an expected. Trans -data is further complicated by the preferential telomeric/centromeric interactions (in humans at least) - but this is next level of detail and is not addressed by the described trans-expected.
Hope this provides more technical details and some context .

**Comment by sergpolly** [comment]
closing for now - feel free to reopen for further discussion
