### ISSUE TITLE
logbin_expected: filtering by min_nvalid can leave an empty dataframe

### ISSUE THREAD

**Issue by golobor** [open2c/cooltools#200]
As reported by Sergey Nowoshilov, filtering by min_nvalid in logbin_expected can produce an empty dataframe, leading to exceptions downstream. Not sure what's the best solution here... @mimakaev , any thoughts?..

https://github.com/open2c/cooltools/blob/6781f41d5ebfce6a8567db2daadef4ff8cc9b854/cooltools/expected.py#L1100

**Comment by gfudenberg** [comment]
should this just throw an error if no diagonals remain?

**Comment by gfudenberg** [comment]
should this be closed if we're now using new smoothing? @golobor

**Comment by golobor** [comment]
yes, i think so!
