### ISSUE TITLE
logbin_expected: exp_summary_name confusion

### ISSUE THREAD

**Issue by gspracklin** [open2c/cooltools#201]
what is exp_summary_name? 

expected.py L1059 requires 'count.sum' but logbin_expected.py doesn't import/read this column by default, perhaps it should?

https://github.com/open2c/cooltools/blob/19bf4c169826e4bf1336229c71cfb8a0947c924e/cooltools/cli/logbin_expected.py#L130

I get an error unless I use 'cooltools logbin-expected expected.tsv::count.sum output'. Is this by design?

**Comment by Phlya** [comment]
What error do you get? I think Sergey added that part, but it defaults to `balanced.sum`. Are your data not balanced?
https://github.com/open2c/cooltools/blob/19bf4c169826e4bf1336229c71cfb8a0947c924e/cooltools/cli/logbin_expected.py#L15

**Comment by sergpolly** [comment]
Doubling down on what @Phlya said - `logbin_expected` is "logbinning" already aggregated expected - i.e. "something.sum".
By default it awaits balanced data - hence "balanced.sum" is the default column ...
"count.sum" - is also a legit option - it is raw counts aggregated by diagonals .

Note that "n_valid" is needed always - as it the normalization factor, that is used to divide "something.sum" by (one way or another)

**Comment by gspracklin** [comment]
hmm...weird - I still get the output files even with the warning message

input columns in expected.tsv: 'region  diag    n_valid count.sum       balanced.sum    count.avg       balanced.avg'

cmd: 'cooltools logbin-expected expected.tsv::balanced.sum output'

Error message:
INFO:numexpr.utils:Note: NumExpr detected 36 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
/home/spracklin/devel/cooltools/cooltools/expected.py:1107: RuntimeWarning: count.sum not found in the input expected
  warnings.warn(RuntimeWarning(f"{raw_summary_name} not found in the input expected"))

**Comment by sergpolly** [comment]
@gspracklin  what is your version of Python btw ?

**Comment by sergpolly** [comment]
oh nevermind - scrape Python version. I figured it out  - my bad ...

**Comment by sergpolly** [comment]
@mimakaev logbin_expected can use raw counts - `count.sum` for some additional filtering - even when you're aggregating balanced data (`balanced.sum`) - that's in his API .

In the CLI - I introduced some validation for the input expected - checks for certain columns being present etc - and along with that check I limited the number of columns being read - so I skipped `count.sum` when you try to aggregate `balanced.sum` - hence the warning

Output should be mostly fine - that filtering based oin `count.sum` is optional and, I assume, sghouldnt matter in a "typical" scenario

**Comment by sergpolly** [comment]
this is what we could do:
![Screenshot from 2020-11-17 16-33-10](https://user-images.githubusercontent.com/6790270/99453375-d83cec00-28f2-11eb-8479-9d29be934675.png)

or simply remove `min_count` from Python API and CLI
@mimakaev @gspracklin  - approve this message and promise to think about better ways

**Comment by gspracklin** [comment]
tmp solution is to read 'count.sum'. see commit https://github.com/open2c/cooltools/commit/1e61438a28a92e3236ca47e012365a1527341d42
