### ISSUE TITLE
eigdecomp.py and bioframe refactoring

### ISSUE THREAD

**Issue by gspracklin** [open2c/cooltools#205]
@golobor potential areas of conflict with the new bioframe release: 

I don't see slice_bedframe in bioframe (use to be in core.py)
https://github.com/open2c/cooltools/blob/fb0a38c95ec5ebfb0bb04e637dad2335f2b0f200/cooltools/eigdecomp.py#L336

this is now is bioframe.ops.py
https://github.com/open2c/cooltools/blob/fb0a38c95ec5ebfb0bb04e637dad2335f2b0f200/cooltools/eigdecomp.py#L355

**Comment by gfudenberg** [comment]
I believe slice_bedframe was deprecated & should be replaced with
bioframe.select
