### ISSUE TITLE
cooltools diamond-insulation output

### ISSUE THREAD

**Issue by biohubx** [open2c/cooltools#206]
hello,
    I am trying to run `cooltools diamond-insulation`, but there is not any arugment to save the result.

Usage: cooltools diamond-insulation [OPTIONS] IN_PATH WINDOW

  Calculate the diamond insulation scores and call insulating boundaries.

  IN_PATH : The paths to a .cool file with a balanced Hi-C map.

  WINDOW : The window size for the insulation score calculations.
  Multiple space-separated values can be provided.          By default, the
  window size must be provided in units of bp.          When the flag
  --window-pixels is set, the window sizes must          be provided in
  units of pixels instead.

Options:
  --ignore-diags INTEGER         The number of diagonals to ignore. By
                                 default, equals the number of diagonals
                                 ignored during IC balancing.

  --min-frac-valid-pixels FLOAT  The minimal fraction of valid pixels in a
                                 sliding diamond. Used to mask bins during
                                 boundary detection.  [default: 0.66]

  --min-dist-bad-bin INTEGER     The minimal allowed distance to a bad bin.
                                 Used to mask bins during boundary detection.
                                 [default: 0]

  --window-pixels                If set then the window sizes are provided in
                                 units of pixels.

  --append-raw-scores            Append columns with raw scores (sum_counts,
                                 sum_balanced, n_pixels) to the output table.

  --chunksize INTEGER            [default: 20000000]
  --verbose                      Report real-time progress.
  -h, --help                     Show this message and exit.

**Comment by Phlya** [comment]
I think it's fixed in the master version on GitHub, but without upgrading you can redirect the output using `cooltools diamond-insulation ... > output.txt`

**Comment by biohubx** [comment]
thanks.

**Comment by Phlya** [comment]
I'll close this, I assume it helped.
