### ISSUE TITLE
Numba problem with Eigen method

### ISSUE THREAD

**Issue by Max-Highsmith** [open2c/cooltools#208]
Hello,
I am trying to use cooltools to obtain eigen decomp information, however, things are crashing when I call the cis_eig method.  The output is listed below.  I have numba installed but have not used it before

>>> eigdecomp.cis_eig(c.matrix(),3,balance=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: cis_eig() got an unexpected keyword argument 'balance'
>>> eigdecomp.cis_eig(c.matrix(balance=False),3,)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/heracles/miniconda3/envs/melanoma_fresh/lib/python3.6/site-packages/cooltools/eigdecomp.py", line 127, in cis_eig
    OE, _, _, _ = numutils.observed_over_expected(A, mask)
  File "/home/heracles/miniconda3/envs/melanoma_fresh/lib/python3.6/site-packages/numba/core/dispatcher.py", line 414, in _compile_for_args
    
  File "/home/heracles/miniconda3/envs/melanoma_fresh/lib/python3.6/site-packages/numba/core/dispatcher.py", line 357, in error_rewrite
    else:
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function iadd>) found for signature:
 
 >>> iadd(Literal[int](0), array(float64, 1d, C))
 
There are 16 candidate implementations:
    - Of which 14 did not match due to:
    Overload of function 'iadd': File: <numerous>: Line N/A.
      With argument(s): '(int64, array(float64, 1d, C))':
     No match.
    - Of which 2 did not match due to:
    Operator Overload in function 'iadd': File: unknown: Line unknown.
      With argument(s): '(int64, array(float64, 1d, C))':
     No match for registered cases:
      * (int64, int64) -> int64
      * (int64, uint64) -> int64
      * (uint64, int64) -> int64
      * (uint64, uint64) -> uint64
      * (float32, float32) -> float32
      * (float64, float64) -> float64
      * (complex64, complex64) -> complex64
      * (complex128, complex128) -> complex128

During: typing of intrinsic-call at /home/heracles/miniconda3/envs/melanoma_fresh/lib/python3.6/site-packages/cooltools/lib/numutils.py (610)

File "../../../../../../miniconda3/envs/melanoma_fresh/lib/python3.6/site-packages/cooltools/lib/numutils.py", line 610:
def observed_over_expected(
    <source elided>
                if not has_mask or mask2d[offset + j, j]:
                    sum_pixels += data[offset + j, j]
                    ^

>>>

**Comment by nvictus** [comment]
I think numba is just being picky about types. The unbalanced matrix is integer. Try casting to float:

```python
eigdecomp.cis_eig(c.matrix(balance=False).astype(float), 3)
```

**Comment by gfudenberg** [comment]
closing this, but feel free to reopen if this did not resolve
