### ISSUE TITLE
find_boundaries index

### ISSUE THREAD

**Issue by gspracklin** [open2c/cooltools#210]
looks like find_boundaries returns a dataframe with each chrom having an index starting at 0. Should we reset_index at the end to maintain the original df index order? @golobor 

https://github.com/open2c/cooltools/blob/51b95c3bed8d00a5f1f91370fc5192d9a7face7c/cooltools/insulation.py#L284

**Comment by gfudenberg** [comment]
double checking this is closed cc @Phlya @agalitsyna

**Comment by agalitsyna** [comment]
Resolved in https://github.com/open2c/cooltools/commit/98b11db82f799f120bc9a25026d92b1683297aba

**Comment by agalitsyna** [comment]
Resolved in https://github.com/open2c/cooltools/commit/98b11db82f799f120bc9a25026d92b1683297aba
