### ISSUE TITLE
Problem with find_boundaries and calculate_insulation_score

### ISSUE THREAD

**Issue by Max-Highsmith** [open2c/cooltools#213]
I am trying to use the insulation module to identify tad boundaries.  However, I am receiving almost entirely all NaN values in the boundary strength column.  How can obtain these TAD boundaries?

`
import numpy as np
import cooler
from cooltools.insulation import calculate_insulation_score, find_boundaries
res      = 100000
win_sz   = 50
cool_string = "Generated/Cool_Files/D0_R1.mcool::/resolutions/100000"
cool_obj = cooler.Cooler(cool_string)
insul_df = calculate_insulation_score(cool_obj, win_sz*res)
bounds   = find_boundaries(insul_df)
print(bounds.columns)
print(bounds['boundary_strength_5000000'])
print(np.sum(np.isnan(bounds['boundary_strength_5000000'])))
print(bounds['boundary_strength_5000000'].shape)
`

> INFO:numexpr.utils:Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
Index(['chrom', 'start', 'end', 'is_bad_bin', 'log2_insulation_score_5000000',
       'n_valid_pixels_5000000', 'boundary_strength_5000000'],
      dtype='object')
0     NaN
0     NaN
1     NaN
2     NaN
3     NaN
       ..
568   NaN
569   NaN
570   NaN
571   NaN
572   NaN
Name: boundary_strength_5000000, Length: 30895, dtype: float64
27928
(30895,)

**Comment by Phlya** [comment]
The ones that are non NaN are the annotated boundaries.

Check this out: https://github.com/open2c/open2c_examples/blob/master/Insulation_and_boundaries.ipynb

And I don't know what organism you are using, but in most cases using 100,000 resolution and 5,000,000 window size are both way too high for any reasonable analysis, I think.

Note that in the example we use micro-C data and very high resolution/small window size, which is not representative of the most typical use cases.

**Comment by gfudenberg** [comment]
I hope this example helped, closing for now but feel free to reopen
