### ISSUE TITLE
Slow expected calculation

### ISSUE THREAD

**Issue by Phlya** [open2c/cooltools#219]
@sergpolly made functions for calculating expected flexible back in summer, which slowed them down a lot. This needs to be fixed to make them great again!

**Comment by sergpolly** [comment]
Anton's proposal:
1. if we want to keep supports overlapping (ultimate flexibility, but exotic case) we can improve complexity of the algorithm by first iterating over pixels and assigning them to different supports . Right now we are going over pairs of regions, assigning supports, pre-calculating sums and then repeating it for a different pair of regions over and over again. `~P*R` complexity  (`P`-# of pixels, `R` - number of 2D regions to handle) ? isn't it `P*R` either way ?
2. if we can guarantee that the regions aren't overlapping - or, better, - there aren't any "support region" clashes - every pixel belong to a different "support" region - than this could be optimized further ... the before-summer performance could be restored

PS
 - I'm afraid scenario 2 is only possible using the `assign_support_2D` that @mimakaev was proposing that same summer
 - scenario 1 is clearly an overkill of "flexibility" - expected for regions overlapping in 2D (sharing pixels) - is exotic, agreed
 - problem was that the "summer" version of `diagsum_asymm` was only capable of processing 2D regions that did not share even a single "side" - i.e. it was "illegal" to put regions like `(chr1p, chr1p), (chr1p, chr1q), ...` as input
 - also, need to explore this branch of `assign_support` further ... https://github.com/open2c/cooltools/blob/53ce4fc11d046e84ca36f3591e9e5d548de9f7b2/cooltools/lib/common.py#L44

**Comment by Phlya** [comment]
How about implementing `assign_supports` using bioframe? Seems like it would be faster without a loop over all supports. And should be relatively easy to turn into `assign_supports_2D` with correct treatment of overlapping regions...

**Comment by Phlya** [comment]
Just wanted to say, we basically implemented the same functionality in snipping using bioframe, maybe it'll help: https://github.com/open2c/cooltools/blob/4c41f419c2e303b01a42238009df2fbfc60303dc/cooltools/snipping.py#L77

**Comment by sergpolly** [comment]
Yes - loop over all `supports/regions/views`is a disaster - it allows regions to be whatever (overlapping, duplicated etc etc) - but it leads to massive slowdowns...

Without some flexible and fast assign_supports/regions_2D that can assign regions non-overlapping in 2D, we'd have to revert back to special cases.

The most efficient special cases, are those which allow annotating several 2D regions using 2-calls for 1D assign_support/region/view:
 - symmetric case (e.g. cis-chromosomes, cis-arms, cis-TAD or compartment domains) defined by a single `viewframe`
 - pairwise asymmetric case (e.g. trans chrom) defined by a single `viewframe`, assign it to `pixels` then groupby in trans-blocks
 - interleaved cis case (e.g. inter-arm on the same chrom) defined by a single `viewframe` - 2D regions are formed between `viewframe[0::2]` and `viewframe[1::2]`, hence interleaved

started doing that.
here are options using an example of `blocksum_pairwise`:

1. using `overlap` surprisingly - slow ...
```python
lo, hi = (0,10_000_000)
bins = clr.bins()[:]
pixels = clr.pixels()[lo:hi]
pixels = cooler.annotate(pixels, bins, replace=False)
pixels["r1"] = bioframe.overlap(
    pixels,
    view,
    how="left", #keep_order=True
    return_input=False,
    return_index=True,
    cols1=["chrom1","start1","end1"]
)["index_"].values
pixels["r2"] = bioframe.overlap(
    pixels,
    view,
    how="left", #keep_order=True
    return_input=False,
    return_index=True,
    cols1=["chrom2","start2","end2"]
)["index_"].values

pixels = pixels.dropna()
pixels.groupby(["r1","r2"])["count"].sum().to_dict()
```

2. using old `assign_support`:
```python
lo, hi = (0,10_000_000)
bins = clr.bins()[:]
pixels = clr.pixels()[lo:hi]
pixels = cooler.annotate(pixels, bins, replace=False)
pixels["r1"] = assign_supports(pixels, view.values, suffix="1")
pixels["r2"] = assign_supports(pixels, view.values, suffix="2")
pixels = pixels.dropna()
pixels.groupby(["r1","r2"])["count"].sum().to_dict()
```

3. skipping `cooler.annotate` using pandas `IntervalIndex` and `pd.cut` - not faster at all !
```python
lo, hi = (0,10_000_000)
pixels = clr.pixels()[lo:hi]
pixels["r1"] = pd.cut(pixels["bin1_id"].values, xxx_interval)
pixels["r2"] = pd.cut(pixels["bin2_id"].values, xxx_interval)
pixels = pixels.dropna()
pixels.groupby(["r1","r2"])["count"].sum().to_dict()
```

4. skipping `cooler.annotate` and going for `searchsorted` in bin-translated regions (`np.digitize`) - blazing fast
```python
lo, hi = (0,10_000_000)
pixels = clr.pixels()[lo:hi]
pixels["r1"] = assign_regions_to_bins_II(pixels["bin1_id"].values,reg_spans)
pixels["r2"] = assign_regions_to_bins_II(pixels["bin2_id"].values,reg_spans)
pixels.groupby(["r1","r2"])["count"].sum().to_dict()
# pixels["r1"] = np.digitize(pixels["bin1_id"].values, bin_bins)
# pixels["r2"] = np.digitize(pixels["bin2_id"].values, bin_bins)
# pixels.groupby(["r1","r2"])["count"].sum().to_dict()
```

**Comment by sergpolly** [comment]
fixed - maybe further developed
