### ISSUE TITLE
A/B compartment analysis bioframe issue

### ISSUE THREAD

**Issue by igoronzy** [open2c/cooltools#229]
Following the tutorial for A/B compartment analysis, I get the error "module bioframe has no attribute slice_bedframe". How can I calculate the eigenvectors/values on my .cool file?

**Comment by nvictus** [comment]
Thanks for your persistence. We've put up a release candidate on PyPI what resolves the bioframe mismatch: https://pypi.org/project/cooltools/

Notes: https://github.com/open2c/cooltools/releases/tag/v0.4.0rc1

Let us know if you run into any other issues.

**Comment by nvictus** [comment]
The proper release should be out in a day or so.

**Comment by nvictus** [comment]
Done: https://pypi.org/project/cooltools/0.4.0/
