### ISSUE TITLE
KeyError when running  snipping.pileup

### ISSUE THREAD

**Issue by wangwl** [open2c/cooltools#230]
Hi there, I recently run into error when using snipping.pileup(). It says "KeyError: 'chr19'". It works well a few weeks ago. Could you help take a look into this? Thanks

**Comment by Phlya** [comment]
Can you provide more details, i.e. versions and code you are using? We did some work on the snipping recently, and would be good to be sure we didn't break anything...

**Comment by Phlya** [comment]
OK, can you please try to upgrade cooltools to the latest version (0.4) and try again?
Also, here is the latest pileup tutorial: https://cooltools.readthedocs.io/en/latest/notebooks/pileup_CTCF.html

**Comment by wangwl** [comment]
Thank you so much for the reply. I now upgraded cooltools to 0.4, and bioframe was automatically upgraded to 0.2. But I run into another error related to bioframe, when doing `windows = snipping.assign_regions(windows, supports)`. The error message is "'list' object has no attribute 'columns'".

**Comment by Phlya** [comment]
Are you `supports` a list? They now should be a dataframe - see how they are created in the new tutorial.

**Comment by wangwl** [comment]
It works now. Thanks so much.
