### ISSUE TITLE
compute-expected and saddle problem

### ISSUE THREAD

**Issue by skytguuu** [open2c/cooltools#242]
Hi,

Thanks for your developed tool "cooltools". There are couple of questions I am confused. 

1. I firstly used HiC-Pro to analyze the raw hic data, then I want to convert the hicpro output file (ice.matrix) to '.cool' file.  Because the ice.matrix is after ICE normalization, so I used 'cooltools call-compartments' to call compartment. But it fails and reported the error "KeyError: "Unable to open object (object 'weight' doesn't exist)"". However, when I used cooler balance firstly then run call-compartments, it works well. My question is, should I used the raw matrix data from hicpro then use cooler to balance, or it is fine to use the normalized ice matrix?

2. Addionally, I want to use 'compute-saddle' to calculate compartment strength (AA+BB)/(AB^2). My command is:
'cooltools compute-saddle file.cool compartment.bed.cis.vecs.tsv file_obs_exp --strength -o dif_comstren'. But it also reported error that : ValueError: Usecols do not match columns, columns expected but not found: ['balanced.avg']. It seems the expected files question, but I don't know what's problem. The file_obs_exp (expected file) is as followed:
![image](https://user-images.githubusercontent.com/25957174/116379907-0f221100-a846-11eb-8978-9fe04b1fb499.png)

Could u give me a hand?
Thanks,
Garen

**Comment by Phlya** [comment]
1. I would use raw matrix from HiC-Pro and balance using cooler.
2. Did you calculate the expected file after you balanced the cooler?

**Comment by skytguuu** [comment]
Hi,

Thanks for your help. I found the problem of failure to run compute-saddle is that " I used the --no balance", and it solved when I used the --balance. However, I have another question abouth the saddle plot.  
1. How can I extract the compartment strength file, because I found it was saved in .npz file. But I am confused about the data (numpy array). If I want to summarize the compartment strength in each chromosome, how could I get the value, it seems there is only value in the .npz?
2. I got the saddle plot figure, but I don't understand the meaning of the top part (green histogram). It is said "cis", is that meaning the total cis counts in each quantile bin?
![image](https://user-images.githubusercontent.com/25957174/116516614-62589a00-a900-11eb-884e-915f3c1066f4.png)

Thanks,
Garen

**Comment by Phlya** [comment]
1. You need to load the .npz file in using `np.load`, it'll create a dict which will include the compartment strength calculations. But I think it is only calculated for all chromosomes combined.
2. Yeah, green bars are a histogram - it's meaningless in this case since you used quantiles, i.e. all bins have the same number of pixels, but it's useful without quantiles.

**Comment by skytguuu** [comment]
Hi,

Thanks for your quickly reply. I am new of python and have some basic question about the npz file. I have used np.load to read the .npz file. If I am understand, the result file (.npz) is  multidimensional array and why it is stored with multidimensional without the replacement of one dimension？I though the number of dimension may be represented the chromosomes, is it right?

Another question is about the saddle plot, I want to set the vmin and vmax, but it failed "ValueError: vmin and vmax values are in original units irrespective of used scale, and therefore should be **positive"，then i used '--scale', but it still failed with the same error.

Many thanks,
Garen

**Comment by Phlya** [comment]
You can generate a saddle for any arbitrary region, e.g. a whole chromosome - using the `--regions` argument. You'll haev to create a separate bed-style file for each whole chromosome.

What are you setting the vmin and vmax to? As the error says, irrespective of the scale they should be positive, for example vmin=0.5 vmax=2 for a symmetrical log scale around 1.

**Comment by skytguuu** [comment]
The command is as followed:
#####################
cooltools compute-saddle merge.cool PC.cis.vecs.tsv obs_exp.file --strength --quantiles --qrange 0.2 0.8 -o test --fig png --scale log --vmin 0.5 --vmax 2
#####################
but the color bar is still from 0.5 to 2.
![image](https://user-images.githubusercontent.com/25957174/117398658-5f2d6180-af31-11eb-8773-77855319da51.png)

**Comment by Phlya** [comment]
That's what you asked for, 0.5 to 2.

**Comment by skytguuu** [comment]
so, you means that the color bar 0.5 to 2 is acturally log2(0.5) to log2(2), right? I can changed the label with -1 and 1?

**Comment by Phlya** [comment]
If you prefer to label that way. It just seems actually more logical to keep the labels in original units, even if the scale is logged.

**Comment by skytguuu** [comment]
Got it. I am appreciated for your help.
Many thanks!

**Comment by baishengjun** [comment]
Hi，
I want to extract the compartment strength in each chromosome, can you provide detailed information about the region file.
The following is my region file, it caused errors.
`chr1    0       249250621`

Thanks a million
Bai
