### ISSUE TITLE
Compartment calling on separate chromosome arms

### ISSUE THREAD

**Issue by yanchunzhang** [open2c/cooltools#243]
Hi, thanks for developing this great tools!

I saw from the Micro-C paper that they called compartment on every single arm of all chromosomes using cooltools, which I think is a more reasonable way to do compartment calling. But I'm not quite clear what the the parameters of _cooler_cis_eig_ want. For example, what are the expected input for the parameters _bins_ and _regions_? 

Could you please provide an example of how to properly set the parameters for calling compartment at a single chromosome arm?

Thanks,
Yanchun

**Comment by luisdiaz1997** [comment]
This used to work  using bioframe. but the new update is giving some errors

assembly = 'hg38'
centromeres = bioframe.fetch_centromeres(assembly)
chromsizes = bioframe.fetch_chromsizes(assembly, as_bed=True)
chromsizes['length'] = chromsizes['end'] - chromsizes['start']
arms_df = bioframe.make_chromarms(chromsizes, centromeres)

I would pass arms_df as regions

**Comment by gfudenberg** [comment]
For the latest version of cooltools installed via github with bioframe 0.3+, the contacts_vs_distance notebook has an example of by-arm view: 
https://cooltools.readthedocs.io/en/latest/notebooks/contacts_vs_distance.html
```
# Use bioframe to fetch the genomic features from the UCSC.
hg38_chromsizes = bioframe.fetch_chromsizes('hg38')
hg38_cens = bioframe.fetch_centromeres('hg38')
hg38_arms = bioframe.core.construction.add_ucsc_name_column(bioframe.make_chromarms(hg38_chromsizes,  hg38_cens))

hg38_arms = hg38_arms[hg38_arms.chrom.isin(clr.chromnames)].reset_index(drop=True)
hg38_arms
```
This can be passed as view_df 

Please re-open if you are still having difficulties
