### ISSUE TITLE
Error when installing cooltools

### ISSUE THREAD

**Issue by rahmas36** [open2c/cooltools#246]
Hi I am trying to install cooltools and the following errors appeared:

Failed building wheel for cooltools
  Running setup.py clean for cooltools
Failed to build cooltools
bioframe 0.2.0 has requirement pandas>=1.0.3, but you'll have pandas 0.24.2 which is incompatible.

Command "/Users/samirrahman/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/83/y481sls56336csx7mh7rlrsc0000gn/T/pip-req-build-lzelbm_d/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/83/y481sls56336csx7mh7rlrsc0000gn/T/pip-record-nsmshp60/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/83/y481sls56336csx7mh7rlrsc0000gn/T/pip-req-build-lzelbm_d/

Will it be corrected if I install the latest version of pandas? Sorry, I have little experience with coding or bioinformatics. Help would be appreciated!

**Comment by gfudenberg** [comment]
Hi, sorry for the slow reply-- there may be conflicts with other packages in your environtment. I'd suggest making a new conda environment with python 3.7+ https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-with-commands, numpy and cython, and then using pip to cooltools.

**Comment by gfudenberg** [comment]
Closing this, but feel free to reopen

**Comment by gfudenberg** [comment]
Hi-- This looks like pip/conda conflicts, and the tricky dependencies between numba and numpy. We resolved something similar the other week & posted the working environment in open2c_examples:
https://github.com/open2c/open2c_examples

**Comment by cgirardot** [comment]
I ll try this thx. By the way, I forgot to mention that I tried to first install from conda without success (I have been waiting for 2 h and it was still searching). Do you manage to install from conda?

**Comment by gfudenberg** [comment]
try installing mamba first, it can greatly speed up conda https://github.com/mamba-org/mamba, then try creating the open2c_examples environment.yml
