### ISSUE TITLE
expected smoothed P(s) curve question

### ISSUE THREAD

**Issue by skytguuu** [open2c/cooltools#249]
Hi,

Thanks for your wanderful tool and I met a problem about the plot smoothed P(s) curve. I want to add the fitted the line with the slope=-1. And it could be as the expected s^(-1) curve, could you give me a hand?

Thanks,
Garen

**Comment by Phlya** [comment]
Does this help?
```python
x = np.logspace(start=1, stop=9, num=2) # Adjust the start and stop to align with your data extremes on the X
y = x**-1 * 1e-3 # Adjust the constant to align nicely with your data
plt.plot(x, y)
```
![image](https://user-images.githubusercontent.com/2895034/123786352-7fdebb80-d8d1-11eb-8605-7ca89aebd8c1.png)

**Comment by skytguuu** [comment]
Hi,

I am appreciated for your help. I am a beginner of python and I have tired many times, but I am still confused about the code.

(1) Under the log-log coordinates, I tried:
x = lb_cvd_agg['s_bp']
y = lb_cvd_agg['balanced.avg']
to fit better, I used the code:
slope, intercept = np.polyfit(x,y,1)
Then I plot with : 
plt.loglog(x,x*-1+intercept)
but the figure showed nothing, then I tried plt.loglog(x,x**-1+intercept), it showed as followed:
![image](https://user-images.githubusercontent.com/25957174/123927316-4edcb480-d9bf-11eb-88d4-a664a9de6974.png)
I don't know what's wrong of my code. I think plt.loglog(x,x*-1+intersect) should be right, but it showed nothing.

(2) Not log-log coordinates
x1 = cvd_agg['s_bp']
y1 = cvd_agg['balanced.avg']
it failed at the beginning of the fit linear regression because of the nan value. In addition, I am not understanded about your formula "y = x**-1 * 1e-3", why it need to multiply by 1e-3?

Many thanks!
Garen

**Comment by Phlya** [comment]
Just plot the exact thing I suggested next to a real curve. Adjust Y location using by changing the 1e-3 constant.

And don't confuse * and ** by the way. a**b is a^b in python, and a*b is just multiplication.

**Comment by skytguuu** [comment]
Thanks, I am now confused that how to calculate the constant to align nicely with your data. Is it right of the way that use "slope, intercept = np.polyfit(x,y,1)"?

**Comment by Phlya** [comment]
Just try by hand, so it looks good on the plot.

If you want to fit the data, easiest is to do a simple linear fit after
log-log transform. But if just want  to show a specific slope, just try it
manually first and see what you like.

**Comment by skytguuu** [comment]
I am tried by hand, and use the code "plt.plot(np.log10(x),np.log10(x**-1*1e-3)+8)", got this figure:
![image](https://user-images.githubusercontent.com/25957174/123962131-b1e04280-d9e3-11eb-9652-61c4ebc1e5e1.png)
In it, I tried manually set the constant equal 8, but I don't know 8 is ok or not. When I set the constant equal 8.5, it looks as followed:
![image](https://user-images.githubusercontent.com/25957174/123962499-1c917e00-d9e4-11eb-8cda-663b067e5b68.png)

I don't know which one is right?

**Comment by Phlya** [comment]
What do you mean, which one is right? Both are right, they show the same slope.

**Comment by skytguuu** [comment]
So, you means the constant is not a defined value, it is subjective according to criteria that the line should be in the range of my data, not need to be calculated by lineage regression?

**Comment by Phlya** [comment]
Well, you could fit a line to your data to overlay as close as possible.
Or if you want to show a specific slope, like what you asked for, just shift the line up or down manually how you like.

**Comment by skytguuu** [comment]
Thanks for your patient explanation, now I understand. 
Many thanks!

**Comment by Phlya** [comment]
Glad I could help.
