### ISSUE TITLE
Questions about "--quantiles" parameter in compute-saddle functions

### ISSUE THREAD

**Issue by QianzhaoJ** [open2c/cooltools#250]
Hello,
  Thanks for developing so helpful tool "cooltools". There are some questions I am confused.
  I tried to calculate saddle statistics and generate saddle plots for ATAC signal track rather than compartment track (eigenvector). 
  When I used "--quantiles" parameter in compute-saddle functions, the code just like `cooltools compute-saddle --contact-type cis --quantiles --qrange 0.01 0.99 --strength --vmin 0.25 --vmax 4 -n 50 --scale log -o $out --fig pdf $cooler ${AB}::signal $exp --min-dist 2000000`, I thought that all bins have the same number of pixels. But after the statistics, I found they are not same.
![image](https://user-images.githubusercontent.com/42069662/123800625-1041ee00-d91c-11eb-9f33-e3a042457e79.png)
  It is so strange because when I used compartment track in compute-saddle with same parameters, all bins have the same number.
![image](https://user-images.githubusercontent.com/42069662/123801027-74fd4880-d91c-11eb-88c0-6f8405c61a01.png)
  How was it happen?  Maybe "--quantiles" parameter made some mistakes? could you give me some suggestions?
  Thanks in advance!

Best wishes
Qianzhao

**Comment by Phlya** [comment]
Could your ATAC signal be discrete perhaps, and then there is a lot of tied values?

**Comment by QianzhaoJ** [comment]
Thanks for your quick reply! I would check my ATAC signal track.

**Comment by gfudenberg** [comment]
Hope this suggestion worked, feel free to re-open if not
