### ISSUE TITLE
streamline cooltools API - assume "regions" are "viewframe", retire parsing

### ISSUE THREAD

**Issue by sergpolly** [open2c/cooltools#254]
proposal to streamline/simplify internal cooltools API: any `regions` argument has to be an instance of `bioframe.viewframe` , so we can retire any regions-parsing that was done internally and replace it with something like that:
```python
try:
    bioframe.is_viewframe(regions, raise_error=True)
except (TypeValue, ValueError) as error:
    print(error)
    raise "regions has to be an instance of bioframe.viewframe"

# or just this:
bioframe.is_viewframe(regions, raise_error=True)

# or this:
if not bioframe.is_viewframe(regions, raise_error=False):
    raise "regions has to be an instance of bioframe.viewframe"

# not sure which is best
```

**Comment by sergpolly** [comment]
from the aug 17 meeting - regarding non-CLI:
 - try to allow some flexibility for the "user"-facing API functions (e..g allow regions=None, or any other format supported by make_viewframe)
 - for more internal/non-public/lower level functions we can stick with requiring (or even make no checks !) strict `is_viewframe` check.

**Comment by sergpolly** [comment]
from aug 17 meeting - regarding CLI:
use following pattern to read/parse through a user provided path to `regions/view`:
```python
if regions is None:
    # use entire chroms
else:
    try:
        regions_df = bioframe.read_table(regions_buf,schema="bed4")
    except  whatever:
        regions_df = bioframe.read_table(regions_buf,schema="bed3")
try:
    regions_df = bioframe.make_viewframe(bioframe.read_table("xxx",schema="bed3"))
except ValueError as e:
    raise RuntimeError("ypu've provided shitty regions file") from e
```

**Comment by agalitsyna** [comment]
Hi, small update in the [recent commit](https://github.com/open2c/cooltools/commit/ef4a1c6f2ed2daf6481d8e7d3b0cb1509c5e7cbb), what's been done: 

- CLIs supporting viewframes: call-compartments, call-dots, compute-expected, compute_saddle
- APIs supporting viewframes: eigdecomp, expected, saddle, snipping
- Corresponding tests updated.

Noticed problems: 

- [ ] asym expected and trans eigdecomp require repeated entries in regions, which is not supported by bioframe.make_viewframe. This actually requires discussion with @sergpolly @gfudenberg 
This currently fails the tests of asym expected and trans compartments/saddles.

- [ ] several places in the code pass tuples to make_viewframe instead of lists, which is not recognized by "from_any" . Can we add this, @gfudenberg ?

**Comment by gfudenberg** [comment]
thanks for the update!

re: trans expected-- I guess we'll need to introduce the concept of a "paired view" for a set of unique pairs of regions... We can either introduce this in bioframe or put a temporary fix in cooltools for now. This might need discussion with other people as well-- any thoughts @nvictus @golobor @Phlya ? 

we can certainly add `from_tuple` to `bioframe.core.construction` and add it to `from_any` !

**Comment by Phlya** [comment]
An alternative is to limit the asym expected and trans eigdecomp to pairwise interactions of regions in a view... For now?

Otherwise yeah, we need to go deeper and define 2D views, or just a temporary fix in some way in cooltools.

**Comment by sergpolly** [comment]
for inner API functions we can gracefully retire support for anything but proper `view_df` using following:

```python
try:
     bioframe.is_viewframe(view_df, ...,raise_errors=True)
except WhatEverError as e:
    # https://docs.python.org/3/library/warnings.html#warnings.warn
    warning.warn("view_df have to be a vieframe in the next version of cooltools", DeprecationWarning, stacklevel=2)
    # try to make viewframe from whatever was provided
    view_df = bioframe.make_viewframe(view_df)

# check if contained regardless of the input type
assert bioframe.is_contained(...,raise_errors=True)

```
