### ISSUE TITLE
add --bigwig option for diamond-insulation CLI

### ISSUE THREAD

**Issue by gabedolpten** [open2c/cooltools#256]
Hi,
Is there a way for the diamond-insulation program to output a bigwig file with bin-wise insulation scores?
Thanks

**Comment by gfudenberg** [comment]
Hi,
There should be a function in bioframe (https://github.com/open2c/bioframe)
that can convert a column into a dataframe to bigwig format, e.g. if your
scores are in insulation_1k['log2_insulation_score_50000']

bioframe.to_bigwig(insulation_1k, hg19_chroms,
                       f'
GM12878_inSitu_MboI.hg19.mapq_30.1000.insul.50000.bw',
                       f'log2_insulation_score_50000')

Hope that helps

**Comment by gabedolpten** [comment]
Awesome, thanks!

**Comment by Phlya** [comment]
Considering we have a --bigwig option for eigenvectors, perhaps we should add it to insulation too? Would just make it easier.
