### ISSUE TITLE
discriminate between user-facing and non-public functions

### ISSUE THREAD

**Issue by sergpolly** [open2c/cooltools#258]
user-facing functions can be imported into the base namespace, e.g.:
```python
from cooltools import *
```
user-facing functions should have the following format:
```python
get_XYZ(
  clr, 
  tracks1=Y1, track2=Y2, .... (input data)
  cutoffs1=Z, cutoffs2=Z2, .... (input parameters)
  nproc=?, chunksize=?, ... (execution specification)
)
```

list of potential user-facing functions by module:

`cooltools.coverage`
- `get_coverage`

`cooltools.directionality` and `cooltools.insulation`. consider refactoring into one module, with different scores. Implement as flexible convolution along the diagonal. @golobor 
- `get_directionality`
- `get_insulation`
- `find_boundaries`

`cooltols.dotfinder` 
- `get_dots` (need to merge pieces together as done in CLI)

`cooltools.eigdecomp` @nvictus @e-navarrete
- `cooler_cis_eig` --> `get_cis_eig`, internal cis_eig should get an underscore
- `cooler_trans_eig` --> `get_trans_eig`, internal should get underscore etc.

`cooler.expected`. refactor diagsum, diagsum_asym (cis-arms), blocksum_asymm (trans)... consider refactoring the CLI for expected into two separate functions. @sergpolly 
- `get_cis_expected` (supports views (i.e. arms), flags for smoothing=True by default, aggregate=True by default) 
- `get_trans_expected`
- `contacts_vs_distance` (also includes derivative) @golobor 

`cooler.saddle`: needs refactoring to make the following work @gfudenberg  
- ~~`make_saddle` --> `get_saddle`. needs to be changed (or wrapped) to accept a cooler as input.~~
- `saddle_strength`. update docstring to clarify it relies on make_saddle output.

`cooler.sample`:
- `sample_cooler`

`cooler.snipping`: @Phlya 
- ????

This would be a way to distinguish the "public" functions vs more internal/lowlevel ones. This has the bonus where the lower-level functions can be freed from tedious parsing and sanitation of input arguments.

**Comment by gfudenberg** [comment]
are `compute_scaling`, `contact_areas`, and `_contact_areas` the functions for reads that should be moved out of expected? cc @golobor @nvictus

**Comment by gfudenberg** [comment]
done, right? cc @golobor

**Comment by golobor** [comment]
seems so! expect for saddle. saddleplot

**Comment by gfudenberg** [comment]
ok, closing this & making an informative issue for saddleplot
