### ISSUE TITLE
TypeError: Cannot cast array data from dtype('<f8') to dtype('int64') according to the rule 'safe'

### ISSUE THREAD

**Issue by ngocemy** [open2c/cooltools#259]
Cooltools random-sample -c 10000 input.cool output.subsample.cool

**Comment by gfudenberg** [comment]
this cooler might have its counts saved as an unexpected dtype.
can you open the cooler with the python API and print what comes up in the pixel table? e.g.  
import cooler
cooler.Cooler(input.cool).pixels()[:3]

**Comment by gfudenberg** [comment]
hope this suggestion helped, feel free to reopen
