### ISSUE TITLE
cooltools compute-saddle - add option for saving saddledata Sums and Counts separately

### ISSUE THREAD

**Issue by ehildebr** [open2c/cooltools#261]
Hello! 

Thanks for all the great work with cooltools. I am wondering if it would be useful to have an option to be able to save the saddledata sums and counts separately in the CLI version of compute-saddle, rather than just the ratio of sums/counts? This would make it easy to calculate strength separately for A vs B compartments, or high vs low of other types of tracks. Alternatively, there could be an option to just calculate those strengths separately and save that in the results. This is the main reason that I do not usually use the CLI version, and instead use the API functions in order to save the counts and sums separately, so just thought it might be a nice enhancement! 

Thanks!

**Comment by sergpolly** [comment]
thank you for suggestion!
now saves `saddledata` which is a ratio of "sums"/"count", and `saddlecounts` - "count".
One can "reconstruct" sums as `saddlesums = saddledata*saddlecounts`
this is a non-redundant way of storing both things along with the most used "ratios"

will be part of `0.5` release
