### ISSUE TITLE
logbin-expected .log.tsv and .der.tsv identical

### ISSUE THREAD

**Issue by ehildebr** [open2c/cooltools#268]
Hello,

When I ran cooltools logbin-expected I found that both the resulting .tsv files were identical, and there was no slope column. I think this may be due to lines 186-191 in https://github.com/open2c/cooltools/blob/master/cooltools/cli/logbin_expected.py:
```
    lb_cvd_agg.to_csv(
        f'{output_prefix}.der.tsv',
        sep="\t",
        index=False,
        na_rep="nan",
    )
```

Should it be this instead?
```
    lb_slopes_agg.to_csv(
        f'{output_prefix}.der.tsv',
        sep="\t",
        index=False,
        na_rep="nan",
    )
``` 

Thanks!

**Comment by Phlya** [comment]
I think you are right about the fix! Sorry about that. Would you like to try it and submit a PR?

Interestingly, just yesterday we were discussing how to proceed with logbinning expected and CLI, and in the future it'll probably all be integrated into the main `compute-expected` command.
