### ISSUE TITLE
cooler-aligned genomic tracks: definitions & assumptions 

### ISSUE THREAD

**Issue by gfudenberg** [open2c/cooltools#271]
for now: 
- should be dataframes with 4 columns
- interpret them as ['chrom','start','end','value']

used in functions as the following:
`my_func_of_track(track, kwargs*)`

this overwrites the old tuple (dataframe, value_column) format:
`my_func_of_track_OLD( (track, 'track_val'), kwargs*)`

for discussion: which scenarios cause issues for tracks?
- missing bins  
- not contained
- track bins that are nans in the cooler.bins()['weight']
- bins do not match track (offset or resolution or trimming ends or 0/1...)
- extra chromosome in track or cooler

**Comment by golobor** [comment]
we would also need cooltools.core.checks.is_cooler_aligned(track, clr)

**Comment by gfudenberg** [comment]
addressed in #320

**Comment by gfudenberg** [comment]
addresses multiple points in 0.6 roadmap #312
