### ISSUE TITLE
cooler kwargs for cooltools functions

### ISSUE THREAD

**Issue by gfudenberg** [open2c/cooltools#272]
for clarity, pass 
```python
my_func_of_clr(
 clr, stuff, ..., clr_weight_name="weight")
```
 instead of `weight="weight"` or `weight_name="weight"`

**Comment by agalitsyna** [comment]
Checked/added for:

- [ ] insulation
- [ ] snipping
- [ ] eigdecomp
- [ ] saddle
- [ ] coverage
- [ ] dotfinder
- [ ] expected

**Comment by agalitsyna** [comment]
Looks like in some places we already use similar parameter, "balance", e.g. https://github.com/open2c/cooltools/blob/5ec504ffa57e7532ef7014d9ce683101644db9a2/cooltools/eigdecomp.py#L296
Here, "balance" is used both as the name of the weight column and as the flag for balancing (can be False). 

What I find surprising is that in the same function there is a separate usage of "weight" column, not related to the passed balancing weight: 
https://github.com/open2c/cooltools/blob/5ec504ffa57e7532ef7014d9ce683101644db9a2/cooltools/eigdecomp.py#L386 

These two roles are very different, and I suggest to use "balanced" as flag only and pass "clr_weight_name" as column name simultaneously. This requires some discussion and deciding what's the best for all.  

List of locations where the change is needed: 

- [ ] Insulation code, no separate "balanced" parameter at all:
https://github.com/open2c/cooltools/blob/5ec504ffa57e7532ef7014d9ce683101644db9a2/cooltools/insulation.py#L73
- [ ] Deprecated function for dense insulation (yet important for testing) has both balance and weight:
https://github.com/open2c/cooltools/blob/5ec504ffa57e7532ef7014d9ce683101644db9a2/cooltools/insulation.py#L391
- [ ] Saddles are fully transferred to clr_weight_name, but it is used for both indicator of balancing and retrieval of weights: 
https://github.com/open2c/cooltools/blob/5ec504ffa57e7532ef7014d9ce683101644db9a2/cooltools/saddle.py#L374
- [ ] dot finder code uses yet another parameter called "bal_v_name": 
https://github.com/open2c/cooltools/blob/5ec504ffa57e7532ef7014d9ce683101644db9a2/cooltools/dotfinder.py#L924
- [ ] expected code uses "weight_name" and "clr_weight_name" interchangeably: 
https://github.com/open2c/cooltools/blob/5ec504ffa57e7532ef7014d9ce683101644db9a2/cooltools/expected.py#L313
- [ ] snipping code does not use any weight parameter at all: 
https://github.com/open2c/cooltools/blob/5ec504ffa57e7532ef7014d9ce683101644db9a2/cooltools/snipping.py#L261

**Comment by golobor** [comment]
fixed for user-facing functions (clr_weight_name + occasional ignore_diags), but should be standardized for the low-level functions too

**Comment by agalitsyna** [comment]
Balancing options are now propagated from the CLI to low-level functions everywhere. 

`insulation` supports calculations on unbalanced data, which is passed as` clr_weight_name=None` to API or `--clr-weight-name ""` to CLI. 

Note that `coverage` does not support `clr_weight_name` at all, while `eigdecomp` and `saddle` support only balanced data (because the eigdecomp is defined for ICed data only).

**Comment by Phlya** [comment]
That's great, thank you @agalitsyna ! I think we could allow unbalanced saddles though, in case one wants to do it on single-cell data, for example. Also saddles don't necessarily have to be based on eigenvectors.

**Comment by agalitsyna** [comment]
Thanks, @Phlya I agree, like checking GC-dependent interaction bias might be also instructive on raw data. Should be easy to add. Can you work on it? Thanks!

**Comment by Phlya** [comment]
OK I think I have it ready, but will check whether it actually works tomorrow morning!

BTW do we use `clr_weight_name=False` or `None`? I think would be better to just support both. `None` sort of makes more sense, but `clr.matrix()` expected `balance=False` for this... So We can just add 
```
if clr_weight_name is None:
    clr_weight_name = False
```
everywhere?

**Comment by agalitsyna** [comment]
`clr.matrix()` works with both `None` and `False`, also str `clr_weight_name` as a nice bonus. This, I think, will work in all of these cases:

```
if clr_weight_name:
  ...<do the balancing-related computations>...
else:
  ... <do other computations> ...
```

Seems like it's already these, but we can check all the usecases.

**Comment by Phlya** [comment]
Ah is clr.matrix works with None then there are no problems, great, thanks!

**Comment by Phlya** [comment]
I pushed the saddle update. It works!

One thing to remember is to add `expected_value_col="count.avg"` when using unbalanced data!
