### ISSUE TITLE
Calculate the P(s) curve

### ISSUE THREAD

**Issue by luciaalvarez95** [open2c/cooltools#275]
Hi!

I am new with cooltools and I am following the _Calculate the P(s) curve_ tutorial described here: https://cooltools.readthedocs.io/en/latest/notebooks/contacts_vs_distance.html#Calculate-the-P(s)-curve Ererything is okay until I get to the _cooltools.expected.diagsum_ part where I get this error: **TypeError: diagsum() got an unexpected keyword argument 'regions'** I tried to solve this error by changing regions with view_df however when I tried that I get this error: **ValueError: Unknown sequence label: chr1** So, I don't know what I should do...could you help me?

Moreover, I am learning how to use this tools because I want to calculate the P(s) curves and its derivative for several mammalian species that do not have a good uscs datasets, so I cannot run this with them:

_hg38_chromsizes = bioframe.fetch_chromsizes('hg38')
hg38_cens = bioframe.fetch_centromeres('hg38')
hg38_arms = bioframe.core.construction.add_ucsc_name_column(bioframe.make_chromarms(hg38_chromsizes,  hg38_cens))_

Is it possible to calculate the P(s) curves without this part?

Many thanks

Lucía

**Comment by gfudenberg** [comment]
Hi Lucía,

Which versions are you using for cooltools & bioframe (e.g.
cooltools.__version__ and bioframe.__version__)?

It will definitely be possible to calculate for non-standard genomes, but
you might need to load in your own chrom sizes file (or get it from the
cooler you're using).

**Comment by luciaalvarez95** [comment]
Hi!

Many thanks for your reply! I think I have the latest version of both:
```
>>> cooltools.__version__
'0.4.0'
>>> bioframe.__version__
'0.3.0'
```

So, for non-standard genomes, in _cooltools.expected.diagsum_ I should include the chrom sizes file as regions? I have a chrom size file for each of the genomes I am working with, but I dont really understand where I should include it and how I have to load it for the function to work properly.  

Sorry for the amount of questions, im kind of new with all of this! Thanks again!

Lucía

**Comment by gfudenberg** [comment]
No worries-- these sorts of questions are very helpful for us to improve
cooltools :)

If you have the chromarms file, you should be able to load it with pandas,
and then try to turn it into a viewFrame with (chrom, start, end, name)
columns with `bioframe.make_viewframe()`. You can add a name column with
`bioframe.core.construction.add_ucsc_name_column()`.

We will be modifying expected.py soon to hopefully make things easier
for users, but I'll make an issue for the example notebook to add a note
saying how to use / load custom chromosome arms.

**Comment by luciaalvarez95** [comment]
Hi! Many thanks for your help!
It works now for  my mammalian species just doing this:

```
chromsizes = pd.read_csv('v5.sizes', sep='\t')
arms = bioframe.core.construction.add_ucsc_name_column(bioframe.make_viewframe(chromsizes))
```

**Comment by gfudenberg** [comment]
added a note-- https://github.com/open2c/open2c_examples/pull/13, please re-open if you think additional information for non-standard genomes would be useful!
