### ISSUE TITLE
in expected.diagsum_from_array , bad bin inference breaks down for small arrays

### ISSUE THREAD

**Issue by golobor** [open2c/cooltools#276]
just lost several hours b/c of the following bug:
in diagsum_from_array, bad bins are inferred as rows/columns with zero counts.
https://github.com/open2c/cooltools/blob/6b2fd1db4597be9d40dc9486ef6f5e80b8429e74/cooltools/expected.py#L1051

This assumption breaks down for small arrays and leads to artificial inflation of the returned scaling.
Proposed solution: if input array contains NaNs, use them to infer bad bins:

invalid_mask1 = np.sum(np.isnan(A), axis=1) == A.shape[0]
invalid_mask2 = np.sum(np.isnan(A), axis=0) == A.shape[1]
A[~np.isfinite(A)] = 0

otherwise, estimate bad bins from zeros, but give a warning.
@Phlya - I think, you wrote this function? What do you think of the proposed solution?

**Comment by Phlya** [comment]
I don't think I wrote that function (maybe you are thinking of the masking in the saddle function, that I wrote following your suggestion?), but it sounds like a good solution to me...

**Comment by sergpolly** [comment]
fixed - right ?
