### ISSUE TITLE
No --view option in cooltools call-compartments

### ISSUE THREAD

**Issue by LIZW2019** [open2c/cooltools#278]
I have used the --view option to restrict the compartment calling in some regions in the genome following the guidance of the  [cooltools document](https://cooltools.readthedocs.io/en/latest/cli.html#cooltools-call-compartments). I have already updated the tool to the latest version but it still told me that it doesn't have that option. Is it a misleading message in the document or my wrong operation?

**Comment by gfudenberg** [comment]
see updated notebooks & feel free to re-open if that is not resolved!
