### ISSUE TITLE
get_cis_expected API (smoothing, aggregation, etc)

### ISSUE THREAD

**Issue by gfudenberg** [open2c/cooltools#280]
- [ ] propagating NaNs through smoothing e.g. balanced.sum.smoothed should be NaN if balanced.sum is NaN.

- [ ] consider renaming balanced & areas here to something more interpretable (smoothed_values, smoothed_counts?)
https://github.com/open2c/cooltools/blob/f478c1c7b69d8dabeb383c9a5aab5d6d753a6417/cooltools/sandbox/expected_smoothing.py#L195

- [ ] its not currently clear what the agg argument is supposed to do-- it seems to deletes the count column (which also has slightly unexpected values)

![image](https://user-images.githubusercontent.com/19657573/137390804-880ac107-2175-4969-a0db-3b4a32e03c19.png)

cc @golobor

**Comment by golobor** [comment]
thank you for these thoughtful comments!

> propagating NaNs through smoothing e.g. balanced.sum.smoothed should be NaN if balanced.sum is NaN.

not sure if I agree with this one! By definition, smoothing assumes that the "true" value of contact frequency for a given diagonal can be inferred from those from adjacent diagonals. If if some diagonal misses good pixels entirely, I would say, we should still be able to estimate its contact frequency, no?..

>  consider renaming balanced & areas here to something more interpretable (smoothed_values, smoothed_counts?)

Done!

>  its not currently clear what the agg argument is supposed to do-- it seems to deletes the count column (which also has slightly unexpected values)

Yes, that is a good point - I just pushed new API that does not have this argument and does not drop columns that were present in the cvd table: 
https://github.com/open2c/cooltools/blob/704f259c4df5bc1c61be915bf56c80b00a0298ed/cooltools/sandbox/expected_smoothing.py#L232
https://github.com/open2c/cooltools/blob/master/cooltools/sandbox/expected_smoothing_example.ipynb

**Comment by gfudenberg** [comment]
going through the notebooks, noticed that the docstring for 
``` python
def get_cis_expected(
    ...
    intra_only=True,
    ...
):
 says intra_only=False returns all combinations, but it only returns non-symmetric combinations. 

Had we discussed a desired behavior?


https://github.com/open2c/cooltools/blob/ad018d6005b5df852cf39f6ec5321bdfab95106f/cooltools/expected.py#L984

**Comment by sergpolly** [comment]
yes, - we've discussed ...
conclusion was to makr `intra_only=False` to return EVERYTHING - intra and inter together
I'll check after everyone goes to sleep

**Comment by gfudenberg** [comment]
actually, now seems to be an issue on the main branch that emerges with intra_only=False for get_cis_expected (or one of the checks that gets called) 
![image](https://user-images.githubusercontent.com/19657573/141224372-30f603e6-594e-4281-9eb5-6ee7745c39c9.png)

**Comment by gfudenberg** [comment]
Update: looks like the issue is with the sorting check-- I think it actually doesn't make sense, b/c there could be more regions in the view than in the cooler, but it could still be compatible

**Comment by sergpolly** [comment]
@gfudenberg we need viewframe to be sorted (by coordinate and according to cooler's order of chromosomes) because we generate "inter"-regions (inter arms, inter - whatever) in a pairwise combination fashion - i.e. first with second, first with third etc - and if viewframe isn't sorted - some of these inter regions would end up in the lower left side of the heatmap

enforcing sorted viewframe is the easiest way to deal with it

**Comment by gfudenberg** [comment]
I'm not sure if this would be a different check if it's only used
sometimes-- one could potentially want a view that is in a different order
of a cooler for many analyses while still wanting this intervals contained
in the cooler.

Also,
current sort implementation doesn't work for a set of arms that are sorted.
So it might need to use an interval-wise sort rather than a name-wise sort.

**Comment by sergpolly** [comment]
`is_compatible_viewframe` does not check order by default - only when requested
we request it for pairwise expected calculations , because we need it there to ensure we're in the upper right triangle of the heatmap

I've just checked is_sorted on arms and on the subset of arms and everything seems to work ok - i.e. in the same open2c example notebook with the microC dataset reduced to 2 chroms . The only thing I had to do is to reduce hg38_arms down to chromosomes available in the cooler itself - i.e. chr2 and chr17

**Comment by sergpolly** [comment]
the problem with `intra_only=False` was indeed real - it didn't do what we've agreed on - it was only returning intra (i.e. asymmetric expecteds)
I'm about to push some changes to correct for it

**Comment by gfudenberg** [comment]
Ah, had though I dropped chrms but maybe I didn't. Should definitely add a
note about sortedness to the docstring.

**Comment by gfudenberg** [comment]
discussion 11.12:

**Comment by gfudenberg** [comment]
bubbling up the idea of propagating NaNs--
the current smoothing does not interpolate to dist=1 correctly, that's all I was suggesting, not NaNs later in the curve. Does that make more sense @golobor ?

**Comment by gfudenberg** [comment]
this commit adds np.nan propagation for smoothed outputs
https://github.com/open2c/cooltools/blob/1e953e3ba8291af26229adda8bd5c833ec2a2fac/cooltools/api/expected.py#L1047

is that o.k. ? @golobor @sergpolly

**Comment by sergpolly** [comment]
the newest API proposal - `expected_full` that would combine cis and trans expected-s together:
```python
expected_full(
        clr,
        view_df=None,  # same view e.g. arms for cis and trans
        smooth_cis=False,  # smooth cis True|False
        aggregate_cis=False,  # aggregate cis expected False | "chrom" | "genome"
        # we have to allow for aggregate_trans, e.g. when calculating trans expected by arm
        aggregate_trans=False,  # aggregate trans expected False | "chrom" | "genome"
        expected_column_name="expected",  # store final result in a single column
        drop_intermediate_columns=True,  # drop count.sum, balanced.sum, n_valid balanced.sum.smooth etc ...

        # usual options
        smooth_sigma=0.1,
        ignore_diags=2,
        clr_weight_name='weight',
        chunksize=10_000_000,
        nproc=4,
)
```
sample output without intermediate columns:

region1 | region2 | dist | expected
-- | -- | -- | --
chr2_p | chr2_p | 0 | NaN
chr2_p | chr2_p | 1 | NaN
chr2_p | chr2_p | 2 | 0.068918
chr2_p | chr2_p | 3 | 0.045381
... | ... | ... | ...
chr2_p | chr2_q | 2421 | 0.000050
chr2_p | chr17_p | -1 | 0.000022
chr2_p | chr17_q | -1 | 0.000022
chr2_q | chr17_p | -1 | 0.000022
chr2_q | chr17_q | -1 | 0.000022




note, how trans-expected has a special value for distance `-1` - allowing for easy filtering and aggregation.

Here is the same output with the intermediate columns:

region1 | region2 | dist | n_valid | balanced.sum | balanced.avg | balanced.avg.smooth | expected
-- | -- | -- | -- | -- | -- | -- | --
chr2_p | chr2_p | 0 | 878.0 | NaN | NaN | NaN | NaN
chr2_p | chr2_p | 1 | 876.0 | NaN | NaN | 0.000795 | 0.000795
chr2_p | chr2_p | 2 | 874.0 | 65.287351 | 0.074699 | 0.068918 | 0.068918
chr2_p | chr2_p | 3 | 872.0 | 41.011675 | 0.047032 | 0.045381 | 0.045381
... | ... | ... | ... | ... | ... | ... | ...
chr2_p | chr2_q | 2421 | 0.0 | 0.000000 | NaN | 0.000050 | 0.000050
chr2_p | chr17_p | -1 | 174722.0 | 3.940185 | 0.000023 | NaN | 0.000022
chr2_p | chr17_q | -1 | 477632.0 | 10.879623 | 0.000023 | NaN | 0.000022
chr2_q | chr17_p | -1 | 284769.0 | 5.839495 | 0.000021 | NaN | 0.000022
chr2_q | chr17_q | -1 | 778464.0 | 16.283992 | 0.000021 | NaN | 0.000022

**Comment by sergpolly** [comment]
in the name of biology we converged on the following API:
```python
expected_full_fast(
    clr,
    view_df=hg38_arms,  # same view for cis and trans
    smooth_cis=True, # applies yto both inter and intra (-cis)
    smooth_log10=0.03
    combine_cis = False|"intra_genomewide"|function !
    combine_trans= False(None)|"chrom"|"genomewide"|function !
    expected_column_name="expected"
    store_intermediate_columns=True
)
# region1, region2, dist, expected_column - default

# if everything ios False and choose to store intermediates ...
# region1 region2 dist n_valid balanced.sum balanced.avg expected
```

**Comment by gfudenberg** [comment]
API discussion superseded by https://github.com/open2c/cooltools/pull/501

the issue of propagating NaNs from count.avg & balanced.avg to the smoothed columns remains
