### ISSUE TITLE
snipping.pileups docstring does not match the behavior in the code

### ISSUE THREAD

**Issue by sergpolly** [open2c/cooltools#283]
https://github.com/open2c/cooltools/blob/0c1d32f489be86f3191cd7a8f5508c4b6564a6b5/cooltools/snipping.py#L170

**Comment by gfudenberg** [comment]
looks ok in 0.5.0!
https://github.com/open2c/cooltools/blob/596e232aa80e737f70ed3e52679ebdb4b7bbbe50/cooltools/api/snipping.py#L654
