### ISSUE TITLE
insulation updates for 0.5.0

### ISSUE THREAD

**Issue by golobor** [open2c/cooltools#291]
the whole set of insulation functions needs to be updated, e.g.

- [x] `diamond_insulation` does not have view_df as an input (currently takes chrms) https://github.com/open2c/cooltools/blob/938ec3007725d53312f757ebc51558e8293a5dcd/cooltools/cli/diamond_insulation.py#L55 

- [x] `find_boundaries` operates on chrms, not view regions. Should also preserve index of original dataframe, which would solve https://github.com/open2c/cooltools/issues/210

- [x] `calculate_insulation_score` operates on chrms, not view regions.https://github.com/open2c/cooltools/blob/938ec3007725d53312f757ebc51558e8293a5dcd/cooltools/insulation.py#L121
  - also https://github.com/open2c/cooltools/issues/266

- [x] in `insul_diamond`, allow `clr_weight_name` to be passed
currently, the weight column is hard-coded:
https://github.com/open2c/cooltools/blob/db9392a992fcad52c8d277f51e80ebb1a4c4e551/cooltools/insulation.py#L80

**Comment by golobor** [comment]
thank you, @dmalzl!

**Comment by gfudenberg** [comment]
for CLI:

- https://github.com/open2c/cooltools/issues/256

**Comment by agalitsyna** [comment]
for CLI and calculate_insulation_score: 

- https://github.com/open2c/cooltools/issues/266

**Comment by golobor** [comment]
we also need a single function that calculates scores, calls and filters boundaries (so called "user-facing" function as defined in #258 )

**Comment by sergpolly** [comment]
@golobor 

just check insulation CLI code - there are literally just 2 function calls - and they looks user-facing enough to me:
```python
    # Calculate insulation score:
    ins_table = insulation.calculate_insulation_score(
        clr,
        view_df=view_df,
        window_bp=window,
        ignore_diags=ignore_diags,
        min_dist_bad_bin=min_dist_bad_bin,
        append_raw_scores=append_raw_scores,
        chunksize=chunksize,
        verbose=verbose,
    )

    # Find boundaries:
    ins_table = insulation.find_boundaries(
        ins_table,
        view_df=view_df,
        min_frac_valid_pixels=min_frac_valid_pixels,
        min_dist_bad_bin=min_dist_bad_bin,
    )
```

what else is needed ?

**Comment by gfudenberg** [comment]
tests for insulation.insulation to be added post-release
