### ISSUE TITLE
do we want to use decorators to "hide" compatibility checks?

### ISSUE THREAD

**Issue by sergpolly** [open2c/cooltools#309]
from one of the discussions about our new "checks" someone mentioned "decorators" ...
Are we looking to do something like below:
![Screenshot from 2021-11-16 17-27-51](https://user-images.githubusercontent.com/6790270/142076533-a64d858c-6e7d-40f4-9d08-d20d9bd7e183.png)

I think this would be very very cool and improve readability of the code

**Comment by Phlya** [comment]
Yeah I think I mentioned this, and that's what I meant! Indeed I think it would be cool.

**Comment by sergpolly** [comment]
will leave some relevant info here:
https://learning-python.com/rangetest.html

so, what not so trivial is to extract values of some specific arguments that were passed to one of our functions, i.e.:
```python
@check_cooler_balanced
def expected_cis(
    clr,
    view_df=None,
    intra_only=True,
    smooth=True,
    aggregate_smoothed=True,
    smooth_sigma=0.1,
    clr_weight_name="weight",
    ignore_diags=2
...
)
```
in this case hypothetical `check_cooler_balanced` would need to "intercept" only relevant arguments passed to `epected_cis` - i.e. `clr` and `clr_weight_name` - from `*args` and `**kwargs` passed to `expected_cis` ...

 - "intercepting" `clr` can be easy, as it is positional , and we could agree that it would always be the first one or whatrever (still important to note that it could be passed via `*args`, or `**kwargs` still ! `expected_cis(myclr)` vs `expected_cis(clr=myclr)`)
 - "intercepting" `clr_weight_name` isn't so easy - as it could be passed as `args` or `kwargs`, or skipped altogether (since it has a default) - then you'd have to make sure it was skipped and apply its default for the checker
 - users might not obey the original function signature and then it'll fall apart  - how exactly  ?

some relevant bit for introspecting functions:
```python
import inspect
argspec = inspect.getfullargspec(func)

assert "clr" in argspec.args
assert "clr_weight_name" in argspec.args

# catching strictly positional argument
if "clr" not in kwargs:
    _arg_index = argspec.args.index("clr")
    _val_passed = args[_arg_index]
    clr = _val_passed
else:
    clr = kwargs["clr"]

# last n-defaults !
argspec.defaults
...
```

there is also that https://www.python.org/dev/peps/pep-3102/ - that @mimakaev  brought up some time ago (enforcing kwargs form for some arguments)

**Comment by sergpolly** [comment]
this is mega https://stackoverflow.com/questions/57314496/how-to-intercept-and-preproccess-arguments-with-decorators
