### ISSUE TITLE
Tutorial issue when using bioframe to create a view with chr arms 

### ISSUE THREAD

**Issue by JSegueni** [open2c/cooltools#316]
Hi everyone,
Thanks for developing cooltools :)

I'm trying to determine the number of reads in each bin of my Hi-C matrix, to select the best possible resolution.

In this tutorial, using bioframe: https://cooltools.readthedocs.io/en/latest/notebooks/contacts_vs_distance.html,
we are told to run the following code:

`
hg38_chromsizes = bioframe.fetch_chromsizes('hg38')

hg38_cens = bioframe.fetch_centromeres('hg38')

hg38_arms = bioframe.make_chromarms(hg38_chromsizes,  hg38_cens)

hg38_arms = hg38_arms[hg38_arms.chrom.isin(clr.chromnames)].reset_index(drop=True)
hg38_arms
`

At this line:
`hg38_arms = bioframe.make_chromarms(hg38_chromsizes,  hg38_cens)`

I get the following error message: "ValueError: mids not in keys of df.columns"

After checking the columns in hg38_cens, I renamed a column from "mid" to "mids" to get over the error.

I got a new error message saying "KeyError: 'index_2'" causing two exceptions.

My environment: 
Python version: 3.9.6
Bioframe: 0.2.0
Cooltools: 0.4.0

How should I fix this issue?

Best,
Julie.

**Comment by gfudenberg** [comment]
Hi Julie-- please try updating bioframe and cooltools to 0.3+ and 0.5+ & let us know if that resolves the issue. Thank you!

**Comment by zhengdafangyuan** [comment]
Hi gfudenberg,  I have the same question.

Error info
`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_3988/561494880.py in <module>
      3 hg38_cens = bioframe.fetch_centromeres('hg38')
      4 # create a view with chromosome arms using chromosome sizes and definition of centromeres
----> 5 hg38_arms = bioframe.make_chromarms(hg38_chromsizes,  hg38_cens)
      6 
      7 # select only those chromosomes available in cooler

~/miniconda3/envs/PoreC/lib/python3.8/site-packages/bioframe/genomeops.py in make_chromarms(chromsizes, midpoints, cols_chroms, cols_mids, suffixes)
     54         df_mids = midpoints.copy()
     55 
---> 56     ops._verify_columns(df_mids, [ck2, sk2])
     57     ops._verify_columns(df_chroms, [ck1, sk1])
     58 

~/miniconda3/envs/PoreC/lib/python3.8/site-packages/bioframe/ops.py in _verify_columns(df, colnames)
     52     """
     53     if not set(colnames).issubset(df.columns):
---> 54         raise ValueError(
     55             ", ".join(set(colnames).difference(set(df.columns)))
     56             + " not in keys of df.columns"

ValueError: mids not in keys of df.columns
`
In my environment,  bioframe 0.3.1,  cooltools   0.5.0;

I tired to change the "hg38_cens" column id
`hg38_cens = hg38_cens.rename(columns={"mid":"mids"})` , 
but annother error occurred:

`KeyError                                  Traceback (most recent call last)
~/miniconda3/envs/PoreC/lib/python3.8/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   3360             try:
-> 3361                 return self._engine.get_loc(casted_key)
   3362             except KeyError as err:

~/miniconda3/envs/PoreC/lib/python3.8/site-packages/pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

~/miniconda3/envs/PoreC/lib/python3.8/site-packages/pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'index_2'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
/tmp/ipykernel_3988/198135224.py in <module>
      5 hg38_cens = hg38_cens.rename(columns={"mid":"mids"})
      6 # create a view with chromosome arms using chromosome sizes and definition of centromeres
----> 7 hg38_arms = bioframe.make_chromarms(hg38_chromsizes,  hg38_cens)
      8 # select only those chromosomes available in cooler
      9 hg38_arms = hg38_arms[hg38_arms.chrom.isin(clr.chromnames)].reset_index(drop=True)

~/miniconda3/envs/PoreC/lib/python3.8/site-packages/bioframe/genomeops.py in make_chromarms(chromsizes, midpoints, cols_chroms, cols_mids, suffixes)
     60     df_chroms["end"] = df_chroms[sk1].values
     61 
---> 62     df_chromarms = ops.split(
     63         df_chroms,
     64         df_mids,

~/miniconda3/envs/PoreC/lib/python3.8/site-packages/bioframe/ops.py in split(df, points, cols, cols_points, add_names, suffixes)
   1251     if add_names:
   1252         df_split = regions_add_name_column(df_split)
-> 1253         sides = np.mod(df_split["index_2"].values, 2).astype(int)  # .astype(str)
   1254         df_split["name"] = df_split["name"].values + np.array(suffixes)[sides]
   1255         df_split.drop(columns=["index_2"])

~/miniconda3/envs/PoreC/lib/python3.8/site-packages/pandas/core/frame.py in __getitem__(self, key)
   3456             if self.columns.nlevels > 1:
   3457                 return self._getitem_multilevel(key)
-> 3458             indexer = self.columns.get_loc(key)
   3459             if is_integer(indexer):
   3460                 indexer = [indexer]

~/miniconda3/envs/PoreC/lib/python3.8/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   3361                 return self._engine.get_loc(casted_key)
   3362             except KeyError as err:
-> 3363                 raise KeyError(key) from err
   3364 
   3365         if is_scalar(key) and isna(key) and not self.hasnans:

KeyError: 'index_2'`

Could you help with it, thanks!

All the best,
Zhong.

**Comment by gfudenberg** [comment]
Hi Zhong (and Julie, since I forgot to mention this previously!),

This looks again like the version mismatch issue.

If you have conda installed (https://docs.anaconda.com/anaconda/install/) the easiest way to get things working is to create an environment from the one provided in https://github.com/open2c/open2c_examples. i.e. after cloning the repository, navigate to the folder & execute the following in the command line:
conda env create -f environment.yml
conda activate open2c
Then start jupyter notebooks.

Closing for now, because we just tested the environment.yml approach, but feel free to re-open if the issue persists.
Thanks!

**Comment by zhengdafangyuan** [comment]
Hi Geoff,

I updated the bioframe to version 0.3.1 in jupyter kernel, and it works fine now !

Thanks,
Zhong


> Hi Zhong,
> 
> Can you print the versions of bioframe/cooltools in the jupyter notebook that you are working in? Sometimes jupyter can use a different kernel than expected.
> 
> Also, @JSegueni, I forgot to mention this previously but if you have conda installed (https://docs.anaconda.com/anaconda/install/) the easiest way to get things working is to create an environment from the one provided in https://github.com/open2c/open2c_examples. i.e. after cloning the repository, navigate to the folder & execute the following in the command line: conda env create -f environment.yml conda activate open2c Then start jupyter notebooks.
> 
> @zhengdafangyuan can you try this as well? Thanks! Geoff

**Comment by gfudenberg** [comment]
Good to know, thanks!
