### ISSUE TITLE
making cooler bad bins in user-facing functions

### ISSUE THREAD

**Issue by sergpolly** [open2c/cooltools#319]
should `mask_cooler_bad_bins` (one that assigns NaNs to bad bins from cooler to a track before doing saddle) become a part of one of the user-facing functions ?

right now it is done in CLI outside of any user-facing functions `digitize` or `saddle` - it does not fit into `digitize` now, because `digitize` does not know about the `cooler` (now), but by the time we get to `api.saddle` it is too late ...

Does it "deserve" to be brought into `digitize` by making it depend on the `cooler` and/or some `bad_bin_mask` (optionally of course)?

Is masking "bad" bins really important for saddle ?:
- masking bad bins in the track seems important and (?)could affect the result of the saddle(?) via outliers , maybe ...
- maybe should check with a track defined for every bin (e.g. GC-content) and test with and without masking bad bins from cooler

_Originally posted by @sergpolly in https://github.com/open2c/cooltools/pull/318#discussion_r763113621_

**Comment by Phlya** [comment]
Need to find that discussion with details, but I remember that masking bad bins was very important for saddles based on e.g. ChIP-seq etc. Otherwise they looked ugly for some reason...

I think adding an argument with bad bins to digitize would make sense!

**Comment by Phlya** [comment]
https://github.com/open2c/cooltools/pull/103 Found the PR where it was added with a before and after example

**Comment by gfudenberg** [comment]
Good sleuthing @Phlya !
I wonder if such an argument is added to digitize, which will require passing a clr and clr_weight_name, then digitization should just be wrapped into the one user facing function. 
Thoughts?

**Comment by Phlya** [comment]
I thought it should be wrapped into `saddle` from the beginning, but it doesn't have to be just for this - we can just add an argument with a mask of some sort that's easy to get from bins.

**Comment by gfudenberg** [comment]
I think the main reasoning for keeping `api.digitize` & `api.saddle` separated in the python api was this would increase the number of arguments passed to each, so if we added another argument to `api.digitize` the old reasoning wouldn't necessarily hold. Any objections to wrapping `api.digitize` into `api.saddle`? we could keep `api.digitize` exposed for ease of exploration.

cc @nvictus @golobor

**Comment by gfudenberg** [comment]
Relatedly, I'm thinking that for `eigs_cis` it is confusing to have 'clr' and 'bins' as required inputs. This also makes the current docstring for 'bins' confusing:
> bins : DataFrame
> table of bins derived from clr with phasing track added

How about the following: 
- pass a keyword argument 'track=' (or `phasing_track=`), and merge this with clr.bins()[:] inside the function, making use of the new `merge_track_with_cooler`.
- if 'phasing_track'=None, don't phase 
```python
def eigs_cis(
    clr,
    phasing_track=None,
    view_df=None,
    n_eigs=3,
    phasing_track_col="GC",
    clr_weight_name="weight",
    ignore_diags=None,
    bad_bins=None,
    clip_percentile=99.9,
    sort_metric=None,
    map=map,
):
```

This would avoid the following pattern in the cli, where we (first merge the phasing track with the bins) then pass 'bins=track':
```python
   eigvals, eigvec_table = eigdecomp.eigs_cis(
        clr=clr,
        bins=track,
        view_df=view_df,
        n_eigs=n_eigs,
        clr_weight_name=clr_weight_name,
        ignore_diags=ignore_diags,
        phasing_track_col=track_name,
        clip_percentile=99.9,
        sort_metric=None,
    )
```

**Comment by sergpolly** [comment]
> Relatedly, I'm thinking that for `api.eigs_cis` it is confusing to have 'clr' and 'bins' as required inputs. This also makes the current docstring for 'bins' confusing:
> 
> > bins : DataFrame
> > table of bins derived from clr with phasing track added

:+1: 100% !


> How about the following:
> 
> * pass a keyword argument 'phasing_track=', and merge this with clr.bins()[:] inside the function, making use of the new `merge_track_with_cooler`.
> * if 'phasing_track'=None, don't orient
:+1:  :+1: 
> * 'bad_bins' can either be 'None', in which case it uses cooler bins for masking, 'False' which would be passed to `merge_track_with_cooler(..., mask_bad_bins=False)` and no masking is done, or an array-like list of bins to ignore (ie. as currently).

Do we really need the array-like list of bins option ? maybe at least start deprecating it ?

> Finally, should we rename the `--reference-track` argument in the cli.eigs_cis should be renamed to `--phasing-track` for clarity/synchrony?

:+1:

**Comment by gfudenberg** [comment]
I had forgot the main use of `bad_bins` in this function... 
in that case, maybe keep it as is and use default for `mask_bad_bins` in `merge_track_with_cooler()`?

also, seems that `eigs_trans()` doesn't have `bad_bins` as a kwarg... or a docstring!

**Comment by gfudenberg** [comment]
update from 12/15 discussion: 
- keep digitize as a dataframe operation (no passing coolers)
- wrap digitize into user-facing api.saddle()
- allow passing a pre-digitized track to api.saddle(), which would not be re-digitized

**Comment by gfudenberg** [comment]
adddressed in #320
