### ISSUE TITLE
cooltools compute-saddle error : 'numpy.float64' object is not iterable

### ISSUE THREAD

**Issue by hiroyukikato911** [open2c/cooltools#326]
Hi,

Thanks for this wonderful tool!
I encountered problem when running

`cooltools compute-saddle A_100000_KR.cool A_100kb.txt A_100kb_KR_expected.tsv -o A100kb_saddle`

I converted .hic file using hic2cool.

My eigenvector "A_100kb.txt" file look like:

> chrom	start	end	E1
> 1	1	100000	0.007031937
> 1	100001	200000	0.005896139
> 1	200001	300000	0.005767067

My expected "A_100kb_KR_expected.tsv" file look like:

> region	diag	n_valid	balanced.avg
> 1	0	2493	nan
> 1	1	2492	nan
> 1	2	2491	870.0417833
> 1	3	2490	596.0763178

I'm running

> cooltools, version 0.4.1
> Python 3.6.8 :: Anaconda, Inc.
> numpy.version 1.19.1
> 

Thank you so much in advance.

Best regards,
Hiroyuki

**Comment by Phlya** [comment]
Hi, could you please provide more info, in particular the full error message that you got?

In general, however, files converted from .hic can cause problems unfortunately, and we don't really support them at this stage.

**Comment by hiroyukikato911** [comment]
Hi Phyla,

I appreciate your prompt response.

Here are my error messages:

> 
> INFO:numexpr.utils:NumExpr defaulting to 8 threads.
> /Users/hiroyukikato/opt/anaconda3/lib/python3.6/site-packages/numpy/lib/nanfunctions.py:1366: RuntimeWarning: Mean of empty slice
>   return np.nanmean(a, axis, out=out, keepdims=keepdims)
> Traceback (most recent call last):
>   File "/Users/hiroyukikato/opt/anaconda3/bin/cooltools", line 8, in <module>
>     sys.exit(cli())
>   File "/Users/hiroyukikato/opt/anaconda3/lib/python3.6/site-packages/click/core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "/Users/hiroyukikato/opt/anaconda3/lib/python3.6/site-packages/click/core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "/Users/hiroyukikato/opt/anaconda3/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/Users/hiroyukikato/opt/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/Users/hiroyukikato/opt/anaconda3/lib/python3.6/site-packages/click/core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "/Users/hiroyukikato/opt/anaconda3/lib/python3.6/site-packages/cooltools/cli/compute_saddle.py", line 405, in compute_saddle
>     lo, hi = saddle.quantile(track[track_name], qrange)
> TypeError: 'numpy.float64' object is not iterable
> 

Thank you so much in advance!

Best regards,
Hiroyuki

**Comment by gfudenberg** [comment]
Hi Hiroyuki, 

Please try updating to the latest cooltools==0.5.1, it should be working in the example notebooks: https://github.com/open2c/open2c_examples.

You will also need to re-compute expected to conform to the new format.
Let us know if that works!

**Comment by gfudenberg** [comment]
Closing for now, feel free to re-open if still an issue
