### ISSUE TITLE
phasing_track_col

### ISSUE THREAD

**Issue by labmike88** [open2c/cooltools#328]
Hi, since recently when using cooltools.eigs_cis, the phasing_track_col disappeared from the arguments and it gives an error when included. If not included the A/B compartments are flipped even when gc df is used as a phasing_track. Can you please have a look at it? Thanks! 

![image](https://user-images.githubusercontent.com/36769302/153529879-f80e0934-5c39-4deb-ac8c-38445746e163.png)

**Comment by gfudenberg** [comment]
Can you try passing a track dataFrame where the 4th column is the desired set of values for phasing (e.g. GC content)? The phasing_track_col argument is deprecated-- let us know if the docstring could use clarification. Sorry the open2c_examples are slightly behind the code, will hopefully update soon!

**Comment by labmike88** [comment]
Hi Geoffrey, thanks for replying so quickly! I have already tried to pass a df with the GC on the 4th column and there is no difference compared to when I use a df with only weights

**Comment by Phlya** [comment]
Can you please provide the exact code and first few lines of the dataframes you tried to use?

**Comment by agalitsyna** [comment]
Hi, @labike88, can you double-check that the 4th column if GC content? 

I see that in the example of open2c that you probably follow, GC is 5th after the weight column, and thus it is not parsed from the phasing_track table. 

I update the example in https://github.com/open2c/open2c_examples/blob/master/compartments_and_saddles.ipynb and also check the effect of phasing (see attached). Looks that it works as expected if appropriate phasing_track is passed. 
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/8100372/153619499-0d2dec88-38e4-46d9-9802-06e724b4a42e.png">

**Comment by gfudenberg** [comment]
After resolving some numpy/numba conflicts, the example notebooks (https://github.com/open2c/open2c_examples) run fine with the open2c enviornment.yml. Track should be a 4 column dataframe (e.g. with columns ['chrom','start','end','value']). The value column could be GC content, or anything else to use for phasing. Closing for now, but feel free to reopen if the issue persists--
Thanks!
