### ISSUE TITLE
in saddle allow regions to have all NA values in a track

### ISSUE THREAD

**Issue by sergpolly** [open2c/cooltools#330]
https://github.com/open2c/cooltools/blob/ac36a825027ca85ea8cedc2b540079cf521f13ef/cooltools/lib/common.py#L306

this happens when you try to run saddle on a chromosome arms view for human genome - some small acrocentric arms would have no data associated with them and it raises this error

just want to live here - to think if it too harsh and such regions could be simply ignored

**Comment by ehildebr** [comment]
I'm running into this issue as well - is there a quick way to filter a viewframe of chromosome arms made using bioframe to drop those regions (or not have them in the first place)? Filter based on cooler coverage or something? (maybe this is a bioframe question)

**Comment by gfudenberg** [comment]
sure! e.g.

```python

resolution = 1_000_000
clr = cooler.Cooler('test.mcool::resolutions/'+str(resolution))
bins = clr.bins()[:].copy()
bins['coverage'] = cooltools.coverage(clr)[1]

view_df = bioframe.make_viewframe(clr.chromsizes)
display(view_df)
view_coverage = bioframe.overlap(view_df, bins).groupby('name').sum('coverage_')
display(view_df.iloc[ bg['coverage_'].values > 1e7])
```

**Comment by Phlya** [comment]
@gfudenberg nice thing to add to bioframe examples/howto!

**Comment by gfudenberg** [comment]
sure! 
any suggestion for how to make more general-- or more elegant?
or expand into a tutorial for peaks?

**Comment by Phlya** [comment]
Yeah maybe just use peaks from some ChIP-seq instead of a coverage filter...

**Comment by ehildebr** [comment]
Thanks @gfudenberg and @Phlya! This is just what I was looking for.

**Comment by gfudenberg** [comment]
I think PR #360 resolves this, but feel free to re-open if not the case!
