### ISSUE TITLE
Cannot import name 'expected' from 'cooltools'

### ISSUE THREAD

**Issue by norouzis** [open2c/cooltools#332]
I am trying to run a scaling plot script. It throws this error: 

File "scaling_script_multiprocess.py", line 7, in <module>
    from cooltools import expected
ImportError: cannot import name 'expected' from 'cooltools' (~/anaconda3/lib/python3.8/site-packages/cooltools/__init__.py)

How to fix this?
Thank you
Davood

**Comment by agalitsyna** [comment]
Hi, it looks like the script you mention uses cooltools version 0.4.1 or lower, while you have cooltools version 0.5.0. With 0.5.0, you import API modules with: 
`from cooltools.api import expected`
You can change this specific line in your script. 
As an alternative, you might consider downgrading cooltools. See the [list of changes of 0.5.0 version](https://github.com/open2c/cooltools/releases/tag/v0.5.0).

**Comment by gfudenberg** [comment]
you can also check out the examples: https://github.com/open2c/open2c_examples & the environment provided there. Closing for now, but feel free to reopen
