### ISSUE TITLE
snipping.pair_sites is using bedtools

### ISSUE THREAD

**Issue by Phlya** [open2c/cooltools#338]
Let's switch it to bioframe.

**Comment by Phlya** [comment]
OK, actually it has been ported to bioframe already, and it's in bioframe itself!
https://github.com/open2c/bioframe/pull/57

Shall we remove it from snipping completely? Or just run bioframe under the hood, so people's code continues working?

**Comment by Phlya** [comment]
So the bioframe API is now quite different from the pair_sites in snipping, so I suggest we just remove it. OK?

**Comment by agalitsyna** [comment]
Yes, sounds good! `bioframe.pair_by_distance` is not simply diverged but more advanced (allows setting number of intervening regions, selecting endpoints or midpoints). I remember making sure it substitutes pair_sites in open2c_examples completely.

**Comment by Phlya** [comment]
Yes, indeed it has more features! OK, how about I just remove it in my PR here? https://github.com/open2c/cooltools/pull/339 Or do you think we should investigate more complicated solutions to that problem first?

**Comment by gfudenberg** [comment]
closed in #383
