### ISSUE TITLE
Insulation & boundaries tutorial - Error on the figure?

### ISSUE THREAD

**Issue by JSegueni** [open2c/cooltools#344]
Hi,
I'm trying to understand the figure showing the 1D pileup of CTCF enrichment at called boundaries.
It is the last figure here: https://cooltools.readthedocs.io/en/latest/notebooks/insulation_and_boundaries.html

I believe there is a mistake in the x axis tick labels ? Or do we have CTCF enrichment on 200kb around the boundaries ?
I think the labels should be divided by 10.

Best wishes,
Julie.

**Comment by JSegueni** [comment]
You're welcome!

Another puzzling aspect is the plot before this one. I believe all the boundaries plotted should be computed for the same window so that the plot makes more sense:

`histkwargs = dict(
    bins=10**np.linspace(-4,1,200),
    histtype='step',
    lw=2,
)
f, ax = plt.subplots()
ax.set(xscale='log', xlabel='Boundary strength')
ax.hist(
    boundaries[f'boundary_strength_{windows[0]}'][ctcf_chip_signal>=2],
    label='CTCF Chip/Input ≥ 2.0',
    **histkwargs
);
ax.hist(
    boundaries[f'boundary_strength_{windows[0]}'][ctcf_chip_signal<2],
    label='CTCF Chip/Input < 2.0',
    **histkwargs
);
ax.hist(
    boundaries[f'boundary_strength_{windows[0]}'],
    label='all boundaries',
    **histkwargs
);
ax.legend(loc='upper left')`

**Comment by Phlya** [comment]
Wow that also looks like a good catch!
