### ISSUE TITLE
cli random-sample/sample - is this with or without replacement?

### ISSUE THREAD

**Issue by ehildebr** [open2c/cooltools#357]
Hello, I have a question about how to best downsample cooler files so that all samples in an experiment have the same read depth. 

I have been using cooltools version 0.4.0, but I think this applies to newer versions as well. 

I thought that I could use what used to be cooltools random-sample (now cooltools sample), as the cli documentation for cooltools random-sample states that it will "Pick a random sample of contacts from a Hi-C map, w/o replacement." - which I thought meant 'without replacement'. 

However, is the 'without replacement' part true when --exact is not specified? In that case, it looks like it uses numpy.random.binomial to pick the contacts that will be in the sampled cooler - which I think might pick with replacement? (based on the numpy documentation comparing it to the hypergeometric distribution here: https://numpy.org/doc/stable/reference/random/generated/numpy.random.hypergeometric.html) 

In this case, it would be a very different kind of sampling. Instead of downsampling the reads to match between samples, it would be more like a random distribution based on the data - to test if the real data is different from the random sample. Both seem useful, but I just want to check which is actually happening with this function, and if it is picking WITH replacement when --exact is not specified, to suggest a change to the documentation. 

Thanks!

**Comment by golobor** [comment]
Hi, Erica!
yeah, that's a good catch!
Indeed, w/o --exact, we essentially get a sample of a random size (narrowly distributed around --count) but *with* replacement. With --exact, we get a sample of a fixed size, but sampled without replacement.
The difference between the two should not be substantial. Without --exact, some pixels in the sample may have higher counts than in the original cooler - but it's neither likely, nor should not affect any conclusions (as much as I can see).
@Phlya - could you correct us if we're wrong? I think you as well may have some experience with sample.py.
Anton

**Comment by Phlya** [comment]
Sorry, no, I don't think I have any experience beyond just running it.

**Comment by ehildebr** [comment]
@golobor Thanks for the info! 

So do you think the use cases are the same for either sampling method? 

I'm mainly using this to read normalize between samples from the same experiment, or across replicates - so they have pretty close read numbers to start, but I'm trying to make them more similar - so I am not usually downsampling by very much. For example, I might want to retain 90 or 95% of the interactions in the downsampled cooler. Would sampling with or without replacement make more of a difference in this case, then if I was only retaining a smaller percent (maybe 10%) of the interactions?

Also, would there be more differences between replicates of sampling if a dataset is sampled without --exact (with replacement) than using --exact (no replacement)? For read normalization, I would prefer to just downsample once for each dataset, rather than many times and calculating the average of all of the sampled datasets, so would using --exact be better in this case?

Thanks!

**Comment by golobor** [comment]
@ehildebr , thank you for the detailed description - indeed, in this case, i'd probably just recommend --exact!

**Comment by ehildebr** [comment]
Great - thank you!

**Comment by nvictus** [comment]
Closing as resolved. Please re-open if there are still issues.
