### ISSUE TITLE
Mask short-range interaction when plotting heatmap

### ISSUE THREAD

**Issue by Xieeeee** [open2c/cooltools#358]
Hi cooltools team,
Thanks for this great tool! I wonder whether it is possible to mask (what I mean is not showing) short range interactions (e.g. <1kb) when visualizing contact map? For some techniques there are quite abundant short range interactions thus there is extremely high diagonal signal. I wonder whether masking this diagonal could better scale the signal elsewhere.

Thanks,
Yang

**Comment by Phlya** [comment]
Hi Yang,

When plotting any heatmap, you can set the first two diagonals to 0 or np.nan, there is a useful function cooltools.lib.numutils.set_diag that will help you.
E.g. (untested):

```python
# arr is your array with data
for i in [-1, 0, 1]:
    set_diag(arr, 0, i)
```

**Comment by Xieeeee** [comment]
Gotcha, thanks so much!
