### ISSUE TITLE
cooltools saddle regions issue

### ISSUE THREAD

**Issue by Snehal1894** [open2c/cooltools#359]
I was trying to run saddle with EV cis and expected cis tracks.
I got the error "ValueError: no track values assigned to region chrM:0-16569"
So i manually removed chrM entries from EV track file and provided chr entries excluding chrm M using --view option.
But it still didnt work, since expected had chrM entries.

The saddle worked after redoing the expected using the updated --view file (no chr M).
So unlike mentioned in help "Analysis will be performed for chromosomes referred to in TRACK_PATH", looks like this script also depends on chromosomes in expected track.

**Comment by Phlya** [comment]
Ah I see, thanks! I'll check.

**Comment by gfudenberg** [comment]
closing, but feel free to reopen!
