### ISSUE TITLE
saddle script error

### ISSUE THREAD

**Issue by Snehal1894** [open2c/cooltools#361]
While generating saddle plots using command line with --vrange option, the script gave an error- 'variable **hi** referenced before assigned'.
The script was missing the hi/lo intialization for vrange.

adding the following lines of code in api/saddle.py resolved the issue.

if vrange is not None:
        lo, hi = vrange
        binedges = np.linspace(lo, hi, n_bins + 1)

**Comment by nvictus** [comment]
Are you still encountering this issue? The initialization seems to be there: https://github.com/open2c/cooltools/blob/master/cooltools/api/saddle.py#L230-L232.

**Comment by Snehal1894** [comment]
I added the vrange condition in saddleplot function after line 655, then the error was resolved.
In line 653 qrange assignes hi, lo; but for vrange these variables are not getting intitalized I suppose.

**Comment by gfudenberg** [comment]
closed in #361, with added test

**Comment by nvictus** [comment]
> I added the vrange condition in saddleplot function after line 655

Thank you! It indeed was missing in that case. Resolved.
