### ISSUE TITLE
Compartment calling tsv file extra entries 

### ISSUE THREAD

**Issue by Snehal1894** [open2c/cooltools#363]
The cis.vecs.tsv has rows for all the genomic regions but no EV values for regions not included in --regions file.

For example, if I have chr1-7 in regions.bed file, the cis.vecs.tsv has all chromosomes (chr1-22,X,Y,M) but EV entries only for chr1-7.
Had to manually remove extra entries to make this tsv file appropriate for running saddle scripts  for a subset of chromosomes (chr 1-7 in this case)

**Comment by nvictus** [comment]
Resolved by https://github.com/open2c/cooltools/pull/360
