### ISSUE TITLE
Is a pseudo bulk data obtained by merging 14 single cell data enough to call compartments??

### ISSUE THREAD

**Issue by tarak77** [open2c/cooltools#366]
Just curious- Is a pseudo bulk data obtained by merging 14 single cell data enough to call compartments??

**Comment by Phlya** [comment]
I'd be skeptical... How many contacts (e.g. cis over 1 kb) do you have in total?

**Comment by Phlya** [comment]
That's is very few contacts. You won't be able to call compartments on that data, sorry!

**Comment by Phlya** [comment]
I'd say at least in the millions... I don't know whether anyone has tried to find the minimum required number.

To downsample, you can use `cooltools random-sample` https://cooltools.readthedocs.io/en/latest/cli.html#cooltools-random-sample

**Comment by tarak77** [comment]
ok thanks

**Comment by tarak77** [comment]
sorry, I just use "wc -l" command on the terminal and I just mentioned these numbers as an approx. 
True values are like 44249,10308,21959,12679,34019,8650,8329,14423
I am trying to match all these for proper downstream analysis..

**Comment by Phlya** [comment]
Oh I see. You need to use cooler info, don't count lines with wc -l! Cooler is a binary format... And also, even if you dumped all pixels and then counted them, it's not the same as number of contacts.

**Comment by tarak77** [comment]
ah I see. I tried on one cool file and this is what i get
```
{
    "bin-size": 100000,
    "bin-type": "fixed",
    "creation-date": "2021-06-09T21:02:47.248031",
    "format": "HDF5::Cooler",
    "format-url": "https://github.com/mirnylab/cooler",
    "format-version": 3,
    "generated-by": "cooler-0.8.10",
    "genome-assembly": "unknown",
    "nbins": 27268,
    "nchroms": 21,
    "nnz": 7330240,
    "storage-mode": "symmetric-upper",
    "sum": 34981136
}
```

what line is the num of contacts?

**Comment by tarak77** [comment]
got it. and then i can use --count with --exact option in random-sample command for samples w/o replacement right?

**Comment by Phlya** [comment]
I believe so, but with or without replacement I am not 100% sure right now.

**Comment by tarak77** [comment]
okay

**Comment by tarak77** [comment]
Hey @Phlya , how to check if my random-sample has worked on a pseudo bulk cool file(of single cell HiCs)? meaning how to know that the samples I have now still show characteristics of my cell type. 
just trying to test how many contacts would be needed on a pseudo bulk file(of single cell HiCs) to call compartments?

**Comment by Phlya** [comment]
I'm not entirely sure I understand the question, but why don't you try to call compartments and compare the results to the bulk compartments?..

**Comment by tarak77** [comment]
It's not helping much though. None of the downsampled population data at many levels correlated with the pseudo bulk, even though they are the same cell type. 
I get a correlation of 0.95 only when I do not downsample any. 

btw any way to correlate just the .cool files? and not the compartment

**Comment by tarak77** [comment]
@Phlya I think calling compartments on random-sampled data is not properly done using cooltools?!
because unlike compartments when I just correlate the downsampled cool files with the original file using  _hicCorrelate_ function of _HiCExplorer_ I get what I would expect to see!

**Comment by Phlya** [comment]
Are you providing a phasing track when calling compartments? Some more info about what you do and what you get could be useful.

**Comment by tarak77** [comment]
yes, I do provide the same phasing track info to call compartments on the random-sampled data as I would for original data.

`cooltools eigs-cis --phasing-track gc_100kb.txt -o ./du_esc_comp_many_ds_100kb/$a $i`

Also attached is a figure showing correlations on population mouse ESC data from https://www.nature.com/articles/nature23263

<img width="1194" alt="Screen Shot 2022-07-18 at 5 49 16 PM" src="https://user-images.githubusercontent.com/32019333/179624366-3b810ac7-702d-4f9a-8f94-b96d2538bc01.png">

**Comment by Phlya** [comment]
Is "esc" the original data before downsampling? That is weird then... Can you compare the compartment tracks visually, what looks so suddenly changed between esc and 100e6 samples?

**Comment by tarak77** [comment]
yea need to check them visually later but is there a way I could share the cool files if you want to have a look at them?

**Comment by tarak77** [comment]
I think the issue is with the function change from `call-compartments` to `eigen-cis`. The files I have might have been called using these two functions and so the correlation was coming out to be nothing. But now I called them using `call-compartments` from older version of cooltools and it works fine.

**Comment by Phlya** [comment]
Very interesting. Have you managed to compare visually what the difference is?

**Comment by gfudenberg** [comment]
closing for now-- feel free to re-open if new related questions emerges!
