### ISSUE TITLE
check dtype for window_bp in calculate_insulation_score

### ISSUE THREAD

**Issue by Bo-UT** [open2c/cooltools#369]
Hi, 

I got issues when calculating insulation score. Looks like there are some conflicts in numpy. I updated the numpy, but the problem was not resolved. I also attached conda packages I used. Thank you!

Traceback (most recent call last):
  File "/rsrch4/home/genomic_med/bzhao2/pipelines/cooltools-pipeline/cooltools_compartment_boundary_loop.py", line 85, in <module>
    insulationscore = getinsulationscore()
  File "/rsrch4/home/genomic_med/bzhao2/pipelines/cooltools-pipeline/cooltools_compartment_boundary_loop.py", line 53, in getinsulationscore
    insulation_table = cooltools.insulation(clr, windows, verbose=True)
  File "/rsrch4/home/genomic_med/bzhao2/miniconda3/envs/cooltools/lib/python3.9/site-packages/cooltools/api/insulation.py", line 665, in insulation
    ins_table = calculate_insulation_score(
  File "/rsrch4/home/genomic_med/bzhao2/miniconda3/envs/cooltools/lib/python3.9/site-packages/cooltools/api/insulation.py", line 241, in calculate_insulation_score
    window_bins = window_bp // bin_size
TypeError: ufunc 'floor_divide' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
_libgcc_mutex=0.1=conda_forge
_openmp_mutex=4.5=2_gnu
asciitree=0.3.3=pypi_0
asttokens=2.0.5=pyhd8ed1ab_0
backcall=0.2.0=pyh9f0ad1d_0
backports=1.0=py_2
backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
bioframe=0.3.3=pypi_0
bottleneck=1.3.5=py39hd257fcd_0
bzip2=1.0.8=h7f98852_4
c-ares=1.18.1=h7f98852_0
ca-certificates=2022.6.15=ha878542_0
certifi=2022.6.15=pypi_0
charset-normalizer=2.1.0=pypi_0
click=8.1.3=pypi_0
cooler=0.8.11=pypi_0
cooltools=0.5.1=pypi_0
cycler=0.11.0=pypi_0
cython=0.29.30=py39h5a03fae_0
cytoolz=0.10.1=pypi_0
decorator=5.1.1=pyhd8ed1ab_0
dill=0.3.5.1=pypi_0
executing=0.8.3=pyhd8ed1ab_0
fonttools=4.34.4=pypi_0
h5py=3.7.0=pypi_0
idna=3.3=pypi_0
imageio=2.19.3=pypi_0
ipython=8.4.0=py39hf3d152e_0
jedi=0.18.1=py39hf3d152e_1
joblib=1.1.0=pyhd8ed1ab_0
keyutils=1.6.1=h166bdaf_0
kiwisolver=1.4.3=pypi_0
krb5=1.19.3=h3790be6_0
ld_impl_linux-64=2.36.1=hea4e1c9_2
libblas=3.9.0=15_linux64_openblas
libcblas=3.9.0=15_linux64_openblas
libcurl=7.83.1=h7bff187_0
libdeflate=1.10=h7f98852_0
libedit=3.1.20191231=he28a2e2_2
libev=4.33=h516909a_1
libffi=3.4.2=h7f98852_5
libgcc-ng=12.1.0=h8d9b700_16
libgfortran-ng=12.1.0=h69a702a_16
libgfortran5=12.1.0=hdcd56e2_16
libgomp=12.1.0=h8d9b700_16
liblapack=3.9.0=15_linux64_openblas
libnghttp2=1.47.0=h727a467_0
libnsl=2.0.0=h7f98852_0
libopenblas=0.3.20=pthreads_h78a6416_0
libssh2=1.10.0=ha56f1ee_2
libstdcxx-ng=12.1.0=ha89aaad_16
libuuid=2.32.1=h7f98852_1000
libzlib=1.2.12=h166bdaf_1
llvmlite=0.38.1=pypi_0
matplotlib=3.5.2=pypi_0
matplotlib-inline=0.1.3=pyhd8ed1ab_0
multiprocess=0.70.13=pypi_0
ncurses=6.3=h27087fc_1
networkx=2.8.4=pypi_0
nomkl=1.0=h5ca1d4c_0
numba=0.55.2=pypi_0
numexpr=2.8.0=py39h194a79d_102
numpy=1.22.4=py39hc58783e_0
openssl=1.1.1q=h166bdaf_0
packaging=21.3=pypi_0
pandas=1.4.2=py39h295c915_0
parso=0.8.3=pyhd8ed1ab_0
pexpect=4.8.0=pyh9f0ad1d_2
pickleshare=0.7.5=py_1003
pillow=9.2.0=pypi_0
pip=22.1.2=pyhd8ed1ab_0
prompt-toolkit=3.0.30=pyha770c72_0
ptyprocess=0.7.0=pyhd3deb0d_0
pure_eval=0.2.2=pyhd8ed1ab_0
pyfaidx=0.7.0=pypi_0
pygments=2.12.0=pyhd8ed1ab_0
pypairix=0.3.7=pypi_0
pyparsing=3.0.9=pypi_0
pysam=0.19.1=py39h5030a8b_0
python=3.9.13=h9a8a25e_0_cpython
python-dateutil=2.8.2=pyhd8ed1ab_0
python_abi=3.9=2_cp39
pytz=2022.1=pyhd8ed1ab_0
pywavelets=1.3.0=pypi_0
pyyaml=6.0=pypi_0
readline=8.1.2=h0f457ee_0
requests=2.28.1=pypi_0
scikit-image=0.19.3=pypi_0
scikit-learn=1.1.1=py39h4037b75_0
scipy=1.8.1=py39he49c0e8_0
setuptools=63.1.0=py39hf3d152e_0
simplejson=3.17.6=pypi_0
six=1.16.0=pyh6c4a22f_0
sqlite=3.39.0=h4ff8645_0
stack_data=0.3.0=pyhd8ed1ab_0
threadpoolctl=3.1.0=pyh8a188c0_0
tifffile=2022.5.4=pypi_0
tk=8.6.12=h27826a3_0
toolz=0.12.0=pypi_0
traitlets=5.3.0=pyhd8ed1ab_0
tzdata=2022a=h191b570_0
urllib3=1.26.10=pypi_0
wcwidth=0.2.5=pyh9f0ad1d_2
wheel=0.37.1=pyhd8ed1ab_0
xz=5.2.5=h516909a_1
zlib=1.2.12=h166bdaf_1

**Comment by nvictus** [comment]
Please check the dtype of your input variable `windows`. The error suggests that is not of a numeric type as expected.

**Comment by nvictus** [comment]
Better input validation is needed [here](https://github.com/open2c/cooltools/blob/c6b705d7aac895006efe797cb22da332793a7ae2/cooltools/api/insulation.py#L246).

Renaming the issue accordingly.
