### ISSUE TITLE
standardize the format for the "regions" kwarg in expected, eigdecomp and saddle.

### ISSUE THREAD

**Issue by golobor** [open2c/cooltools#37]
**Abstract:** 
in order to finalize the modules related to eigenvector decomposition, we need to agree on the format in which we specify genomic regions. 

**Intro:** 
All three cooltools (`expected`, `eigdecomp`, `saddle_plot`), when used in cis, can be limited to squares of a Hi-C map along the main diagonal that are smaller than the whole chromosome. This option is necessary because all three tools assume that contact frequency decays uniformly with genomic separation for all loci pairs. This assumption is violated when chromosome is split into segments and pairs of loci from different segments interact less/more often than expected given their distance  - e.g. chromosomal arms or major gaps in the genome assembly. That why the three tools accept the `regions` keyword argument that limits the analysis to the provided segments of the genome and ignores the contacts between different segments.

**Problem:**
Currently, different tools use different formats for the `regions` kwarg, which makes API non-intuitive. Moreover, the three tools should ideally be feeding one into another, such that the `regions` used by `expected` would then be used in `eigdecomp` and `saddle_plot`. (Note that, currently, eigdecomp re-calculates expected, which should be a subject of a separate GitHub issue).

**Details:**
- `expected`:
  - Python API input, [cis_expected](https://github.com/mirnylab/cooltools/blob/master/cooltools/expected.py#L292)
  accepts regions as a list of tuples or a Dataframe. The docstring is misleading - is doesn't specify DataFrames as a possible input and mentions strings, which are not processed properly in the code. The Dataframe for some reason expectes a mandatory field "name" that is not required in the tuple/string input.
  - Python API input, [trans_expected](https://github.com/mirnylab/cooltools/blob/master/cooltools/expected.py#L400)
   accepts a list of chromosomes, not regions. 
  - Python API input, multiple auxiliary functions
    use `supports` kwargs instead of `regions`, e.g. [make_diag_tables](https://github.com/mirnylab/cooltools/blob/master/cooltools/expected.py#L505). `supports` seems to be expected in a 3-tuple form.
  - Python API output, [cis_expected](https://github.com/mirnylab/cooltools/blob/master/cooltools/expected.py#L384):
    A dataframe, with columns that depend on the input. In both cases, the region is described by "chrom", but doesn't contain "start" or "end". If the "regions" were provided via a DataFrame, then the output column "name" is additionally provided. 
  - Python API output, [trans_expected](https://github.com/mirnylab/cooltools/blob/master/cooltools/expected.py#L400):
    A dataframe, indexed by columns "chrom1" and "chrom2".

  - CLI input,
  [expected](https://github.com/mirnylab/cooltools/blob/master/cooltools/cli/compute_expected.py#L66) does not accept `regions` in any form.
  - CLI output:
    A .csv file. For "cis", regions are indentified by "chrom"; in "trans", regions are identified by "chrom1" and "chrom2".

- `eigdecomp`:
  - Python API input, [cooler_cis_eig](https://github.com/mirnylab/cooltools/blob/master/cooltools/eigdecomp.py#L280)
    accepts regions in a form of strings or tuples (the conversion is delegated to bioframe).
  - Python API input, [cooler_trans_eig](https://github.com/mirnylab/cooltools/blob/master/cooltools/eigdecomp.py#L355) 
    takes a `partition` kwarg as a list of bin indices of chromsomes boundaries.
  - Python API output, [cooler_cis_eig](https://github.com/mirnylab/cooltools/blob/master/cooltools/eigdecomp.py#L345):  
    `eigvals` output table is indexed by a `region` column. `eigvecs` does not contain any information on the regions used in calculations.
  - Python API output, [cooler_trans_eig](https://github.com/mirnylab/cooltools/blob/master/cooltools/eigdecomp.py#L392):  
    not clear, most likely does not contain any information on regions.

  - CLI input:
    nether [cis](https://github.com/mirnylab/cooltools/blob/master/cooltools/cli/call_compartments.py#L142) nor trans accept `regions`.
  - CLI output:
    same as Python API outputs.

- saddle:
  - Python API input, [make_saddle](https://github.com/mirnylab/cooltools/blob/master/cooltools/saddle.py#L204)
    accepts `regions` in a format parseable by `bioframe`
  - Python API input, [make_cis_obsexp_fetcher](https://github.com/mirnylab/cooltools/blob/master/cooltools/saddle.py#L93)
    need an expected DataFrame with a "chrom" column; can only work with chromosome-wide expected.
  - Python API input, [make_trans_obsexp_fetcher](https://github.com/mirnylab/cooltools/blob/master/cooltools/saddle.py#L122)
    need an expected DataFrame with a "chrom1" and "chrom2" columns; can only work with chromosome-vs-chromsomes expected.

**Solution:**
Discuss! 

My proposal:

0. Rename "supports" and "partitions" to "regions".

1. Expect `regions` either in the form of (a) a list of UCSC-strings or (b) a list of 3-tuples or (c) a DataFrame with (chrom, start, end) columns (retire the "name" column). Never use bin indices.

2. Pick one format (say, DataFrames) to use internally in all functions. Delegate conversion between  to bioframe in _every_ function.

3. Add "region" column to eigenvector tables to keep track of which region each bin belonged to.

Extra suggestions that should become separate tickets:

4. Force "eigdecomp" to use externally computed expecteds.

5. Allow region-vs-region trans expecteds. In computations, check if region1[0] != region2[0].

6. Allow "linked" computations of expected that assume that all regions or all pairs of regions should have the same expected.

PS. Note that this partially spills over to the domain of `bioframe`. (a) bioframe is the place where we specify formats of data exchange; (b) bioframe's role is to provide convenience functions for conversion between formats.

**Comment by nvictus** [comment]
Let's start with an implementation of the parser that turns (a), (b), and (c) into a data frame. It could go into bioframe.

**Comment by golobor** [comment]
yes, this is a well-isolated to do. But it's not absolutely fundamental; we can also start modifying expected at the same time

**Comment by nvictus** [comment]
There's an additional semantics to `supports` that wasn't mentioned here. In `snipping`, rectangular snippet regions lying off the main diagonal can be assigned to **paired** support regions (e.g. snippets in trans):

https://github.com/mirnylab/cooltools/blob/master/cooltools/snipping.py#L79

**Comment by sergpolly** [comment]
to add `names` to the `diagsum/_assym` - `make_diag_table` would take another argument - `label`  or `name` .

As far as expected CLI is concerned - we should expose `regions` to input a BED file with labeled regions and use it (depending on the scenario - intra-arm, cis-inter-arm, trans of all sorts) to generate the expected output for the labeled regions or pairwise combinations of thereof

**Comment by golobor** [comment]
done!
