### ISSUE TITLE
cooltools command tutorial 

### ISSUE THREAD

**Issue by BioEpi** [open2c/cooltools#371]
Hello,
   Thanks for developing the great tool, cooltools. You have made the tutorial (https://cooltools.readthedocs.io/en/latest/index.html), would you like to make a similar tutorial running cooltools on command, not not notebooks?
That would be easy to use cooltools.
Best,

**Comment by Phlya** [comment]
Thank you for your suggestion, we are certainly planning to add similar notebook tutorials using CLI tools!

**Comment by gfudenberg** [comment]
See new docs added in commit
https://github.com/open2c/cooltools/commit/33e9711064f1282d819305dd96411a0052b66949

on https://cooltools.readthedocs.io/en/latest/notebooks/command_line_interface.html

Feel free to open a new issue with additional questions/suggestions!
