### ISSUE TITLE
random-sample counts cis/total

### ISSUE THREAD

**Issue by efriman** [open2c/cooltools#377]
Hi,

Just a few points that I noticed. Maybe there are good reasons for this but just wanted to point it out.

1. The "cis" counts (generated by cooltools coverage --store) are doubled, while the "sum" values are not. It seems for cooltools random-sample you need to use the doubled value with --counts-cis and the non-doubled value with --counts. This is a bit confusing.

2. After using cooltools random-sample, the cooler needs to be rebalanced but the weight column persists. This leads for example to the error "ValueError: Please, specify ignore_diags and/or IC balance this cooler! Cannot access the value used in IC balancing." when running cooltools coverage on the sampled (but not rebalanced) matrix and cooler balance says it's already balanced. Maybe it would be good to remove the weight column upon sampling.

Elias

**Comment by Phlya** [comment]
Indeed, 1 is a bug! Thanks for reporting.

2 is a good idea, we should simply remove the weights after sampling, I also think so.
