### ISSUE TITLE
Expected with integer chromosomes

### ISSUE THREAD

**Issue by efriman** [open2c/cooltools#384]
Hi,

I noticed if I have cooler with chromosomes named without "chr", i.e. 1,2,3 etc., I can generate an expected file that looks right but when I run cooltools.lib.io.read_expected_from_file it throws an error. If I do it in the API it works if I convert the region1 and region2 columns to str.

Elias

**Comment by gfudenberg** [comment]
@sergpolly should `read_expected_from_file` just used the dtype= kwarg for read_table before verifying? https://github.com/open2c/cooltools/blob/880a1487c66a404e88437fd697caf4cd91dc0004/cooltools/lib/io.py#L315

**Comment by gfudenberg** [comment]
closed with #404
