### ISSUE TITLE
'binedges' confused

### ISSUE THREAD

**Issue by BioEpi** [open2c/cooltools#396]
Hello,
   I ran this command to plot saddle plot: cooltools saddle **`--qrange 0.025 0.975 -n 38`**. 

`a=np.load("test_saddle.saddledump.npz",allow_pickle=True)`

 `a['saddledata'].shape`
(40, 40)

`len(a['binedges'])`
39

I am a little confused about a['saddledata'] and a['binedges'].
**how to determine which value in a['saddledata'] corresponds to BB/BA/AB/AA?** 
another question is the length of binedges is not 40, but 39. I do not understand that.

<img width="947" alt="image" src="https://user-images.githubusercontent.com/12387462/195119338-1c7fc745-8633-41df-b35a-35cce774c5f1.png">

**Comment by gfudenberg** [comment]
hi @BioEpi , thanks for the question!
The lowest and highest edge are +/- infinity, hence there are 39 specified binedges and 40 bins in the saddledata. The docstring for `digitize` has more information.

To determine which value in saddledata corresponds to BB/BA/AB/AA, this depends on the digitized track passed to the saddle function. If it is the eigenvector phased to GC content, then BB would be 0,0 and AA would be 39,39. There is some more info on https://cooltools.readthedocs.io/en/latest/notebooks/compartments_and_saddles.html#Saddleplots, about the red area in the upper left corner being low digitized values.  

Closing for now, but please reopen if more documentation would be helpful!
