### ISSUE TITLE
how to import cool data

### ISSUE THREAD

**Issue by jiangshan529** [open2c/cooltools#401]
Hi, I am using cooltools in jupyter notebook. How should I import my own data from my own path? I just saw "cooltools.download_data("HFF_MicroC", cache=True, data_dir=data_dir)".

**Comment by jiangshan529** [comment]
Ok, I found it. "cooler.Cooler("../4DNFI2TK7L2F_5k.cool")"

**Comment by Phlya** [comment]
`cooler.Cooler('file_path_to.cool')` will load the file
Note that if you have a multiresolution .mcool file, you have to specify which resolution you want to access, e.g. for 10,000 resolutions:
`cooler.Cooler('file_path_to.mcool::resoltutions/10000')`

**Comment by gfudenberg** [comment]
closing for now as this appears to be addressed, but feel free to reopen @jiangshan529  !
