### ISSUE TITLE
ModuleNotFoundError: No module named 'cooltools.expected'

### ISSUE THREAD

**Issue by PengfeiInTuebingen** [open2c/cooltools#403]
Hi, I am using this tool to calculate the contact P(s) curve, I met a problem like below:
from cooltools.expected import logbin_expected, diagsum, combine_binned_expected
import cooler
import matplotlib.pyplot as plt
import pandas as pd
import multiprocess
import bioframe
import pickle
from scipy.interpolate import interp1d

#cooler, version 0.8.10
#Python 3.7.9

ModuleNotFoundError                       Traceback (most recent call last)
Input In [39], in <cell line: 1>()
----> 1 from cooltools.expected import logbin_expected, diagsum, combine_binned_expected
      2 import cooler
      3 import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'cooltools.expected'
do you have any suggestions to solve this? 
Thanks in advance!
Best,
Pengfei

**Comment by Phlya** [comment]
Hi Pengfei,

Have you check the tutorial about it?
https://cooltools.readthedocs.io/en/latest/notebooks/contacts_vs_distance.html

Ilya

**Comment by PengfeiInTuebingen** [comment]
Hi Ilya, 
Thanks for your quick reply!
I checked the tutorial before, I want to do an analysis like this(https://github.com/dekkerlab/Zagelbaum_etal_NSMB_2022/blob/main/2022_scaling_from_cooler.ipynb), do you have any idea how to import diagsum ?
Best,
Pengfei

**Comment by Phlya** [comment]
I would follow the tutorial, we now have more user-friendly functions that would give you the same results. But if you want to follow that notebook, you can try changing the import to `from cooltools.api import expected`

**Comment by gfudenberg** [comment]
closing for now as this appears to be answered @PengfeiInTuebingen , but feel free to re-open!
