### ISSUE TITLE
Install ERROR: Could not find a version that satisfies the requirement bioframe>=0.3.3 

### ISSUE THREAD

**Issue by jiangshan529** [open2c/cooltools#409]
Hi, I am install cooltools to a conda environment(has Cpython in it), I installed in this way
`
git clone https://github.com/open2c/cooltools
cd cooltools
pip install -e ./
`
However, it said "ERROR: Could not find a version that satisfies the requirement bioframe>=0.3.3 (from cooltools) (from versions: 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.1.0, 0.2.0)
ERROR: No matching distribution found for bioframe>=0.3.3".

How to deal with this?

**Comment by gfudenberg** [comment]
Hi @jiangshan529, what version of python are you using?  you can see that bioframe 0.3.3 requires python3.7+ https://pypi.org/project/bioframe/

**Comment by gfudenberg** [comment]
closing for now as this was 3 weeks ago, but feel free to reopen!
