### ISSUE TITLE
IndexError: cooltools.dots() v0.5.2

### ISSUE THREAD

**Issue by Jiangyuan-Liu** [open2c/cooltools#410]
Hi, I got an IndexError message when I ran cooltools.dots() using v0.5.2 in conda env. Could you help me solve this problem? Thanks.

Jiangyuan

hg38_chromsizes = bioframe.fetch_chromsizes('hg38')
hg38_cens = bioframe.fetch_centromeres('hg38')
hg38_arms = bioframe.make_chromarms(hg38_chromsizes, hg38_cens)

clr = cooler.Cooler('file.mcool::resolutions/5000')
expected = cooltools.expected_cis(
    clr,
    view_df=hg38_arms,
    nproc=1,)

dots=cooltools.dots(
    clr,
    expected=expected,
    view_df=hg38_arms,
    max_loci_separation=10_000_000,
    max_nans_tolerated=4,
    clustering_radius=None,
    nproc=1,
)

INFO:root:Using recommended donut-based kernels with w=7, p=4 for binsize=5000
INFO:root: matrix 24696X24696 to be split into 625 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 25097X25097 to be split into 676 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 18628X18628 to be split into 361 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 29812X29812 to be split into 900 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 18443X18443 to be split into 361 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 21218X21218 to be split into 484 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 10146X10146 to be split into 121 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 27898X27898 to be split into 784 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 9655X9655 to be split into 100 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 26654X26654 to be split into 729 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 11839X11839 to be split into 144 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 22324X22324 to be split into 529 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 11970X11970 to be split into 144 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 19901X19901 to be split into 400 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 8992X8992 to be split into 81 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 20037X20037 to be split into 441 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 8891X8891 to be split into 81 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 18789X18789 to be split into 361 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 8129X8129 to be split into 81 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 18632X18632 to be split into 361 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 10551X10551 to be split into 121 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 16468X16468 to be split into 289 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 7196X7196 to be split into 64 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 19461X19461 to be split into 400 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 3406X3406 to be split into 16 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 19468X19468 to be split into 400 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 3418X3418 to be split into 16 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 17992X17992 to be split into 324 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 3681X3681 to be split into 16 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 16719X16719 to be split into 289 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 7458X7458 to be split into 64 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 10611X10611 to be split into 121 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 4943X4943 to be split into 25 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 11710X11710 to be split into 144 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 3633X3633 to be split into 16 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 12443X12443 to be split into 169 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 5169X5169 to be split into 36 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 6556X6556 to be split into 49 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 5648X5648 to be split into 36 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 7242X7242 to be split into 64 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 2379X2379 to be split into 9 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 6964X6964 to be split into 49 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 2801X2801 to be split into 9 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 7364X7364 to be split into 64 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 12102X12102 to be split into 169 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 19108X19108 to be split into 400 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 2087X2087 to be split into 9 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 9360X9360 to be split into 100 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root: matrix 4X4 to be split into 1 tiles of 1000X1000.
INFO:root: tiles are padded (width=7) to enable convolution near the edges
INFO:root:convolving 1776 tiles to build histograms for lambda-bins
INFO:root:fallback to serial implementation.
INFO:root:Done building histograms in 1625.377 sec ...
INFO:root:Determined thresholds for every lambda-bin ...
INFO:root:convolving 1776 tiles to extract enriched pixels
INFO:root:fallback to serial implementation.
Traceback (most recent call last):
  File "/home/jiangyuan.liu5-umw/miniconda3/envs/genomeinfodb-manual-versions2/lib/python3.8/site-packages/pandas/core/indexing.py", line 1587, in _get_list_axis
    return self.obj._take_with_is_copy(key, axis=axis)
  File "/home/jiangyuan.liu5-umw/miniconda3/envs/genomeinfodb-manual-versions2/lib/python3.8/site-packages/pandas/core/series.py", line 945, in _take_with_is_copy
    return self.take(indices=indices, axis=axis)
  File "/home/jiangyuan.liu5-umw/miniconda3/envs/genomeinfodb-manual-versions2/lib/python3.8/site-packages/pandas/core/series.py", line 930, in take
    new_index = self.index.take(indices)
  File "/home/jiangyuan.liu5-umw/miniconda3/envs/genomeinfodb-manual-versions2/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 1189, in take
    taken = values.take(
  File "/home/jiangyuan.liu5-umw/miniconda3/envs/genomeinfodb-manual-versions2/lib/python3.8/site-packages/pandas/core/arrays/interval.py", line 1081, in take
    left_take = take(
  File "/home/jiangyuan.liu5-umw/miniconda3/envs/genomeinfodb-manual-versions2/lib/python3.8/site-packages/pandas/core/algorithms.py", line 1573, in take
    result = arr.take(indices, axis=axis)
IndexError: index -9223372036854775808 is out of bounds for axis 0 with size 20

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jiangyuan.liu5-umw/projects/4DNII/notebooks/generate_enriched_pixels_and_clustering.py", line 323, in <module>
    dots=cooltools.dots(

**Comment by sergpolly** [comment]
similar issue has been recently fixed here https://github.com/open2c/cooltools/commit/d4518a1ec7e7cf25cf8a8ecc98d0a627cc2be90a

please use the latest unreleased code-base of cooltools from the "master" branch

closing for now - feel free to reopen if the issue persists

**Comment by nvictus** [comment]
@sergpolly Is this fix worth making a patch release?
