### ISSUE TITLE
cooltools is not compatible with cooler 0.9.0

### ISSUE THREAD

**Issue by JSegueni** [open2c/cooltools#413]
Hi everyone,

cooltools is not compatible with the newest version of cooler.

here are two jupyter notebooks executions with two different cooler versions

if cooler = 0.9.0, import of cooltools fails

**`import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

import cooler

from packaging import version
print(version.parse(cooler.__version__))

import cooltools.lib.plotting`**

`0.9.0

FutureWarning: The `cooler.tools` module is deprecated in v0.9 and will be removed in v0.10. Use `cooler.parallel` instead.
  from ._numutils import (

AttributeError                            Traceback (most recent call last)
Cell In[1], line 10
      7 from packaging import version
      8 print(version.parse(cooler.__version__))
---> 10 import cooltools.lib.plotting
     12 from cooltools import insulation

File ~/miniconda3/lib/python3.9/site-packages/cooltools/__init__.py:17
     14 __version__ = "0.5.0"
     16 from . import lib
---> 17 from .lib import (
     18     numutils,
     19     download_data,
     20     print_available_datasets,
     21     get_data_dir,
     22     download_file,
     23     get_md5sum,
     24 )
     26 from .api.expected import expected_cis, expected_trans
     27 from .api.coverage import coverage

File ~/miniconda3/lib/python3.9/site-packages/cooltools/lib/numutils.py:784
    779     report = {"converged": converged, "iternum": iternum}
    781     return _x, totalBias, totalBias2, report
--> 784 class LazyToeplitz(cooler.core._IndexingMixin):
    785     """
    786     A Toeplitz matrix can be represented with one row and one column.
    787     This lazy toeplitz object supports slice querying to construct dense
    788     matrices on the fly.
    789 
    790     """
    792     def __init__(self, c, r=None):

AttributeError: module 'cooler.core' has no attribute '_IndexingMixin'`

---------------------------------------------------------------------------------------------------------

if cooler = 0.8.11

**`import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

import cooler

from packaging import version
print(version.parse(cooler.__version__))

import cooltools.lib.plotting`**

`0.8.11`

The conda requirements of cooltools should thus be updated.

Best wishes.

**Comment by Phlya** [comment]
Thanks, the PR to pin cooler requirements <0.9 in the bioconda recipe was merged exactly 15 min ago!
https://github.com/bioconda/bioconda-recipes/pull/38928#event-8321754878

**Comment by JSegueni** [comment]
Perfect, thank you.
