### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by jiangyingru** [open2c/cooltools#426]
Hi， I am using pip install cooltools and appearing errors :

C:\Users\dell\AppData\Local\Temp\pip-build-env-s9uca34g\overlay\Lib\site-packages\numpy\core\include\numpy\npy_1_7_depre cated_api.h(14) : Warning Msg:  Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
cooltools/lib/_numutils.c(3534): warning C4244: "=" : Data may be lost when conversion from Py_ssize_t to int
cooltools/lib/_numutils.c(4467): warning C4244: "=" : Data may be lost when conversion from Py_ssize_t to int
cooltools/lib/_numutils.c(5653): warning C4244: = : Data may be lost if the system converts from npy_intp to int
cooltools/lib/_numutils.c(5707): warning C4013: "random" is not defined; Assume that the outside returns an int
cooltools/lib/_numutils.c(6055): warning C4244: = : indicates that data is converted from npy_intp to int
"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO  /LIBPATH:C:\Users\dell\AppData\Local\Programs\Python\Python310\libs  /LIBPATH:C:\Users\dell\AppData\Local\Programs\Python\Python310  /LIBPATH:C:\Users\dell\AppData\Local\Programs\Python\Python310\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft  Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\lib\x64" "/LIBPATH:C: Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C: Program Files (x86)\Windows Kits\10\lib\10.0.22000.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22000.0\\um\x64" /EXPORT:PyInit__numutils build\temp.win-amd64-cpython-310\Release\cooltools/lib/_numutils.obj  /OUT:build\lib.win-amd64-cpython-310\cooltools\lib\_numutils.cp310-win_amd64.pyd  /IMPLIB:build\temp.win-amd64-cpython-310\Release\cooltools/lib\_numutils.cp310-win_amd64.lib
Creating library build.temp.win -amd64-cpython-310\Release\cooltools/lib\_numutils.cp310-win_amd64.lib and object build\temp.win-amd64-cpython-310\Release\cooltools/lib\_numutils.cp310-win_amd64.exp
_numutils.obj: error LNK2001: external symbol random that cannot be resolved
build\lib.win-amd64-cpython-310\cooltools\lib\_numutils.cp310-win_amd64.pyd: fatal error LNK1120: 1 external command that cannot be resolved
error:  command 'C:\\Program Files (x86)\\Microsoft Visual  Studio\ 2022\ BuildTools\ VC\ Tools\ MSVC\ 14.35.32215\ bin\ HostX86\ x64\ link.exe' failed with exit code 1120
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for cooltools

Thank you for your help！！！

**Comment by gfudenberg** [comment]
I wonder if this is a numpy version conflict issue in your current environme. Perhaps you can try installing in a new conda environment?
We specify one that should work here:
https://github.com/open2c/open2c_examples/blob/master/environment.yml

**Comment by DavidWarrenKatz** [comment]
I have created a condo environment with the yml file above and I still am unable to import cool tools. Specifically, the command

         >>> import cooltools

produces the following error:

       ModuleNotFoundError: No module named 'cooltools.lib'; 'cooltools' is not a package

**Comment by gfudenberg** [comment]
With that error my guess would be that the open2c environment either wasn't activated, or wasn't installed correctly. You can check if this package was installed in your current environment with: conda list |grep cool

**Comment by gfudenberg** [comment]
closing for now, feel free to re-open if still an issue
