### ISSUE TITLE
pandas 2 incompatibilities

### ISSUE THREAD

**Issue by sergpolly** [open2c/cooltools#433]
https://github.com/open2c/cooltools/blob/67bc94d41b988d4442f483da80c6274e91bda164/tests/test_checks.py#L238

this assignment preserves `dtype` of the 1st column as `"object"` with pandas 2 - which could be explained by this deprecation warning visible with pandas 1.5.3:
```python
DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  track_incompat.iloc[:, 0] = 10
```

this causes test to fail, downstream ...

I think it could be practial to change `pandas>=1.5.1,<2` in the requirements for now - and go over those warnings to ensure comptability

**Comment by sergpolly** [comment]
to confirm - the latest tests ARE pulling pandas 2.0.0

**Comment by gfudenberg** [comment]
hmm, this is a pretty weird thing actually.. I guess we don't have a test for the case of numeric chrom column in bioframe, and we're not doing type checking in `bioframe.merge`

```
TypeError                                 Traceback (most recent call last)
Cell In[13], line 1
----> 1 cooltools.lib.is_track(track_incompat)

File ~/mambaforge/envs/open2c/lib/python3.9/site-packages/cooltools/lib/checks.py:544, in is_track(track, raise_errors)
    542     else:
    543         return False
--> 544 if bioframe.is_overlapping(track, cols=track.columns[:3]):
    545     if raise_errors:
    546         raise ValueError("track intervals must not be overlapping")

File ~/mambaforge/envs/open2c/lib/python3.9/site-packages/bioframe/core/checks.py:166, in is_overlapping(df, cols)
    162 from ..ops import merge
    164 ck1, sk1, ek1 = _get_default_colnames() if cols is None else cols
--> 166 df_merged = merge(df, cols=cols)
    168 total_interval_len = np.sum((df[ek1] - df[sk1]).values)
    169 total_interval_len_merged = np.sum((df_merged[ek1] - df_merged[sk1]).values)

File ~/mambaforge/envs/open2c/lib/python3.9/site-packages/bioframe/ops.py:775, in merge(df, min_dist, cols, on)
    772 clusters_group = {}
    773 for col in group_list:
    774     clusters_group[col] = pd.Series(
--> 775         data=np.full(n_clusters, group_keys[group_list.index(col)]),
    776         dtype=df[col].dtype,
    777     )
    778 clusters_group[sk] = cluster_starts_group
    779 clusters_group[ek] = cluster_ends_group

TypeError: 'int' object is not subscriptable
```

**Comment by sergpolly** [comment]
well cooltools  `is_track` checker was supposed to handle it on cooltools-side of things ...
i.e. is_Track was suuposed to give False , when there were numbers in the crom column - and it worked fine before - including the test

it's just with pandas 2  the assignment `track_incompat.iloc[:, 0] = 10`  got more nuanced - i.e. it tries to assign inplace now, and when you're assigning numbers over previous strings - your numbers inherit the dtype from strings "object" or whatever

But then later , somewhere deep inside bioframe , when you group by chroms - those strings/objects somehow get cast to Ints again  - or after some grouping by chromosomes `group_keys` becomes just a number `10` ...

And yes - this is true - we're lacking test currently for the genomes where they call chromosomes just `1,2,3,4, ...X,Y` - every now and then somebody tries to apply cooltools on such data and get weird crashes here and there ...

**Comment by gfudenberg** [comment]
yeah, and the current `bioframe.core.checks.is_bedframe` only throws an error if that column gets cast to int. Moreover, we were hoping to slim down on checks in bioframe to improve speed... 

if we just replace the offending line with:
```track_incompat.isetitem(0,10)```
It seems the test pass w/ pandas2.0

Is there anything else we'd need to change?
Other suggestions?

**Comment by sergpolly** [comment]
I'd try to go over all pandas warnings while on pandas<2 ...
 - There was at least one more annoying warning about groupby with 1-element sized lists, but I think @Phlya added a fix somewhere not sure
 - also I'd try go over such `df[:,smth] = smth` assignments to see if there will be issues in the future 

no other suggestions otherwise

**Comment by Phlya** [comment]
yes I have https://github.com/open2c/cooltools/pull/419/files

**Comment by sergpolly** [comment]
ok - but I'm afaraid this pattern could be a bit more widespread... i think i've seen it elsewhere - cannot recall
Maybe should track down some warning while running notebooks ?

**Comment by Phlya** [comment]
That's the only one I've seen, but it's an easy fix if we encounter it somewhere else.

**Comment by sergpolly** [comment]
i'd prefer doing it preemptively - and regarding pandas 2 in particular - imho it is a big release with lots of deprecations being fulfilled, so we could release cooltools with pandas<2 requirement and continue testing/prepraing for pandas=2

this is just imho though - mostly cause failing tests annoy me much

**Comment by sergpolly** [comment]
there is also python 3.11 itself - from a quick glance pandas and numpy already support it - also worth a try

**Comment by Phlya** [comment]
So far I am ignoring it and pinning all environments up to 3.10. I had problems with lots of things whenever conda pulled 3.11...

**Comment by gfudenberg** [comment]
shall we close this for now @sergpolly given the installation pinning?
