### ISSUE TITLE
Plotting difference between balanced matrices

### ISSUE THREAD

**Issue by atj31** [open2c/cooltools#441]
I wanted to ask for advice on plotting the difference between normalized matrices so that I can look at the differences between conditions in my data. Thank you!

**Comment by gfudenberg** [comment]
this might depend on what you are considering-- can you provide some more details of the goals of your analysis?

In general I'd recommend walking through all of the types of analyses covered in the docs for each dataset, as they might highlight a particular feature that changes between conditions (or perhaps nothing is highlighted and 3D genome folding is stable for the considered perturbation)
