### ISSUE TITLE
Aggregate_smoothed P(s) curve for Hi-C data without weight

### ISSUE THREAD

**Issue by divinomas** [open2c/cooltools#445]
We produced Hi-C-like data that should not be balanced as the matrix balance assumption is severely violated. 
Although smoothed Ps curve was made successfully, this unbalanced matrix could not be used to make an aggregate_smoothed  Ps curve due to the lack of weight.
So my questions are: Is there any easy way to aggregate the smoothed Ps curve data? Is there any API to manipulate the weight column of cooler.bins()?

**Comment by Phlya** [comment]
You were right, looks like at the moment aggregation is only implemented for balanced data... Which is not ideal.
Indeed, as a trick to let the code run, you can set all the weights of the cooler to 1.

```
import h5py
with h5py.File(clr_new.filename, 'r+') as fw:
    fw['bins']['weight'][:] = 1
```

**Comment by gfudenberg** [comment]
issue under consideration in https://github.com/open2c/cooltools/issues/456
