### ISSUE TITLE
How to make one heatmap plot for two conditions?

### ISSUE THREAD

**Issue by liufuyan2016** [open2c/cooltools#449]
Hi,
I want to draw heatmap as below. The heatmap  was showing two methods (one is Hi-C ,another is TAC-C) in one picture.
![image](https://github.com/deeptools/HiCExplorer/assets/23466455/6e76bd0d-46f3-4a7a-93fd-354c4847e632)
How to make it ? 
Thank you！

**Comment by gfudenberg** [comment]
hi, 
in matplotlib you can do this with plotting_function( np.triu(matrix1) + np.tril(matrix2)). You can also do this in higlass https://higlass.io/, but you'll need to read their docs!
