### ISSUE TITLE
Question about TAD regions from boundaries calling

### ISSUE THREAD

**Issue by FlavianR** [open2c/cooltools#453]
Hi! Thanks for this great tools!
I have a question conserning TAD regions. 
I generated with cooltools an insulation score and I found the differents boundaries but now I need to find the associated boundaries to create TAD regions (mostly for an differential analysis). 

Do you have an idea on how can i make it with your tools results ?

**Comment by Phlya** [comment]
Example of how to do it:
https://github.com/open2c/quaich/blob/e153a579a31f966968eb8c63a32aa6ff63c5a6e2/workflow/rules/insulation_tads.smk#L42

**Comment by FlavianR** [comment]
Thanks for the fast reply. I will try that
