### ISSUE TITLE
cooltools.pileup() returns unexpected ndarray dimensions

### ISSUE THREAD

**Issue by ddepierre** [open2c/cooltools#454]
Hi Open2C team, 

I am running cooltools tutorial. (https://cooltools.readthedocs.io/en/latest/notebooks/pileup_CTCF.html) - On-diagonal pileup of ICed Hi-C interactions

I think the way cooltools.pileup constructs the matrices' list (ndarray called stack) does not correspond to how dimensions are used thereafter.  Expected output in stack should follow [xPos, yPox, nSites], while pileup() returns   [nSites, xPos, yPox].

When I run:

```
 stack = cooltools.pileup(clr, sites, view_df=hg38_arms, flank=300_000)
# Mirror reflect snippets when the feature is on the opposite strand
mask = np.array(sites.strand == '-', dtype=bool)
stack[:, :, mask] = stack[::-1, ::-1, mask]

# Aggregate. Note that some pixels might be converted to NaNs after IC, thus we aggregate by nanmean:
mtx = np.nanmean(stack, axis=2)

```
 I have 
```

mtx.shape
(613, 61)


```
613 being the number of CTCF sites to plot pileup around.

I don't know where it comes from. but I had to modify those two lines as follow for it works:

```
stack[mask, :, :] = stack[mask, ::-1, ::-1]
mtx = np.nanmean(stack, axis=0)
mtx.shape
(61, 61)

```
Kind regards, 
David
```

>>> session_info.show()
-----
bbi                 0.3.5
bioframe            0.4.1
cooler              0.9.2
cooltools           0.5.4
matplotlib          3.7.2
numpy               1.24.4
pandas              1.5.3
pysam               0.21.0
scipy               1.11.1
seaborn             0.12.2
session_info        1.0.0
-----
Python 3.9.5 (default, Jun  4 2021, 12:28:51) [GCC 7.5.0]
Linux-5.3.18-150300.59.60-default-x86_64-with-glibc2.31
-----
Session information updated at 2023-07-18 15:40

```

**Comment by Phlya** [comment]
Thank you for the report! I am guessing you are using the version from github and not a released package? You are right, we recently changed the order of axes in the stack returned by pileup(). This change is recent and hasn't been included in any release... That's why the tutorial is not updated yet.

**Comment by Phlya** [comment]
I would guess you didn't downgrade the package to the released version correctly. The PR with the change was merged on the 12th of June, and the latest release on PyPI is from January 24th.

https://github.com/open2c/cooltools/pull/424/files#diff-e6563d802a721a3d9df4e7eb184dd15f0369015176abc788b07c06709830f1beR196

**Comment by Phlya** [comment]
If you pip install and the package is already installed, by default it does nothing. To be sure I add --upgrade --force-reinstall --no-deps (assuming dependencies have not changed).


No, cooltools pileup can only use regions of identical sizes. For rescaled pileups you can use coolpup.py.
