### ISSUE TITLE
cooltools.expected_cis(clr_weight_name = None) returns error asking for balanced data: smoothing breaks without a balanced column

### ISSUE THREAD

**Issue by ddepierre** [open2c/cooltools#456]
Hi, 
I am not sure to well understand how cooltools.expected_cis works.

I want to apply OE normalisation on unbalanced data, 
However, when I run 
`cooltools.expected_cis(unbalanced_cooler_cl, clr_weight_name = None, ignore_diags=0, view_df=gnm_arms,chunksize=1000000, nproc = nproc)`

with unbalanced_cooler_cl

`unbalanced_cooler_cl.bins()[:10]`
  chrom  start     end  weight
0  chr1      0   10000     NaN
1  chr1  10000   20000     NaN
2  chr1  20000   30000     NaN
3  chr1  30000   40000     NaN
4  chr1  40000   50000     NaN
5  chr1  50000   60000     NaN
6  chr1  60000   70000     NaN
7  chr1  70000   80000     NaN
8  chr1  80000   90000     NaN
9  chr1  90000  100000     NaN

`unbalanced_cooler_cl.pixels()[:10]`
   bin1_id  bin2_id  count
0      300      300      3
1      300   113084      1
2      300   113085      2
3      300   113090      1
4      300   154894      1
5      301      301      7
6      301      302      1
7      301      337      1
8      301     9164      1
9      302      302      3

I get an error as if expected_cis was looking for balanced data:
KeyError: "Column(s) ['balanced.sum'] do not exist"

Do I miss a step in which I should create a raw_count columns in unbalanced_cooler_cl.bins() for it can be used by expected_cis()?

Thanks
David

**Comment by Phlya** [comment]
I think the error comes from the attempt to smooth the expected. Can you try setting smooth=False, aggregate_smoothed=False?

**Comment by Phlya** [comment]
Actually it's a real issue we need to solve one way or another, so I'll keep it open, thanks for reporting!
