### ISSUE TITLE
How to visualise .cool files instead of .mcool

### ISSUE THREAD

**Issue by redjay8** [open2c/cooltools#457]
Hi,

Is it possible to visualise .cool files instead of .mcool files?

Thanks.

**Comment by Phlya** [comment]
What do you mean by visualizing? In HiGlass no, you have to create an mcool. To make a figure yourself using e.g. matplotlib, there is no difference...

**Comment by gfudenberg** [comment]
there is information in the tutorials on visualizing coolers with matplotlib, so you can start there as well: https://cooltools.readthedocs.io/en/latest/notebooks/viz.html#Inspecting-C-data
