### ISSUE TITLE
Balance = True flags an error

### ISSUE THREAD

**Issue by ratheraarif** [open2c/cooltools#461]
Hi,

I'm inexperienced in this area, and I apologize if my question appears naive.
When I try to run the following code it throws the following error. However, when I set `balance = False`, it works perfectly fine..

Note that I generated the mcool files from .hic data using the following code `hic2cool convert file1.allValidPairs.hic file2 -r 0  `

<img width="779" alt="image" src="https://github.com/open2c/cooltools/assets/46924431/116a85a9-d46b-4f04-b2cf-655cf7206f99">

<img width="558" alt="image" src="https://github.com/open2c/cooltools/assets/46924431/e2b2dc40-e6db-4cab-a44a-e16cdc4341ad">

**Comment by Phlya** [comment]
Since you converted from .hic, the balancing weights are not stored in the standard column called "weight". Try using `balance="KR"`, or whichever weight name you want from the .hic file.
Or you can rebalance the days using `cooler balance`.

**Comment by ratheraarif** [comment]
Thank you for the swift reply.. Will try this

**Comment by ratheraarif** [comment]
Setting `balance = 'KR'`  works fine. However, without the weight column I cant do the downstream analysis. Is there any other of generating mcool files while also retaining weight column. Or what is the standard practice of generating cool files.

**Comment by Phlya** [comment]
I think for all analyses you can specify the weight column, and you can set it to KR... where are you having problems?

You can generate a cooler tile using `cooler cload` or `cooler load`, depending on what you are starting with. Then you can balance it using `cooler balance`. If you want a multi resolution .mcool file, you can use `cooler zoomify`, and with the right arguments it can balance each resolution for you too. Please check documentation for the details of these commands.

**Comment by ratheraarif** [comment]
I am Executing the following code snippet and it requires the `weight column`
`# cvd == contacts-vs-distance
cvd = cooltools.expected_cis(
    clr=clr,
    view_df=hg38_arms,
    smooth=False,
    aggregate_smoothed=False,
    nproc=4 #if you do not have multiple cores available, set to 1
)`
Can you please  provide me with the exact code example to create an mcool file with weight column or generating a new mcool file from .hic data having the weight column

**Comment by ratheraarif** [comment]
One more niaive question! If I have to perform the exact analysis as listed in the cooltools tutorial in my study. How should I generate the mcool file from the hic data.. Kindly clarify it..

**Comment by gfudenberg** [comment]
Hi Aarif, 

the easiest way to get mcools is either by starting from .pairs files or from fastqs. You can check out distiller https://github.com/open2c/distiller-nf & pairtools https://github.com/open2c/pairtools for either of these options.

for cvd, you would likely be better off re-balancing matrices with cooler https://github.com/open2c/cooler, specifically https://cooler.readthedocs.io/en/latest/api.html#cooler.balance_cooler. 

closing this issue as the original question was resolved & these are more questions related to cooler, distiller, and pairtools

Hope this is helpful!
