### ISSUE TITLE
Error: No such command 'dump-cworld'.

### ISSUE THREAD

**Issue by songxh1996** [open2c/cooltools#463]
Hello,
I am trying to use the 'dump-cworld' function, but

> cooltools dump-cworld -h
> Error: No such command 'dump-cworld'.

I am trying to covert cool to ice  square matrix, how to do?

**Comment by gfudenberg** [comment]
hi-- dump-cworld was migrated to sandbox, as it was a specific use-case that is not actively maintained. Sergey Venev may be able to provide more info!

see this commit: https://github.com/open2c/cooltools/commit/904cff103760bcc2f2bddadaca6759c324e4c08e#diff-dbdcea1d082b4c4fb7d6d32c886d76b2a4a9bc35f2efe3a6314daf6e11b40af5
