### ISSUE TITLE
Bugs in decay curve tutorial

### ISSUE THREAD

**Issue by bskubi** [open2c/cooltools#470]
The cooltools decay curve plotting tutorial has you call make_chromarms as follows:

```
# Use bioframe to fetch the genomic features from the UCSC.
hg38_chromsizes = bioframe.fetch_chromsizes('hg38')
hg38_cens = bioframe.fetch_centromeres('hg38')
# create a view with chromosome arms using chromosome sizes and definition of centromeres
hg38_arms = bioframe.make_chromarms(hg38_chromsizes,  hg38_cens)
```

This results in an error as the make_chromarms function appears to expect a chromsizes df rather than series, with specific headers. This can be fixed by inserting after the fetch_chromsizes function:

```
hg38_chromsizes = pd.DataFrame({
    'chrom': hg38_chromsizes.index,
    'length': hg38_chromsizes.values
})
```

**Comment by sergpolly** [comment]
Closing, because , i believe it is the same issue as https://github.com/open2c/bioframe/issues/175 - and should have been addressed by a later version of bioframe
Feel free to reopen if this appears again
