### ISSUE TITLE
Saddle plot questions

### ISSUE THREAD

**Issue by zhanyinx** [open2c/cooltools#48]
Hi,

Thanks for making available this tool.

I have few questions:
1) is it possible to create saddle plot only on a subset of chromosomes? is it correct to use the regions option?
2) In case I have to use the 2nd eigenvector to call A/B compartment for a subset of chromosomes, how does the test code change? are also the 2nd/3rd etc.. eigenvector phased by phasing_track_col?
3) could it be possible to extract all the coordinates corrisponding to each bin in the saddle plot?

Thanks
Zhan

**Comment by sergpolly** [comment]
1. `regions` option is still under development/discussion, see https://github.com/mirnylab/cooltools/issues/37 , meanwhile you can control chromosomes included in a `saddle_plot` using compartment track - just keep chromosomes you need there, and remove ones you don't want to be included. It is described here: https://github.com/mirnylab/cooltools/blob/441a84ab6c1efd3bcd29de6cfd6ee78551873478/cooltools/cli/compute_saddle.py#L135
