### ISSUE TITLE
cooltools.dots runs under different conda environments

### ISSUE THREAD

**Issue by Jiangyuan-Liu** [open2c/cooltools#508]
Hi,

When I run the same python file (cooltools.dots function) under different conda envs, it works only in my routine env (more complex) but not in my new env (called unionloops-nf) using the below yml file. I confirmed that the versions of numpy, pandas, cooler, and cooltools are same as the versions in my routine env.
bsub < test.sh
I got this error (details in attached err file):
result = arr.take(indices, axis=axis)
IndexError: index -9223372036854775808 is out of bounds for axis 0 with size 21

```
name: unionloops-nf
channels:
  - anaconda
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy=1.21.2
  - pandas=1.5.2
  - cooler=0.9.3
  - cooltools=0.5.2
  - bioframe=0.3.3
  - r-essentials
  - r-base
  - r-dplyr
  - r-stringr
```

In my routine env, dis.err file looks fine as shown below.
INFO:root:Begin post-processing of 82088 filtered pixels
INFO:root:preparing to extract needed q-values ...

I do not know if the new env yml file still needs other extra packages or different versions of packages. Could anyone help me solve this problem? Thanks a lot.

Jiangyuan

[dist1.err.txt](https://github.com/open2c/cooltools/files/14487784/dist1.err.txt)
[generate_enriched_pixels.py.txt](https://github.com/open2c/cooltools/files/14487785/generate_enriched_pixels.py.txt)
[test.sh.txt](https://github.com/open2c/cooltools/files/14487786/test.sh.txt)

**Comment by nvictus** [comment]
The number you see indicates an unsafe casting of NaNs somewhere:

```python
>>> np.array([np.nan]).astype('int64')
array([-9223372036854775808])
```

```python
>>> np.array([np.nan]).astype('int64', casting="safe")
TypeError: Cannot cast array data from dtype('float64') to dtype('int64') according to the rule 'safe'
```

**Comment by nvictus** [comment]
@Jiangyuan-Liu this was fixed a while ago: https://github.com/open2c/cooltools/commit/eeac044de8583fde29cbaa281329e4bcd553ba99

Please use the latest version of cooltools.
