### ISSUE TITLE
dotfinder: searching for efficient dump for the scored pixels - cooler, hdf, parquet, etc.

### ISSUE THREAD

**Issue by sergpolly** [open2c/cooltools#51]
following efficiency conversation https://github.com/mirnylab/cooltools/issues/50 ...

- in the current implementation of `call-dots` , or `score_tile` function implementation rather, the resulting hdf5 dump is too large:
    - we calculate useless `p-vals` https://github.com/mirnylab/cooltools/blob/441a84ab6c1efd3bcd29de6cfd6ee78551873478/cooltools/cli/call_dots.py#L107
    - `annotate`-ing a dataframe with bin-ids leads to `chrom, start, stop`X2 columns, and all of the weights crippling in ...
    - reconsider if we need # of `NaN`-s in the footprint of EACH kernel  
    - `obs.raw` (`count` from cooler's `pixel` table), `exp.raw` - de-ICE-ed  global `expected`
 - either trim all of that down or add a `debug` option to output some of those columns for debugging only ...
 - dots-related hdf5 dump should be `~len(kernels)`X `sizeof(COOLER)`, sort of... - upper bound estimate ?!
 - what we really need is `locally-adjusted-expected` for each kernel and `bin_id1/2`, maybe number of NaNs in `kernels` footprint ...
 - consider `float32` instead of `float64` for  `locally-adjusted-expected` to save space

_Just to illustrate the problem_: a 10kb cooler of 720MB size lead to ~11GB(!) dots hdf5-dump, where `locally-adjusted-expected` was calculated only for pixels <=2Mbases away from the diagonal (loci not further than 2MB of each other) ...

I had too many "alternative" balancing weights, that crippled in with the `annotate`, here are the columns:
```python
Out[18]: 
Index(['chrom1', 'start1', 'end1', 'w11', 'w21', 'w31', 'w41', 'weight1',
       'chrom2', 'start2', 'end2', 'w12', 'w22', 'w32', 'w42', 'weight2',
       'la_exp.donut.value', 'la_exp.donut.nnans', 'la_exp.vertical.value',
       'la_exp.vertical.nnans', 'la_exp.horizontal.value',
       'la_exp.horizontal.nnans', 'la_exp.lowleft.value',
       'la_exp.lowleft.nnans', 'exp.raw', 'obs.raw', 'la_exp.donut.pval',
       'la_exp.vertical.pval', 'la_exp.horizontal.pval',
       'la_exp.lowleft.pval'],
      dtype='object')

```

**Comment by sergpolly** [comment]
after a brief review - it should be super easy to remove most of the columns, keeping only: `la_exp.KERNEL.value`, `obs.raw`, `binid_1`, `binid_2` ...
 - stop early `cooler.annotate`-ion
 - remove useless `pvals` (in favor of lambda-chunking)
 - `nnans` ?! remove for now at least ...
 - remove `exp.raw` - that's purely illustrational  

more stuff:
 - don't forget to `cooler.annotate` before `clustering/filtering` ...
 - check if there are any limits expressed in bases/nucleotides units - should be bins

**Comment by nvictus** [comment]
Btw, you should use `blosc` (even `blosc:zstd` or `blosc:lz4`) compression and a high `complevel` in `to_hdf()`. It can make a significant difference.

**Comment by sergpolly** [comment]
the problem with reading an hdf using `pandas.read_hdf` chunked - seems deeper ... i.e. I'm doing something wrong I guess.

I created a minimal example  here: https://github.com/sergpolly/test-chunk-hdf5

I'll try to ask around on stack-overflow , but if any of you guys know how to fix it - it would be great! @nvictus @mimakaev @golobor

**Comment by sergpolly** [comment]
I should try parquet, yes ...
But regardless, the problem seems ridiculous, right?! reading should be faster ...
I tried to explain it as best as I could here:
https://stackoverflow.com/questions/54426590/reading-chunks-of-hdf-file-using-pandas-read-hdf-takes-too-long

**Comment by golobor** [comment]
welp, that's why we never used builtin pandas-HDF5 interfaces... :)

**Comment by golobor** [comment]
actually, i believe that @nvictus must have a separate simple library for
interfacing pandas to HDF5!

**Comment by nvictus** [comment]
Another option would be to store the scores in new coolers. There is now full support for multiple value columns and datatypes.

**Comment by nvictus** [comment]
@golobor, work-in-progress...

**Comment by sergpolly** [comment]
@nvictus we've talked about doing it using coolers, yes ...

could you provide a small snipped of what it might look like ?

pandas is nice, cause API is nice/small/simple ... I really liked:
```python
for df_chunk in chunks:
    df_chunk.to_hdf/parquet(fname,some_nice_compression=True) 
```
on one side, and:
```python
for chunk in pandas.from_whatever(fname,iterator=True ...):
    minding_my_business(chunk)
```
on the other side ...

**Comment by nvictus** [comment]
It would looks something like:

```python
def chunk_generator():
    for df_chunk in chunks:
        yield chunk

columns = ['obs.raw', ...]
dtypes = {'obs.raw': np.int32, ...}
cooler.create_cooler(fname, bins, chunk_generator(), columns=columns, dtypes=dtypes, ...)
```

I believe it still requires an input column be named "count". You could use it for obs.raw. Eventually, I want to drop the requirement.

```python
score_clr = cooler.Cooler(fname)
selector = score_clr.pixels(join=True) 
spans = cooler.util.partition(0, len(selector), chunksize)
for lo, hi in spans:
    chunk = selector[lo:hi]
    minding_your_business(chunk)
```
The beauty of iterating over spans instead of chunks is that the spans can be farmed out to workers for parallelization, where the actual chunk extraction can take place. e.g., doing a parallel pool.map over the chunks themselves will lead to the overhead cost of serializing/transporting/deserializing the dataframes to the worker processes.

**Comment by sergpolly** [comment]
so, right now with this implementation  https://github.com/mirnylab/cooltools/pull/58
and the code around this comment: https://github.com/mirnylab/cooltools/pull/58/commits/1b22279030641350ed1aeea079a2770d7b3284e3#r253247691

I'm getting an `.hdf` of 15GB in ~2:47 minutes, and
a `.cool` of 6.5GB in ~9:30 minutes

for cool output run
```
cooltools call-dots -n cores \
    -o MEANINGLESS_STR -v --fdr MEANINGLESS_FLOAT \
    --max-nans-tolerated 11 \
    --max-loci-separation 10000000 \
    --dots-clustering-radius MEANINGLESS_INT \
    --tile-size 10000000 \
    --score-dump-mode cooler\
    -s output.cool \
    input.cool input.expected.tsv
```

for hdf output run:
```
cooltools call-dots -n cores \
    -o MEANINGLESS_STR -v --fdr MEANINGLESS_FLOAT \
    --max-nans-tolerated 11 \
    --max-loci-separation 10000000 \
    --dots-clustering-radius MEANINGLESS_INT \
    --tile-size 10000000 \
    --score-dump-mode hdf\
    -s output.hdf \
    input.cool input.expected.tsv
```

`MEANINGLES_XXX`- because I terminate the dot-calling after the dump of scores to hdf/cooler/parquet ...

**Comment by sergpolly** [comment]
Prelim reading tests, just simple sequential stuff calculating mean value in one of the columns, as suggested by @nvictus :
```python
import cooler
fname = "test_scores4_U54-H1ESC4DN-FA-DSG-MNase_hg19.10000.hdf"
chunksize = 10000000
score_clr = cooler.Cooler(fname)
selector = score_clr.pixels(join=False)
spans = cooler.util.partition(0, len(selector), chunksize)
dmd = []
for lo, hi in spans:
    chunk = selector[lo:hi]
    dmi = chunk['la_exp.donut.value'].mean()
    dmd.append(dmi)
```

Takes 1:32 minutes ! with `chunksize=10'000'000`
takes 1:36 minutes with `chunksize=1'000'000`
which is great!

But I have a question - where is multithreading is coming from here ?! with small chunks it was ~970% cpu usage and larger chunks had ~240% cpu usage .... - and it's not about `numpy`, as I've tried these flags https://github.com/mirnylab/distiller-nf/issues/128

**Comment by golobor** [comment]
Maybe multi threading is used in data decompressing?

Anton.
(typed on a phone, sorry for brevity and typos)

**Comment by sergpolly** [comment]
I think you're right @golobor  - I was just surprised to see that - I had a dejavu of the https://github.com/mirnylab/distiller-nf/issues/128 , where it felt like, I'm not in control on how many cores/resources the programm is using ....

Anyways , seems like I f-ed up the cooler output - i.e. I assumed it's ordered, while it seems like it's not https://github.com/mirnylab/cooltools/pull/58/files/71d428eefe5ac4ef22f7aa23af0873ad69a0d8ad..1b22279030641350ed1aeea079a2770d7b3284e3#r253315723

https://github.com/dekkerlab/cooltools/blob/54359225c188c1b702b7a25d17f0abffed5a3f65/cooltools/dotfinder.py#L1062
`multiprocess.pool.imap` returns results out of order, doesn't it ?
Also not sure if tiles are returned in order or not https://github.com/dekkerlab/cooltools/blob/54359225c188c1b702b7a25d17f0abffed5a3f65/cooltools/cli/call_dots.py#L229


that's the kind of output I'm getting from my convolution score calculation ...
![xxx](https://user-images.githubusercontent.com/6790270/52181500-b2e3fa00-27c0-11e9-9316-ade1a26db16e.png)

Missing squares, made me think ordered assumption was a complete mess ...
100% my idiocy.

.................
However, while trying to figure it all out, seems like found an inconsistent cooler api descritpion, tried to document it here in details :
https://github.com/mirnylab/cooler/issues/149

**Comment by nvictus** [comment]
> multiprocess.pool.imap returns results out of order, doesn't it ?
Also not sure if tiles are returned in order or not 

I believe imap does return things in order. It does so asynchronously, as soon as the next thing is available. I suspect the tiles are not generated in the required order.

The requirement of a "count" column is annoying. I'll see if I can fix that. You can get around it for now by adding one...

**Comment by sergpolly** [comment]
yep! added `count`- cooler got fixed!
looks "normal" now:
![zzz](https://user-images.githubusercontent.com/6790270/52182386-a6649f00-27ca-11e9-9ca2-4997ffe56eb4.png)

resulted `cooler` is still 6.5GB, but it takes forever to generate one ... ~40 mins with all of the merges ...

Still super valuable, since I can easily plot the map of the "convolution" scores, check this out (maps are not matching, but it's close, region on the inset is `chr4:109,000,000-112,000,000`):
![screenshot from 2019-02-03 15-43-26](https://user-images.githubusercontent.com/6790270/52182420-078c7280-27cb-11e9-9358-6e1f232ea832.png)


Given this observations, I feel like cooler-dump would be great for debugging/visualization only - it would be too slow for debugging the convolution - 40 mins to regenerate is a bit slow ...

Might be good for debugging the "post-processing", i.e. building histograms, etc. - since reading `cooler` is plenty fast.

[todo]
so it's between "plain" hdf and parquet now I guess ...
try @nvictus suggestion on reading pytables hdf:
![screenshot from 2019-02-03 15-55-53](https://user-images.githubusercontent.com/6790270/52182580-774f2d00-27cc-11e9-99e5-ecd9716be1a7.png)

**Comment by nvictus** [comment]
Sounds good. Though I suspect the merge time is slow because the chunks you are feeding  to`cooler_create` are small.

**Comment by sergpolly** [comment]
more things to try:

1. parquet chunked reading by @nvictus :
https://github.com/apache/arrow/blob/master/python/pyarrow/parquet.py#L1100
```python
for i in range(pf.num_row_groups):
    chunk = pf.read_row_group(i)
```

2. see if something can be done about `kwargs` in pandas API `to_parquet` and `read_parquet`

3. @nvictus is suggesting that the chunks that we generate in call_dots are too small (~0.5 million) , thus we can buffer them for `cooler`-dump:
![2019-02-03](https://user-images.githubusercontent.com/6790270/52183036-eb400400-27d1-11e9-9157-fe40dce63527.png)
i.e. we should be able to squeeze more performance from `cooler` itself ... - still super useful.

**Comment by sergpolly** [comment]
4. want to emphasize importance of the `cooler` dump again - the ease of visual output would enable us to tune future "kernels" for different use case, like stripes-calling etc. Also adjusting "donuts" and such for finer resolutions

**Comment by sergpolly** [comment]
More weird stuff:
```python
cooler output ...
Traceback (most recent call last):
  File "/home/venevs/miniconda3/envs/dots-latest/bin/cooltools", line 11, in <module>
    sys.exit(cli())
  File "/home/venevs/miniconda3/envs/dots-latest/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/venevs/miniconda3/envs/dots-latest/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/venevs/miniconda3/envs/dots-latest/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/venevs/miniconda3/envs/dots-latest/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/venevs/miniconda3/envs/dots-latest/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/venevs/miniconda3/envs/dots-latest/lib/python3.6/site-packages/cooltools/cli/call_dots.py", line 246, in call_dots
    nproc, score_dump_mode, verbose)
  File "/home/venevs/miniconda3/envs/dots-latest/lib/python3.6/site-packages/cooltools/dotfinder.py", line 1150, in scoring_step
    mode = 'w')
  File "/home/venevs/miniconda3/envs/dots-latest/lib/python3.6/site-packages/cooler/create/_create.py", line 921, in create_cooler
    max_merge=max_merge)
  File "/home/venevs/miniconda3/envs/dots-latest/lib/python3.6/site-packages/cooler/create/_create.py", line 632, in create_from_unordered
    columns=columns, dtypes=dtypes, mode='a', **kwargs)
  File "/home/venevs/miniconda3/envs/dots-latest/lib/python3.6/site-packages/cooler/create/_create.py", line 565, in create
    file_path, target, meta.columns, iterable, h5opts, lock)
  File "/home/venevs/miniconda3/envs/dots-latest/lib/python3.6/site-packages/cooler/create/_create.py", line 204, in write_pixels
    for i, chunk in enumerate(iterable):
  File "/home/venevs/miniconda3/envs/dots-latest/lib/python3.6/site-packages/cooler/create/_ingest.py", line 307, in _validate_pixels
    raise BadInputError("Found duplicate pixels:\n{}".format(err.head().to_csv(sep='\t')))
cooler.create._ingest.BadInputError: Found duplicate pixels:
	bin1_id	bin2_id	count	la_exp.donut.value	la_exp.vertical.value	la_exp.horizontal.value	la_exp.lowleft.value
75	76	999	0	0.039334712950361124	0.02985299926634868	0.18436449063546803	0.0679983868254756
76	76	1000	0	0.08116557025783917	0.0	0.1444649071338037	0.07124153316898331
152	77	999	0	0.05743539640390035	0.03396130943199788	0.17071727978971427	0.0779715844835965
153	77	1000	0	0.09102873515462423	0.0	0.11910133333345246	0.08039903033544311
230	78	999	0	0.06473282768473614	0.018054547860104672	0.0799101745120326	0.0745334029293596

bash latest_pipe_dots.sh ESC-R1 U54-H1ESC4DN-FA-DSG-MNase_hg19 8  688.31s user 114.51s system 999% cpu 1:20.28 total

```

**Comment by sergpolly** [comment]
1. parquet is fast!
   - using threads:
![screenshot from 2019-02-05 18-59-24](https://user-images.githubusercontent.com/6790270/52312456-9a1e4480-2978-11e9-9cc8-1a5e49b3e43b.png)
   - not using threads - still used a LOT of threads and was of course fast.... not sure how to force it to limit resources usage
![screenshot from 2019-02-05 19-04-28](https://user-images.githubusercontent.com/6790270/52312555-f08b8300-2978-11e9-9916-379f085bad57.png)
   - but how one would control this `num_row_groups: 588` - it's not the way I've written it , close but not quite ? or is it just the format specific thing that user cannot control ? is it always guaranteed to be small enough to fit the RAM? unclear for now.
   - is it the only way to read a `parquet` file in pieces - using `row-groups` ?

...
[todo] still need to try proper hdf:
![screenshot from 2019-02-05 19-09-00](https://user-images.githubusercontent.com/6790270/52312743-a787fe80-2979-11e9-9c75-074e6b9ab318.png)

**Comment by sergpolly** [comment]
after trying to use `parquet` in the `onepass-dots` branch for a while it seems like the whole idea of storing intermediate `DataFrame` of `"enrichment"/adjusted-expected` scores is not immediately applicable:
 - I made it to work with the `parquet` intermediates:
     - it is ok space-usage wise for medium-resolution (~10kb, 10MB near diagonal) dot-calling
     - it is slower, but ok performance wise as well (1 time parquet writing, 2 times reading it - histograms and extracting pixels)
 - For higher resolution datasets (5kb, 10MB near-diagonal) bunch of problems pop up:
     1. pickling/dilling: serializing huge DataFrame to be stored in parquet breaks, see #50 for details
     2. the size of an intermediate file grows a lot ~>30GB for 5kb  - not great ...
     3. performance degradation because of 1-2 is a bit too much: reading huge parquet 2 times ...

Thoughts/solutions for future:
 - intemediate `DataFrame` should be ~ corresponding cooler size (10MB around diagonal), but:
     - it seems less sparse: less "zeros" because `adjusted-expected` is the result of "smoothing" of sorts ...
     - cooler stores just 3 integer columns, this `DF` should carry those 3 columns + NUM_KERNELS*`float64` columns as well
 - are `floats` harder to compress ?  NUM_KERNELS is ~4 columns - it is something - for sure
 - Instead of outputting `adjusted-expected` we could output indices of corresponding lambda-chunks (small and repetitive integers - better compression) - better histogramming downstream ? maybe ...
 - we could write a LOT of `parquet` files directly from each `job`, for each `tile`  - thus avoiding pickling issues - storage amount would still be an issue. - how to proceed with this ton of small `parquet`-s ?! could we append to one in parallel ?
 - reading intermediate 2-times for histogramms and then for extracting significant pixels is also not great - we could build histogramms along with `scoring` - but that already seems a lot like the 2-pass solution again ...

Given all of that , it seems that going back to 2-pass `adjusted-expected` scores calculations would be the easiest solution - at least for now.
 - no pickling issues - we are not passing or returning objects `~total_number_of_pixels` - passing histogramms and pruned lists of pixels only !
- no storage issues
- overall it was much faster
- ...

With that said `onepass-dots` should not go to trash-can:
 - useful code-refactoring
 - educational/demonstrational purposes ! - notebook to be added
 - ...

**Comment by golobor** [comment]
@sergpolly  - we could move this one to the discussions? (tag: Ideas)
