### ISSUE TITLE
Issue with scoring_and_histogramming_step: ValueError: There are la_exp.donut.value in (8192.0, inf], please check the histogram

### ISSUE THREAD

**Issue by satvikgunjala** [open2c/cooltools#511]
Hello, I am relatively new to Hi-C analysis. I am currently attempting to use the dots() function as utilized in https://github.com/open2c/open2c_examples/blob/master/dots.ipynb to identify enriched points in the Hi-C contact matrix. For most of the .mcool contact matricies I am using, I am able to obtain the dataframe. However, for certain .mcool files, I encountered this error:

<img width="958" alt="Screenshot 2024-03-28 at 4 07 52 AM" src="https://github.com/open2c/cooltools/assets/32466133/10db82bf-1a17-47ff-84ab-d55a1bbdac0d">

Could someone explain what this error means and how do I fix it  or get around it?

**Comment by gfudenberg** [comment]
it looks like there might be an issue with the dataframe of `expected` passed to dots(). If you share the function call that may provide some more insight

**Comment by satvikgunjala** [comment]
This is the code that I used based on the example from https://github.com/open2c/open2c_examples/blob/master/dots.ipynb:


```python

import pandas as pd
import numpy as np
from itertools import chain
import os

# Hi-C utilities imports: 
import cooler
import bioframe
import cooltools
from cooltools.lib.numutils import fill_diag
from packaging import version
if version.parse(cooltools.__version__) < version.parse('0.5.2'):
    raise AssertionError("tutorials rely on cooltools version 0.5.2 or higher,"+
                         "please check your cooltools version and update to the latest")

# Visualization imports: 
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm
import matplotlib.patches as patches
from matplotlib.ticker import EngFormatter

# helper functions for plotting
bp_formatter = EngFormatter('b')
def format_ticks(ax, x=True, y=True, rotate=True):
    """format ticks with genomic coordinates as human readable"""
    if y:
        ax.yaxis.set_major_formatter(bp_formatter)
    if x:
        ax.xaxis.set_major_formatter(bp_formatter)
        ax.xaxis.tick_bottom()
    if rotate:
        ax.tick_params(axis='x',rotation=45)

# define genomic view that will be used to call dots and pre-compute expected

# Use bioframe to fetch the genomic features from the UCSC.
hg38_chromsizes = bioframe.fetch_chromsizes('hg38')
hg38_cens = bioframe.fetch_centromeres('hg38')
hg38_arms = bioframe.make_chromarms(hg38_chromsizes, hg38_cens)

# Set directory where matricies are located
data_dir = './data/Matricies'

matricies = os.listdir(data_dir)

mcools = []
for x in matricies:
    if x.endswith(".mcool"):
        mcools.append(x)

# 10 kb is a resolution at which one can clearly see "dots":
binsize = 10_000

for y in mcools:

    # Open cool file with Micro-C data:
    clr = cooler.Cooler(f'{data_dir}/{y}::/resolutions/{binsize}')

    # Select only chromosomes that are present in the cooler. 
    hg38_arms = hg38_arms.set_index("chrom").loc[clr.chromnames].reset_index()

    # intra-arm expected
    expected = cooltools.expected_cis(
        clr,
        view_df=hg38_arms,
        nproc=4,
    )

    print(f'Processing: {y}')
    
    dots_df = cooltools.dots(
        clr,
        expected=expected,
        view_df=hg38_arms,
        # how far from the main diagonal to call dots:
        max_loci_separation=10_000_000,
        nproc=4,
    )

    y_name = y.replace(".mcool","")
    dots_df.to_csv(r'./data/Loops/'+f'{y_name}.csv')

```

**Comment by gfudenberg** [comment]
@satvikgunjala 
if you run cooltools.expected_cis with kwarg `clr_weight_name=None` can you send the resulting plot? It would be useful to know at what distance does the average number of counts drop below 1.



(for reference about contacts vs distance you can check out:
https://cooltools.readthedocs.io/en/latest/notebooks/contacts_vs_distance.html#Impact-of-sequencing-depth-on-computed-P(s))

**Comment by ieres-amgen** [comment]
I am encountering the exact same issue with some data I am trying to analyze at 10kb resolution. I found that changing the max_loci_separation made no difference. I've attached a visualizations that I made with the below custom code, please let me know if there is a different way I could help visualize so we can solve this issue.

![Image](https://github.com/user-attachments/assets/c2c24a02-4648-40c2-b884-a7e1aeaed108)

    def loop_troubleshooter(basepath, sampID, resolution):
      if resolution <= 4000:
          mykerns=cooltools.api.dotfinder.recommend_kernels(4000) #Can't recommend a good kernel size for lower than this anyway
      elif resolution > 4000:
          mykerns = cooltools.api.dotfinder.recommend_kernels(resolution)
          
      mycooler = cooler.Cooler(f'{basepath}/{sampID}/cool/{sampID}.{resolution}_balanced.cool')
      myexp = cooltools.expected_cis(mycooler, view_df=hg38_arms[:46], nproc=num_cpus) #Note need to restrict hg38 arms to exclude Y and M, these were messing up loop calling.
      myexp_raw = cooltools.expected_cis(mycooler, view_df=hg38_arms[:46], nproc=num_cpus, clr_weight_name=None)
      
      plt.figure(figsize=(8,6))
      plt.plot(myexp['dist'], myexp['count.avg'], label='IC Norm Expected Contact Count')
      plt.axhline(1, color='red', linestyle='--', label='1 count threshold')
      plt.xscale('log')
      plt.yscale('log')
      plt.xlabel('Genomic distance (bp)')
      plt.ylabel('Average number of contacts')
      plt.title('Expected Contact Frequency vs Genomic Distance')
      plt.legend()
      plt.gca().xaxis.set_major_formatter(EngFormatter('b'))
      plt.savefig(f'{basepath}/FIGS/{sampID}_NormHist_{resolution}.png', dpi=300, bbox_inches="tight")
      plt.close()
      
      plt.figure(figsize=(8,6))
      plt.plot(myexp_raw['dist'], myexp_raw['count.avg'], label='Raw Expected Contact Count')
      plt.axhline(1, color='red', linestyle='--', label='1 count threshold')
      plt.xscale('log')
      plt.yscale('log')
      plt.xlabel('Genomic distance (bp)')
      plt.ylabel('Average number of contacts')
      plt.title('Expected Contact Frequency vs Genomic Distance')
      plt.legend()
      plt.gca().xaxis.set_major_formatter(EngFormatter('b'))
      plt.savefig(f'{basepath}/FIGS/{sampID}_RawHist_{resolution}.png', dpi=300, bbox_inches="tight")
      plt.close()
      
      os.makedirs(f'{basepath}/loops/', exist_ok=True)

**Comment by ieres-amgen** [comment]
Current dataset heatmap example:

![Image](https://github.com/user-attachments/assets/d59d1882-2c17-45da-868d-e03122291445)

Heatmap example from a past dataset, where I could successfully call loops without issue:

![Image](https://github.com/user-attachments/assets/417ed610-0ec9-4d5e-8a22-1210716cb3f2)

Both at 10kb resolution

**Comment by gfudenberg** [comment]
hi @ieres-amgen -- it looks like there are few if any reads off the main diagonal, I would be worried that the experiment some didn't work and only produced molecular byproducts

**Comment by ieres-amgen** [comment]
But I have plenty of good QC plots from the multiQC produced from running Hi-C Pro on these samples, that suggests a good number of reads are there to inform about cis-long-range contacts. These are also visualizing 10kb resolution maps across 5 Mb, so yes, it doesn't look like there are many reads off the main diagonal--but this is due to the full scale here. If we set vmax to, e.g., 100, they look like:

![Image](https://github.com/user-attachments/assets/0f00002a-1895-4cc3-ad5b-7829e3aac183)

![Image](https://github.com/user-attachments/assets/b5e83157-fa52-4275-aa85-b436f52ba367)

It is also worth noting in this reply and in my reply above, that the top map, which appears to have more off-diagonal reads than the bottom, is the one where I'm failing to call loops. The lower plot, that shows even fewer off-diagonal reads in both visualizations, I previously called loops from with no problem, using the exact same setup...
