### ISSUE TITLE
dist_bp and contact_frequency fields missing from CVD function. 

### ISSUE THREAD

**Issue by ratheraarif** [open2c/cooltools#512]
Hi,

Thank you for making such a wonderful package. 
I have an issue! when running the `cvd`  function from the cooltools, it does not generate the `dist_bp` and `contact_freqeuncy` fields. Although I can generate the `dist_bp` by multiplying the dist by `resolution`. I don't know how to generate the `contact_frequency` field.

Kindly help!

<img width="1028" alt="image" src="https://github.com/open2c/cooltools/assets/46924431/d8aec4cb-e0f6-4b0d-8104-0aaf4b0c8ec7">

**Comment by gfudenberg** [comment]
It seems you have an older version of cooltools-- please update to the latest 0.6.1 and let us know if the issue is resolved!
https://pypi.org/project/cooltools/

**Comment by ratheraarif** [comment]
Even after updating to the latest version, the problem is still unsolved.


<img width="1035" alt="image" src="https://github.com/open2c/cooltools/assets/46924431/07695c6e-c1fe-4ade-a4a6-af91a2d894cc">

**Comment by gfudenberg** [comment]
Any guesses @Yaoyx ?

In the meanwhile, you can use the balanced.avg column, and using aggregate_smoothed=True is generally useful!

**Comment by Yaoyx** [comment]
It may be caused by the cache. Restart the kernel for Jupyter notebook might solve the issue

**Comment by Yaoyx** [comment]
Hi @ratheraarif, just in case you want to use the latest features now, you can git clone the repo and in the downloaded repo use`python setup.py install` to manually install the latest package.

**Comment by ratheraarif** [comment]
Thank you!

**Comment by Phlya** [comment]
The package has been updated on PyPI, so I am assuming this is solved now. Feel free to reopen in the issue persists.

**Comment by fengchuiguo1994** [comment]
I had the same problem.
For me, when I remove "chr", generate hic file, convert into mcool, balanced, it's OK 
When I remain "chr", generate hic file, convert into mcool, balanced, it's bad, it well not have dist_bp and contact_frequency.

for short 4dn format
0 chr3 1000 0 1 chr3 2000 1
or
0 3 1000 0 1 3 2000 1 (use this)

for 4dn format
readid chr3 1000 chr3 2000 - +
or
readid 3 1000 3 2000 - + (use this)

This phenomenon occurs in multiple versions.

**Comment by fengchuiguo1994** [comment]
```
cooltools expected-cis hic2cool.mcool::/resolutions/1000 --nproc 5 -o test.1k.tsv
sed '1d' test.1k.tsv | awk '$5!="nan"' | awk '{sum+=$5}END{print sum}'    # 6.78395
```
why the total contact_frequency is 6.78395 not 1

**Comment by Yaoyx** [comment]
Hi,

Here's the definition of contact_frequency in the table:

contact_freq:
            The "most processed" contact frequency value. For example, if balanced & smoothing then this will return the balanced.avg.smooth.agg;
            if aggregated+smoothed, then balanced.avg.smooth.agg; if nothing then count.avg.
