### ISSUE TITLE
cooltools.expected_cis output does not have the 'dist_bp' column

### ISSUE THREAD

**Issue by danobaji** [open2c/cooltools#518]
hi!
i'm following the tutorial notebook on making distance decay plots, using my own data. everything works fine but i noticed my output does not have the 'dist_bp' column. 

i think i can get this by multiplying the 'dist' column by the resolution of my cool file but i was wondering if you can give some insights as to why the 'dist_bp' is missing for my output

thank you!

![image](https://github.com/open2c/cooltools/assets/59674957/a25a5184-b5a9-4c60-8e60-cf44ec720794)

**Comment by Phlya** [comment]
You need to update cooltools to the latest version 0.7.0.

**Comment by danobaji** [comment]
thank you! that solved it )
