### ISSUE TITLE
Issue with pileup example

### ISSUE THREAD

**Issue by erika-anderson** [open2c/cooltools#525]
Hello,

I recently upgraded to cooltools 0.7.1 and encountered an issue with pileups that I hadn't experienced previously when using version 0.5.4. In the Pileups and average features example cell 15, I got this error:

```
stack = cooltools.pileup(clr, sites, view_df=hg38_arms, flank=300_000)
# Mirror reflect snippets when the feature is on the opposite strand
mask = np.array(sites.strand == '-', dtype=bool)
stack[:, :, mask] = stack[::-1, ::-1, mask]

# Aggregate. Note that some pixels might be converted to NaNs after IC, thus we aggregate by nanmean:
mtx = np.nanmean(stack, axis=2)
```
IndexError                                Traceback (most recent call last)
Cell In[49], line 4
      2 # Mirror reflect snippets when the feature is on the opposite strand
      3 mask = np.array(sites.strand == '-', dtype=bool)
----> 4 stack[:, :, mask] = stack[::-1, ::-1, mask]
      6 # Aggregate. Note that some pixels might be converted to NaNs after IC, thus we aggregate by nanmean:
      7 mtx = np.nanmean(stack, axis=2)

IndexError: boolean index did not match indexed array along dimension 2; dimension is 61 but corresponding boolean dimension is 613

With these changes, the pileup worked:
```
stack = cooltools.pileup(clr, sites, view_df=hg38_arms, flank=300_000)
# Mirror reflect snippets when the feature is on the opposite strand
mask = np.array(sites.strand == '-', dtype=bool)
stack[mask,:, :] = stack[mask,::-1, ::-1]

# Aggregate. Note that some pixels might be converted to NaNs after IC, thus we aggregate by nanmean:
mtx = np.nanmean(stack, axis=0)
```

Hopefully this will be helpful to anyone else who encounters a similar problem with the axis order.

**Comment by gfudenberg** [comment]
Thanks!

It looks like the docstring properly reflects the current behavior https://github.com/open2c/cooltools/blame/ab97a0461a9b3b642f36c7597cd17b852c075d46/cooltools/api/snipping.py#L872

Closing for now, but feel free to re-open!
