### ISSUE TITLE
mcool format conversion

### ISSUE THREAD

**Issue by mdozmorov** [open2c/cooltools#527]
It is possible to convert a `format-version: 3` mcool file to `format-version: 2`? A bigger picture - we are [unable to analyze a 4D Nucleome dataset with CoolBox](https://github.com/GangCaoLab/CoolBox/issues/101). Differences in formats is what I could identify, following a 
[ChatGPT conversation](https://github.com/user-attachments/files/16249746/mcool_comparison.md). I feel it is a trivial question but we've been trying for weeks and failing. I will ask @hamy12398 to explore other options but wanted to ask if there is a way to easily convert formats?

**Comment by Phlya** [comment]
CoolBox supports format version 3, I doubt that is the issue...
(Pretty sure it's just uses the `cooler` library to access the data, so any cooler file should be supported I expect.
![Screenshot 2024-07-16 at 17 49 45](https://github.com/user-attachments/assets/b1d0127f-bfe1-4ff1-8f0d-b7c764084b56)

**Comment by nvictus** [comment]
Yeah, I think chatgpt is barking up the wrong tree. The error message suggests coolbox is pulling up an empty array somewhere. It would help to provide a full traceback.

**Comment by mdozmorov** [comment]
It's me interpreting it incorrectly, relatively new to cooltools and Python. Here's [a minimal code to reproduce](https://github.com/GangCaoLab/CoolBox/issues/101#issuecomment-2231690070). There's no traceback, it's just a warning and an empty plot
```
WARNING:plot.py:254 -     matrix_val_range()] zero-size array to reduction operation minimum which has no identity
```

**Comment by mdozmorov** [comment]
Closing and will waif for CoolBox folks to help. Thank you all!
