### ISSUE TITLE
Compare results among samples

### ISSUE THREAD

**Issue by QianzhaoJ** [open2c/cooltools#53]
Hi :
    Now, I have analysed several Hi-C samples that represent different treatments. However , these samples had different counts of mapped reads.
    During downstream analysis , I can see differences in different samples. However, I'm not sure whether those differences are related to treatment or to the difference in mapped reads.
     Whether I should normalize by the number of mapped reads before generating binned matrix ( just like sub-sample from mapped reads or valid pairs after filtering) or after it, before downstream analysis ( just like directly dividing the reads counts in raw or balanced matrix by mapped read counts) ? 
      Can you give me some advice ? 
      Thank you in advance for your time !

Best wishes 
Qianzhao

**Comment by golobor** [comment]
sorry that we did not address this issue in time!
