### ISSUE TITLE
how to get expected contact frequency

### ISSUE THREAD

**Issue by BenxiaHu** [open2c/cooltools#530]
how to get expected contact frequency for each individual locus and its congate locus?
does expected-cis(https://cooltools.readthedocs.io/en/latest/cli.html#cooltools-expected-cis) can do that?
Calculate expected Hi-C signal for cis regions of chromosomal interaction map: average of interactions separated by the same genomic distance, i.e. are on the same diagonal on the cis-heatmap.

if yes, how to interpret the reuslt?
<img width="670" alt="image" src="https://github.com/user-attachments/assets/4bc200de-f161-42b9-88a3-249f02602cf7">

**Comment by gfudenberg** [comment]
hi @BenxiaHu 

I am not sure what you mean by cognate locus. 

Expected-cis does indeed calculate the expected contact frequency as a function of genomic distance. This could in principle vary by region, depending on the arguments passed to the function. If the docstring description is insufficient to understand functionality, you can check out the examples as well:  https://cooltools.readthedocs.io/en/latest/notebooks/contacts_vs_distance.html#Smoothing-&-aggregating-P(s)-curves.

For this expected DataFrame displayed above, the expected would be from the count.avg column. Any loci on chr2_p separated by 3000bp would be expected to have a count of 50.4.

Hopefully this addresses the question-- if not please don't hesitate to re-open!
