### ISSUE TITLE
significant dot-calls are "jumping" to nearby pixel upon clustering/post-processing

### ISSUE THREAD

**Issue by sergpolly** [open2c/cooltools#77]
left - before postprocessing ; right after postprocessing
postprocessing = clustering and thresholding
the lower-left significant pixel is "jumping" ...

![](https://lh3.googleusercontent.com/-Ut9KTxxyntU/XNB78vfEp6I/AAAAAAAAtIs/sb2EpObpOWQsvCd2073ndJn-RthHd7trQCK8BGAs/s0/2019-05-06.png)

this:
![](https://lh3.googleusercontent.com/-XkWPiEPm1zA/XNCCyArdZdI/AAAAAAAAtJE/JI-b7U6BsV06P-ZdTrpIT2mfor2RPGYeQCK8BGAs/s0/2019-05-06.png)
becomes this , after postprocessing:
![](https://lh3.googleusercontent.com/-LZV40bQIZjY/XNCC3MbJfSI/AAAAAAAAtJI/_QMxZMrMCvsCWkQVLCHwpBxVoNYY5bligCK8BGAs/s0/2019-05-06.png)

singleton clustering introducing numerical artifacts ?
try manually https://github.com/mirnylab/cooltools/blob/eca55d68f82a472d0c2d0666ff1a8d7888fccfb8/cooltools/cli/call_dots.py#L342

and https://github.com/mirnylab/cooltools/blob/eca55d68f82a472d0c2d0666ff1a8d7888fccfb8/cooltools/dotfinder.py#L176 
```
	chrom1	start1	end1	weight1	chrom2	start2	end2	weight2	bin1_id	bin2_id	count	la_exp.vertical.value	la_exp.lowleft.value	la_exp.horizontal.value	la_exp.donut.value	la_exp.vertical.qval	la_exp.lowleft.qval	la_exp.horizontal.qval	la_exp.donut.qval
2291	11	110000	112000	0.009687769709	11	182000	184000	0.01086322946	3349	3385	79	48.13751231	45.00522499	47.21019248	42.29654582	0.1336599712	0.02180989959	0.1233427349	0.05482371419
```

as reported by @gfudenberg

**Comment by gfudenberg** [comment]
In other cases it appears as if the max value pixel is not chosen after the clustering step
right - before postprocessing ; 
left- after postprocessing (clustering and thresholding)

![image](https://user-images.githubusercontent.com/19657573/57266076-5d252500-702f-11e9-8a46-abe148bde259.png)

**Comment by sergpolly** [comment]
@gfudenberg could you please provide corresponding dataframe-s or their slices?
Just so it's easier to narrow the problem down to "funny" clustering or a bug in selecting the brightest one from the group

**Comment by gfudenberg** [comment]
[raw.txt](https://github.com/mirnylab/cooltools/files/3150510/error_for_sergey_raw.txt)
[postproc.txt](https://github.com/mirnylab/cooltools/files/3150511/error_for_sergey_postproc.txt)

**Comment by golobor** [comment]
@sergpolly  - still an issue?
