### ISSUE TITLE
FDR calculations intricacy

### ISSUE THREAD

**Issue by sergpolly** [open2c/cooltools#82]
https://github.com/mirnylab/cooltools/blob/d5de964ad4c5123ea6b2026a70ac31c4562c0d71/cooltools/dotfinder.py#L2015

this computes FDR based on sorted p-values and their rank, that is being incremented even for identical p-values  ...

while this https://github.com/mirnylab/cooltools/blob/d5de964ad4c5123ea6b2026a70ac31c4562c0d71/cooltools/dotfinder.py#L1089

- the way it is done in HiCCUPS , assigns identical rank to identical p-values, yet increments to the next group of identical p-values according to the total number of identical p-values in the first group . 

What does `statsmodels` do in this case ? or `scipy` stats ?

**Comment by golobor** [comment]
@sergpolly  - is this still an issue?

**Comment by sergpolly** [comment]
will be resolved in https://github.com/open2c/cooltools/pull/327
added `cummin()` to the table of adjusted p-values , to ensure that q-values(aka adjusted p-values) are decreasing monotonously with p-values, as it is done in `statsmodels`.

Aslo added tests to make sure we understand this and don't brake it going further
