### ISSUE TITLE
compartments calling seems broken? KeyError: 'ignore_diags' line 314

### ISSUE THREAD

**Issue by gtrichard** [open2c/cooltools#98]
Hello cool people,

I recently found out that compartments calling doesn't seem to behave normally (one of our user too: https://github.com/deeptools/HiCExplorer/issues/437). I used matrices coming from HiCExplorer (converted to cool format), and `cooltools call-compartments` is producing the following final error:

```
File "foo/python3.6/site-packages/cooltools/eigdecomp.py", line 314, in cooler_cis_eig
if ignore_diags is None
KeyError: 'ignore_diags'
```

When `None` is replaced by an integer, like `2`, (as defined in `cis_eig ` line 62), it works fine.

I don't think it is related to using HiCExplorer (although, I don't have any cooler processed matrices around to test `cooltools call-compartments` with such a "cooler only" matrix).

Could you have a look?

All the best,
Gautier

**Comment by nvictus** [comment]
Hi Gautier!

Yes, I think the weights that HiCExplorer writes does not include the metadata attributes that `cooler balance` writes. We should have used a default of 2 anyway. You always want to drop at least the main diagonal + 1 when balancing if the data was not already pre-filtered as such.

**Comment by golobor** [comment]
this issue seems to be solved, correct? Feel free to reopen!
